### PR TITLE
#2199 Adding support of placeholder matching between slashes👍 

### LINKED ISSUE #2199: Ocelot can't match placeholders between slashes
## Expected Behavior / New Feature

Ocelot should be capable of matching paths that contain placeholders embedded between slashes, such as: 
`/api/invoices_{url0}/{url1}-{url2}_abcd/{url3}?urlId={url4}.`

## Actual Behavior / Motivation for New Feature

Currently, Ocelot cannot match placeholders embedded between slashes. For example: `/api/test/{url}-2` -> request: `/api/test/a-2` -> the result will incorrectly return `{url} = a-2`.

## Steps to Reproduce the Problem

  1. Try any template with placeholders embedded between slashes

### PR DESCRIPTION
**Pull request by ggnaegi**
## Fixes #2199
- #2199

## Proposed Changes
  - Reworked `UrlPathPlaceholderNameAndValueFinder.cs` supporting now embedded placeholders
  - Pattern matching with Regexes
  
     ```c#
     Regex regex = new($@"\{PlaceHolderLeft}(.*?)\{PlaceHolderRight}", RegexOptions.None, TimeSpan.FromSeconds(1));
     template = EscapeExceptBraces(template);
     string regexPattern = $"^{regex.Replace(template, match => $"(?<{match.Groups[1].Value}>[^&]*)")}";
     ```

  - Some tweaks:
    - If the path template contains a catch-all query, then return the catch-all placeholder with an empty value
    ```c#
    private static (bool IsMatch, string Placeholder) IsCatchAllQuery(string template)
        {
            Regex catchAllQueryRegex = new($@"^[^{{}}]*\?\{PlaceHolderLeft}(.*?)\{PlaceHolderRight}$", RegexOptions.None, TimeSpan.FromMilliseconds(300));
            Match catchAllMatch = catchAllQueryRegex.Match(template);
    
            return (catchAllMatch.Success, catchAllMatch.Success ? catchAllMatch.Groups[1].Value : string.Empty);
        }
    ```
    - If the path template contains a catch all path, then return the catch-all placeholder with an empty value
    - Skipping the query evaluation if not present in the path template
 - Added some unit tests with complex path templates.
 - Added code comments

### CODE REVIEW

**Comment by ggnaegi** [comment]
@raman-m yeaaaah, the checks have passed ;-)

**Comment by raman-m** [comment]
Gui, how quickly do you need this delivered? Do you require the officially released NuGet package, or can you wait for the next v24.0?

File: src/Ocelot/DownstreamRouteFinder/UrlMatcher/UrlPathPlaceholderNameAndValueFinder.cs [hunk 1]
```diff
@@ -1,161 +1,132 @@
 using Ocelot.Responses;
 
-namespace Ocelot.DownstreamRouteFinder.UrlMatcher
+namespace Ocelot.DownstreamRouteFinder.UrlMatcher;
+
+public class UrlPathPlaceholderNameAndValueFinder : IPlaceholderNameAndValueFinder
 {
-    public class UrlPathPlaceholderNameAndValueFinder : IPlaceholderNameAndValueFinder
+    private const string PlaceHolderLeft = "{";
+    private const string PlaceHolderRight = "}";
```
Comment (raman-m) [inline src/Ocelot/DownstreamRouteFinder/UrlMatcher/UrlPathPlaceholderNameAndValueFinder.cs:8]: Can be simply `char`
```suggestion
    private const char PlaceHolderLeft = '{';
    private const char PlaceHolderRight = '}';
```
For readability better to rename to 
- `PlaceHolderLeft` &rarr; `LeftCurlyBracket`
- `PlaceHolderRight` &rarr; `RightCurlyBracket`

File: src/Ocelot/DownstreamRouteFinder/UrlMatcher/UrlPathPlaceholderNameAndValueFinder.cs [hunk 2]
```diff
@@ -1,161 +1,132 @@
...
+    /// - The path template contains placeholders. We return the placeholders with their matching values.
+    /// </summary>
+    /// <param name="path">The request path.</param>
+    /// <param name="query">The query parameters.</param>
+    /// <param name="pathTemplate">The request path template.</param>
+    /// <returns>The list of the placeholders with their matching values.</returns>
+    public Response<List<PlaceholderNameAndValue>> Find(string path, string query, string pathTemplate)
     {
-        public Response<List<PlaceholderNameAndValue>> Find(string path, string query, string pathTemplate)
+        (bool isCatchAllQuery, string catchAllQueryPlaceholder) = IsCatchAllQuery(pathTemplate);
```
Comment (raman-m) [inline src/Ocelot/DownstreamRouteFinder/UrlMatcher/UrlPathPlaceholderNameAndValueFinder.cs:23]: Styling and convention issue of using `Tuple` in a method which should simply return `bool` only.
```suggestion
        bool isCatchAllQuery = IsCatchAllQuery(pathTemplate, out string catchAllQueryPlaceholder);
```

File: src/Ocelot/DownstreamRouteFinder/UrlMatcher/UrlPathPlaceholderNameAndValueFinder.cs [hunk 3]
```diff
@@ -1,161 +1,132 @@
...
-
-            path = $"{path}{query}";
-
-            var counterForPath = 0;
-
-            var delimiter = '/';
-            var nextDelimiter = '/';
-
-            for (var counterForTemplate = 0; counterForTemplate < pathTemplate.Length; counterForTemplate++)
+            return new OkResponse<List<PlaceholderNameAndValue>>(new List<PlaceholderNameAndValue>
```
Comment (raman-m) [inline src/Ocelot/DownstreamRouteFinder/UrlMatcher/UrlPathPlaceholderNameAndValueFinder.cs:26]: Guys, I am tired of the convention of returning `OkResponse<T>` results because I find them overengineered and redundant. If you are refactoring everything, why not simply return a `List<PlaceholderNameAndValue>` object? Please 🙏 Updating the interface is required.

File: src/Ocelot/DownstreamRouteFinder/UrlMatcher/UrlPathPlaceholderNameAndValueFinder.cs [hunk 4]
```diff
@@ -1,161 +1,132 @@
...
-                    counterForTemplate = endOfPlaceholder;
-                    counterForPath = GetNextCounterPosition(path, counterForPath, '?');
-                    continue;
-                }
-
-                counterForPath++;
-            }
-
-            return new OkResponse<List<PlaceholderNameAndValue>>(placeHolderNameAndValues);
+                new($"{PlaceHolderLeft}{catchAllQueryPlaceholder}{PlaceHolderRight}", string.Empty),
```
Comment (raman-m) [inline src/Ocelot/DownstreamRouteFinder/UrlMatcher/UrlPathPlaceholderNameAndValueFinder.cs:28]: Gui, why do you interpolate constant value in the string?
```suggestion
                new($"{{{catchAllQueryPlaceholder}}}", string.Empty),
```

File: src/Ocelot/DownstreamRouteFinder/UrlMatcher/UrlPathPlaceholderNameAndValueFinder.cs [hunk 5]
```diff
@@ -1,161 +1,132 @@
...
+    /// - First, we skip the query if it is not present in the path template.
+    /// - Second, we append a trailing slash to the path if it is a catch-all path.
+    /// </summary>
+    /// <param name="path">The request path.</param>
+    /// <param name="query">The query parameters.</param>
+    /// <param name="template">The path template.</param>
+    /// <returns>The matching groups.</returns>
+    private static IList<Group> FindGroups(string path, string query, string template)
+    {
+        Regex regex = new($@"\{PlaceHolderLeft}(.*?)\{PlaceHolderRight}", RegexOptions.None, TimeSpan.FromSeconds(1));
```
Comment (raman-m) [inline src/Ocelot/DownstreamRouteFinder/UrlMatcher/UrlPathPlaceholderNameAndValueFinder.cs:54]: I just don't get it. Why can't you write a constant `Regex` pattern string? Don't know how to escape special characters? 😄 
```suggestion
        Regex regex = new(@"\{(.*?)\}", RegexOptions.None, TimeSpan.FromSeconds(1));
```
Also keep in mind PR #1348 which I'm working now

File: src/Ocelot/DownstreamRouteFinder/UrlMatcher/UrlPathPlaceholderNameAndValueFinder.cs [hunk 6]
```diff
@@ -1,161 +1,132 @@
...
-            return closingPlaceHolderPositionOnTemplate + 1;
-        }
+    /// <summary>
+    /// Checks if the path template contains a catch-all query parameter.
+    /// It means that the path template ends with a question mark and a placeholder.
+    /// And no other placeholders are present in the path template.
+    /// </summary>
+    /// <param name="template">The path template.</param>
+    /// <returns>True if it matches and the found placeholder.</returns>
+    private static (bool IsMatch, string Placeholder) IsCatchAllQuery(string template)
```
Comment (raman-m) [inline src/Ocelot/DownstreamRouteFinder/UrlMatcher/UrlPathPlaceholderNameAndValueFinder.cs:84]: Styling and convention issue of using `Tuple` in a method which should simply return `bool` only.
```suggestion
    private static bool IsCatchAllQuery(string template, out string placeholder)
```

File: src/Ocelot/DownstreamRouteFinder/UrlMatcher/UrlPathPlaceholderNameAndValueFinder.cs [hunk 7]
```diff
@@ -1,161 +1,132 @@
...
+    /// <param name="template">The path template.</param>
+    /// <returns>True if query should be skipped.</returns>
+    private static bool ShouldSkipQuery(string query, string template) => !string.IsNullOrEmpty(query) && !template.Contains('?');
+
+    /// <summary>
+    /// Escapes all characters except braces, eg { and }.
+    /// </summary>
+    /// <param name="input">The input string.</param>
+    /// <returns>The formatted string.</returns>
+    private static string EscapeExceptBraces(string input)
```
Comment (raman-m) [inline src/Ocelot/DownstreamRouteFinder/UrlMatcher/UrlPathPlaceholderNameAndValueFinder.cs:119]: I really wonder about this method. Why do we have to escape like this?

File: test/Ocelot.UnitTests/DownstreamRouteFinder/UrlMatcher/UrlPathPlaceholderNameAndValueFinderTests.cs [hunk 8]
```diff
@@ -343,22 +310,70 @@ public void can_match_down_stream_url_with_downstream_template_with_place_holder
...
+            this.Given(x => x.GivenIHaveAUpstreamPath("/upstream/test/"))
+                .And(x => x.GivenIHaveAnUpstreamUrlTemplate("/upstream/test/{testId}"))
+                .When(x => x.WhenIFindTheUrlVariableNamesAndValues())
+                .And(x => x.ThenTheTemplatesVariablesAre(expectedTemplates))
+                .BDDfy();
+        }
+
+        [Theory]
+        [InlineData("/api/invoices/{url}-abcd", "/api/invoices/123-abcd", "{url}", "123")]
+        [InlineData("/api/invoices/{url1}-{url2}_abcd", "/api/invoices/123-456_abcd", "{url1}", "123")]
```
Comment (raman-m) [inline test/Ocelot.UnitTests/DownstreamRouteFinder/UrlMatcher/UrlPathPlaceholderNameAndValueFinderTests.cs:333]: Good! Thank you!
Could you write acceptance tests please?

**Review by raman-m — COMMENTED** [review]
My suggestions are below 👇

File: src/Ocelot/DownstreamRouteFinder/UrlMatcher/UrlPathPlaceholderNameAndValueFinder.cs (hunk 3 above)
Comment (ggnaegi) [reply src/Ocelot/DownstreamRouteFinder/UrlMatcher/UrlPathPlaceholderNameAndValueFinder.cs:26]: Yes, but it has side effects everywhere and it's out of scope

File: src/Ocelot/DownstreamRouteFinder/UrlMatcher/UrlPathPlaceholderNameAndValueFinder.cs (hunk 4 above)
Comment (ggnaegi) [reply src/Ocelot/DownstreamRouteFinder/UrlMatcher/UrlPathPlaceholderNameAndValueFinder.cs:28]: We might use other characters as placeholders...

File: src/Ocelot/DownstreamRouteFinder/UrlMatcher/UrlPathPlaceholderNameAndValueFinder.cs (hunk 5 above)
Comment (ggnaegi) [reply src/Ocelot/DownstreamRouteFinder/UrlMatcher/UrlPathPlaceholderNameAndValueFinder.cs:54]: @raman-m wtf! That's a bit rude. As I wrote you earlier, we might want to use other characters as placeholders...

File: src/Ocelot/DownstreamRouteFinder/UrlMatcher/UrlPathPlaceholderNameAndValueFinder.cs (hunk 6 above)
Comment (ggnaegi) [reply src/Ocelot/DownstreamRouteFinder/UrlMatcher/UrlPathPlaceholderNameAndValueFinder.cs:84]: Question of taste again

File: src/Ocelot/DownstreamRouteFinder/UrlMatcher/UrlPathPlaceholderNameAndValueFinder.cs (hunk 7 above)
Comment (ggnaegi) [reply src/Ocelot/DownstreamRouteFinder/UrlMatcher/UrlPathPlaceholderNameAndValueFinder.cs:119]: For performance sake...

File: test/Ocelot.UnitTests/DownstreamRouteFinder/UrlMatcher/UrlPathPlaceholderNameAndValueFinderTests.cs (hunk 8 above)
Comment (ggnaegi) [reply test/Ocelot.UnitTests/DownstreamRouteFinder/UrlMatcher/UrlPathPlaceholderNameAndValueFinderTests.cs:333]: Let's see..

**Comment by raman-m** [comment]
> It's urgent, but, when it is foreseen to release v24.0?

@ggnaegi, I'm OK to release minor version 23.4.0 with the already [merged 2 features](https://github.com/ThreeMammals/Ocelot/compare/main...develop). Will you prepare the release PR for urgent delivery? Will you write the release notes, etc.? Or will our next minor release be without release notes? 😄

**Comment by ggnaegi** [comment]
> > It's urgent, but, when it is foreseen to release v24.0?
> 
> @ggnaegi, I'm OK to release minor version 23.4.0 with the already [merged 2 features](https://github.com/ThreeMammals/Ocelot/compare/main...develop) + this feat. Will you prepare the release PR for urgent delivery? Will you write the release notes, etc.? Or will our next minor release be without release notes? 😄
> 
> > when it is foreseen to release v24.0?
> 
> First days, 1st week of December, I guess...

Ok let's do this, minor version 23.4.0

File: src/Ocelot/DownstreamRouteFinder/UrlMatcher/UrlPathPlaceholderNameAndValueFinder.cs (hunk 5 above)
Comment (raman-m) [reply src/Ocelot/DownstreamRouteFinder/UrlMatcher/UrlPathPlaceholderNameAndValueFinder.cs:54]: Maybe I misunderstood the problem... Doesn't const pattern solve the problem?.. and we have to use interpolation?
Why are you so emotional today? Your client f...ed you? ))

**Comment by raman-m** [comment]
> Ok let's do this, minor version 23.4.0

Approved! Your destiny, Gui, is to write the documentation for the feature. It seems we have to review all [Routing](https://ocelot.readthedocs.io/en/latest/features/routing.html) documentation to inform the community that we support placeholders in the middle.
As you know, the documentation now includes all placeholder examples "between slashes".

File: src/Ocelot/DownstreamRouteFinder/UrlMatcher/UrlPathPlaceholderNameAndValueFinder.cs (hunk 3 above)
Comment (raman-m) [reply src/Ocelot/DownstreamRouteFinder/UrlMatcher/UrlPathPlaceholderNameAndValueFinder.cs:26]: Which side effects? Where some tests failed?

File: src/Ocelot/DownstreamRouteFinder/UrlMatcher/UrlPathPlaceholderNameAndValueFinder.cs (hunk 7 above)
Comment (raman-m) [reply src/Ocelot/DownstreamRouteFinder/UrlMatcher/UrlPathPlaceholderNameAndValueFinder.cs:119]: Not an issue

File: src/Ocelot/DownstreamRouteFinder/UrlMatcher/UrlPathPlaceholderNameAndValueFinder.cs (hunk 2 above)
Comment (raman-m) [reply src/Ocelot/DownstreamRouteFinder/UrlMatcher/UrlPathPlaceholderNameAndValueFinder.cs:23]: Not an issue

File: src/Ocelot/DownstreamRouteFinder/UrlMatcher/UrlPathPlaceholderNameAndValueFinder.cs (hunk 3 above)
Comment (ggnaegi) [reply src/Ocelot/DownstreamRouteFinder/UrlMatcher/UrlPathPlaceholderNameAndValueFinder.cs:26]: It doesn't build anymore and I need to update references...

File: src/Ocelot/DownstreamRouteFinder/UrlMatcher/UrlPathPlaceholderNameAndValueFinder.cs (hunk 5 above)
Comment (ggnaegi) [reply src/Ocelot/DownstreamRouteFinder/UrlMatcher/UrlPathPlaceholderNameAndValueFinder.cs:54]: No no, it's fine, let's do this like that, it's sound for me! And besides, string interpolation has an impact on the performance, we don't want that @raman-m

**Comment by raman-m** [comment]
@ggnaegi Are you going to write acceptance tests and update docs?

File: src/Ocelot/DownstreamRouteFinder/UrlMatcher/UrlPathPlaceholderNameAndValueFinder.cs (hunk 4 above)
Comment (raman-m) [reply src/Ocelot/DownstreamRouteFinder/UrlMatcher/UrlPathPlaceholderNameAndValueFinder.cs:28]: I'm curious... which one? Could you write an example of "other characters as placeholders" plz?

File: src/Ocelot/DownstreamRouteFinder/UrlMatcher/UrlPathPlaceholderNameAndValueFinder.cs (hunk 5 above)
Comment (raman-m) [reply src/Ocelot/DownstreamRouteFinder/UrlMatcher/UrlPathPlaceholderNameAndValueFinder.cs:54]: Yes, we are performance funs. 😉

File: test/Ocelot.UnitTests/DownstreamRouteFinder/UrlMatcher/UrlPathPlaceholderNameAndValueFinderTests.cs
Comment (raman-m) [inline test/Ocelot.UnitTests/DownstreamRouteFinder/UrlMatcher/UrlPathPlaceholderNameAndValueFinderTests.cs:1]: I see a lot of fake changes because of [EOL problem](https://ocelot.readthedocs.io/en/latest/building/devprocess.html#line-ending-gotchas-aka-eol-fun).
Let me help you with this...

**Comment by ggnaegi** [comment]
> @ggnaegi Are you going to write acceptance tests and update docs?

Yes!

**Comment by raman-m** [comment]
The build [failed](https://app.circleci.com/pipelines/github/ThreeMammals/Ocelot/2612/workflows/4312149e-b119-489b-9c0a-1f11d662ea65/jobs/4587?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link&utm_content=summary&invite=true#step-102-883) because of unsupported `can_match_down_stream_url_with_downstream_template_with_place_holder_to_final_url_path` test❗
So, the old feat #89 is broken after refactroring❗
We must support old functionality, at least try to support...

File: test/Ocelot.UnitTests/DownstreamRouteFinder/UrlMatcher/UrlPathPlaceholderNameAndValueFinderTests.cs
Comment (raman-m) [reply test/Ocelot.UnitTests/DownstreamRouteFinder/UrlMatcher/UrlPathPlaceholderNameAndValueFinderTests.cs:1]: #### Fixed in commit https://github.com/ThreeMammals/Ocelot/pull/2200/commits/ee0011cb437ea971b1f0bd262fa9ab22a01dc913 ✔️ 

Additionally, I've removed BDDfy and applied the AAA pattern. As you may already know, we don't use BDDfy when writing new unit tests, so applying the AAA pattern is highly desirable.

The incident with changes for the old #89 unit test will be handled separately.

**Comment by raman-m** [comment]
> Yes, but the old unit test, is totally crap! I'm wondering why it should pass! **It's stupid**

Do you think we had a stupid contributor in #89 ? 😄

**Comment by ggnaegi** [comment]
> > Yes, but the old unit test, is totally crap! I'm wondering why it should pass! **It's stupid**
> 
> Do you think we had a stupid contributor in #89 ? 😄

```c#
this.Given(x => x.GivenIHaveAUpstreamPath("api/product/products/categories/"))
                 .And(x => x.GivenIHaveAnUpstreamUrlTemplate("api/{finalUrlPath}/")) // Gui, don't remove final slash! We should not break old functionality
                 .When(x => x.WhenIFindTheUrlVariableNamesAndValues())
                 .And(x => x.ThenTheTemplatesVariablesAre(expectedTemplates))
                 .BDDfy();
        }
```
Why on earth {finalUrlPath} should match /product/products/categories/ if the slash is not part of it?????

Besides, the acceptance test is passing...

@raman-m

**Review by raman-m — CHANGES_REQUESTED** [review]
Sorry, I require the following missing artifacts from the development process:
- Acceptance test(s) with the same data as the new unit tests
- Updated documentation for the [Routing](https://github.com/ThreeMammals/Ocelot/blob/develop/docs/features/routing.rst) feature, at least draft with ideas to review

#### P.S. Regarding the #89 failed test
I saw that the unit test fails, but the corresponding #89 acceptance test doesn't, which is strange. Logically, both tests should fail together or they should both pass. I recommend carefully reviewing the #89 and syncing the test data, at least for a final decision.

**Comment by ggnaegi** [comment]
> Why on earth {finalUrlPath} should match /product/products/categories/ if the slash is not part of it?????

**Why on earth {finalUrlPath} should match /product/products/categories/ if the slash is not part of it?????**

"api/{finalUrlPath}/" WHYYYYY!!!

**Comment by raman-m** [comment]
> Why on earth {finalUrlPath} should match /product/products/categories/ if the slash is not part of it?????
> Besides, the acceptance test is passing... `should_return_response_200_with_placeholder_for_final_url_path()`
> 

Don't panic! You should breathe deeply. 😊
Well... I saw this last slash; maybe it is an old typo. I mentioned this in the code review summary above. The real problem is that the test data is not synchronized between unit and acceptance tests. That's really bad. OK, I will return to the #89 requirements tomorrow. Now, please concentrate on the other issues from my code review.

**Comment by raman-m** [comment]
@ggnaegi  @ggnaegi 
> "api/{finalUrlPath}/" WHYYYYY!!!

### Don't paaa-aa-anic!
I would prefer not to use the word 'stupid' elsewhere. 😛

**Comment by raman-m** [comment]
Upon reviewing the old #89 tests, I noticed that the author made a typo error in the unit test, specifically an extra `/` on [line 152](https://github.com/ThreeMammals/Ocelot/pull/89/files#diff-fb43948568ed8817619c967965afcbdc5a759571ba9c036f8ef0e0dfa35c6b9fR152), in the first commit that only included the unit test. Subsequently, Tom requested an acceptance test, which lacked a final slash in the test data. To the best of my knowledge, the acceptance test aligns with the requirements described in #89, but the unit test does not. It appears to be a mistyping by the author.

The tests have been reviewed and are now successfully passing. Apologies for any inconvenience over the past two days! For your information, the author implemented a fix in the code, PR [line 47](https://github.com/ThreeMammals/Ocelot/pull/89/files#diff-2477481f0cecac300439c812fe6f6e62cb6f8fcd064fc16c887f84742370cbffR47), which reads `urlPathTemplate.Trim('/').EndsWith(variableName)`. Currently, this fix for the unit test is located at this line: https://github.com/ThreeMammals/Ocelot/blob/da9d6fab6c704baa925d3c1c5fc984f6a9e9c717/src/Ocelot/DownstreamRouteFinder/UrlMatcher/UrlPathPlaceholderNameAndValueFinder.cs#L124, where the slash trimming is still presented as `Trim(delimiter)`. This is why the old typo and the corrected unit test coexist in the codebase. However, this does not align with the actual requirements of feature #89.

If you don't mind, I will refactor both files along with the tests to adhere to our development conventions.
New tests won't change...

**Comment by raman-m** [comment]
> > @ggnaegi Are you going to write acceptance tests and update docs?
> 
> Yes!

When?

**Comment by ggnaegi** [comment]
@raman-m 🤣

**Comment by ggnaegi** [comment]
@raman-m ready

File: docs/features/routing.rst [hunk 9]
```diff
@@ -69,11 +69,26 @@ In order to change this you can specify on a per Route basis the following setti
 
   "RouteIsCaseSensitive": true
 
-This means that when Ocelot tries to match the incoming upstream URL with an upstream template the evaluation will be case sensitive. 
+This means that when Ocelot tries to match the incoming upstream URL with an upstream template the evaluation will be case sensitive.
+
+.. _routing-embedded-placeholders:
+
+Embedded Placeholders [#f1]_
+^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
Comment (raman-m) [inline docs/features/routing.rst:77]: It's okay now. Thank you for writing this! I will review the section again during the release.

File: test/Ocelot.AcceptanceTests/Routing/RoutingTests.cs [hunk 10]
```diff
@@ -1,1237 +1,631 @@
...
+        "/api/categories_home/furniture_items/789?sort=asc", "/api/categories/home-furniture", "?sort=asc")]
+    [InlineData("/api/orders/{order}-{detail}?status={status}", "/api/orders_{order}/{detail}_invoice/{ref}?status={status}", 
+        "/api/orders_987/abc_invoice/123?status=shipped", "/api/orders/987-abc", "?status=shipped")]
+    [InlineData("/api/transactions/{type}-{region}", "/api/transactions_{type}/{region}_summary/{year}?q={query}", 
+        "/api/transactions_sales/NA_summary/2024?q=forecast", "/api/transactions/sales-NA", "?q=forecast")]
+    [InlineData("/api/resources/{resource}-{subresource}", "/api/resources_{resource}/{subresource}_data/{id}?key={apikey}", 
+        "/api/resources_images/photos_data/555?key=xyz123", "/api/resources/images-photos", "?key=xyz123")]
+    [InlineData("/api/accounts/{account}-{detail}", "/api/accounts_{account}/{detail}_info/{id}?opt={option}", 
+        "/api/accounts_admin/settings_info/101?opt=true", "/api/accounts/admin-settings", "?opt=true")]
+    public void ShouldMatchComplexQueriesWithEmbeddedPlaceholders(string downstream, string upstream, string requestUrl, string downstreamPath, string queryString)
```
Comment (raman-m) [inline test/Ocelot.AcceptanceTests/Routing/RoutingTests.cs:430]: Thank you for adding these tests! I have a question.
Does the feat support embedded placeholders within a single query parameter and its value?
For example &rarr; 
- `/api/invoices_{url0}/{url1}-{url2}_abcd/{url3}?Id1={id1}&filter=A{fid1}B&text=quick fox jumped over lazy {animal2} and&etc`

I assume the answer is NO...

**Review by raman-m — APPROVED** [review]
### Ready for Delivery ✅
Feel free to press the magic **Squash** button! 🎉 
If you merge today, I will prepare the release v23.4.0 for tomorrow.
