### PR TITLE
#649 Acceptance tests

### LINKED ISSUE #649: Upstream route templates that end in a slash are not 'found'.
## Expected Behavior / New Feature
When I map a specific route and it ends with a `/` I expect it to match to the same route if there was no ending `/`.

## Actual Behavior / Motivation for New Feature
Given two upstream routes where one differ's only with the last character being an `/` then the Router fails to map to the route and returns a `404`.

## Steps to Reproduce the Problem

First, lets define a sample route configuration:

```json
{
    "ReRoutes": [
        {
            "UpstreamPathTemplate": "/account/authenticate/",  <-- Notice the ENDING slash
            "DownstreamPathTemplate": "/authenticate",
            "DownstreamScheme": "http",
            "DownstreamHostAndPorts": [
                {
                    "Host": "accounts.api",
                    "Port": 80
                }
            ]
        }
    ],
    "GlobalConfiguration": {
        "BaseUrl": "http://localhost:5002"
    }
}
```

When using Postman, try to hit the following routes:

- `HTTP POST http://localhost:5002/account/authenticate` <--- Succeeds
- `HTTP POST http://localhost:5002/account/authenticate/` <-- **FAILS** but expected to succeed.

There's no documentation about this, if this is a 'by design' feature.

## Specifications

  - Version: `11.0.3`

```
C:\Users\PK>dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   2.1.402
 Commit:    3599f217f4

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.402\

Host (useful for support):
  Version: 2.1.4
  Commit:  85255dde3e

.NET Core SDKs installed:
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.301 [C:\Program Files\dotnet\sdk]
  2.1.400 [C:\Program Files\dotnet\sdk]
  2.1.401 [C:\Program Files\dotnet\sdk]
  2.1.402 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.3-servicing-26724-03 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

### PR DESCRIPTION
**Pull request by ks1990cn**
## Fixes #649 
- #649  

Modifying acceptance test case as per issue.

## Proposed Changes

  - Changes done to verify different URLs
  - Adding Traits to recognise easily for issue fixed verified

### CODE REVIEW

File: test/Ocelot.AcceptanceTests/RoutingTests.cs [hunk 1]
```diff
@@ -445,18 +446,22 @@ public void should_return_response_200_when_host_has_trailing_slash()
                 .BDDfy();
         }
 
-        [Fact]
-        public void should_return_ok_when_upstream_url_ends_with_forward_slash_but_template_does_not()
+        [Theory]
+        [InlineData("/products")]
+        [InlineData("/products/")]
+        [Trait("Issue","Should fix issue 649")]
```
Comment (ks1990cn) [inline test/Ocelot.AcceptanceTests/RoutingTests.cs:452]: @raman-m Here I am using Trait attribute here with `Issue` key.
Trait have key,value feature which provides easy way to filter out issue category verification test cases.
I am not writing another test case with method name "should_fix_issue_649", cause it will be eventually same by execution.
We can categorize with `Issue` key when we do verification from checkbox filter in test explorer.
image

Comment (ks1990cn) [reply test/Ocelot.AcceptanceTests/RoutingTests.cs:452]: What are your thoughts on it @raman-m ?

**Comment by raman-m** [comment]
Reviewing...

File: test/Ocelot.AcceptanceTests/RoutingTests.cs (hunk 1 above)
Comment (raman-m) [reply test/Ocelot.AcceptanceTests/RoutingTests.cs:452]: Nice feature of xUnit! Make sense to use...

Comment (raman-m) [reply test/Ocelot.AcceptanceTests/RoutingTests.cs:452]: Officially it is better to have separate tests for the issue to close it finally
