### PR TITLE
#1288 Query string char missing

### LINKED ISSUE #1288: route -url char missing
# Route Bug

## Steps to Reproduce the Problem
1. Ocelot run at **localhost:9999** with configuration:
```json
{
      "DownstreamPathTemplate": "/cpx/t1/{id}",
      "DownstreamScheme": "http",
      "DownstreamHostAndPorts": [
        {
          "Host": "localhost",
          "Port": 5002
        }
      ],
      "UpstreamPathTemplate": "/safe/{id}",
      "UpstreamHttpMethod": [ "Get" ],
      "AllowAutoRedirect": true
}
```
2. Then call `http://localhost:9999/safe/3?id1=2312`  then log is:
```
info: Ocelot.Requester.Middleware.HttpRequesterMiddleware[0]
      requestId: 0HM17NUPUA37Q:00000001, previousRequestId: no previous request id, message: 200 (OK) status code, 
request uri: http://localhost:5002/cpx/t1/3?d1=2312
```
it should be `xxxx?id1=2312` , **The char `i` disappeared, id1 &rarr; d1**

## Specifications

  - Version: Ocelot **16.0.1**
  - Platform: **win10**

### PR DESCRIPTION
**Pull request by jlukawska**
## Proposed Changes
- the regex that is used to replace placeholder name and value should be used also in the `if` condition before
- The last commit fixed one more problem: when a query param was not the first one, it hadn't been removed.

### CODE REVIEW

**Comment by jlukawska** [comment]
- The last commit fixed one more problem: when a query param was not the first one, it hadn't been removed.

**Review by raman-m — APPROVED** [review]
Hi **J**!
Thank you for the PR and bug fixing!

**Comment by raman-m** [comment]
@TomPallister 
Hi Tom!
It is time to review and merge, please... 🙏

**Comment by raman-m** [comment]
The [feature branch](/jlukawska/Ocelot/tree/fix/1288-query-string-char-missing) has been [rebased](#event-10049077338) onto [ThreeMammals:develop](../tree/develop) successfully!
Code review has started...

---

@yangbocheng As a reporter of the bug #1288 ,
Could you verify this bug fixing solution please?
Thanks!

**Review by RaynaldM — APPROVED** [review]

**Review by wast — APPROVED** [review]

File: test/Ocelot.AcceptanceTests/RoutingWithQueryStringTests.cs [hunk 1]
```diff
@@ -247,8 +243,49 @@ public void should_return_response_200_with_query_string_upstream_template_multi
...
+                        },
+                    },
+            };
 
+            this.Given(x => x.GivenThereIsAServiceRunningOn($"http://localhost:{port}", $"/cpx/t1/{idValue}", $"?{queryName}={queryValue}", 200, "Hello from Laura"))
+                .And(x => _steps.GivenThereIsAConfiguration(configuration))
+                .And(x => _steps.GivenOcelotIsRunning())
+                .When(x => _steps.WhenIGetUrlOnTheApiGateway($"/safe/{idValue}?{queryName}={queryValue}"))
+                .Then(x => _steps.ThenTheStatusCodeShouldBe(HttpStatusCode.OK))
+                .And(x => _steps.ThenTheResponseBodyShouldBe("Hello from Laura"))
```
Comment (raman-m) [inline test/Ocelot.AcceptanceTests/RoutingWithQueryStringTests.cs:285]: OK. But where is a And-check that the query string was copied?
Where is And-check that expected `queryName` is in query string?
What is the predicate of "copying"?
Does it mean if copying failed then the step `ThenTheStatusCodeShouldBe(HttpStatusCode.OK))` fails too?

File: test/Ocelot.UnitTests/DownstreamUrlCreator/DownstreamUrlCreatorMiddlewareTests.cs [hunk 2]
```diff
@@ -137,7 +129,39 @@ public void should_replace_query_string_but_leave_non_placeholder_queries()
...
+                .And(x => GivenTheServiceProviderConfigIs(config))
+                .And(x => x.GivenTheUrlReplacerWillReturn("api/units/1/2/updates"))
+                .When(x => x.WhenICallTheMiddleware())
+                .Then(x => x.ThenTheDownstreamRequestUriIs("https://localhost:5000/api/units/1/2/updates?productId=2"))
+                .And(x => ThenTheQueryStringIs("?productId=2"))
+                .BDDfy();
+        }
+
+        [Fact]
+        public void should_replace_query_string_but_leave_non_placeholder_queries_2()
```
Comment (raman-m) [inline test/Ocelot.UnitTests/DownstreamUrlCreator/DownstreamUrlCreatorMiddlewareTests.cs:142]: Do we cover the user scenario reported in 1288?

**Review by raman-m — APPROVED** [review]

**Comment by raman-m** [comment]
@TomPallister 
This PR is ready to merge.
