### PR TITLE
#1660 Huge logs because of StyleCop.Analyzers warnings

### LINKED ISSUE #1660: Huge logs because of StyleCop.Analyzers warnings
## Expected Behavior
**No** [StyleCop.Analyzers](https://www.nuget.org/packages/StyleCop.Analyzers/) warnings in build logs: [CircleCI](https://app.circleci.com/pipelines/github/ThreeMammals/Ocelot), VS Output Build, VS Error List Warnings.

## Actual Behavior
Current CI-build [690](https://circleci.com/gh/ThreeMammals/Ocelot/690) for latest top commit of develop branch: [push code coverage for main and develop branches](https://github.com/ThreeMammals/Ocelot/commit/bc25f4e8d1a10122538aecead200cec20f0f166c).
- The [690](https://circleci.com/gh/ThreeMammals/Ocelot/690) CI-build has [1729 Warning(s)](https://app.circleci.com/pipelines/github/ThreeMammals/Ocelot/405/workflows/c4af2cbd-41f1-43a3-9dde-5dac41d40523/jobs/690?invite=true#step-102-545) for [Ocelot.AcceptanceTests](../blob/develop/test/Ocelot.AcceptanceTests/Ocelot.AcceptanceTests.csproj) project.
- Visual Studio Error List shows 1728 Warnings: 
image
- Visual Studio Output Build shows SA-warnings in these projects:
  Ocelot.UnitTests
  Ocelot.AcceptanceTests
  Ocelot.IntegrationTests
  Ocelot.ManualTest
  Ocelot.Benchmarks
  Ocelot.Administration
  Ocelot.Provider.Eureka
  Ocelot.Provider.Polly
  Ocelot.Cache.CacheManager
  Ocelot.Provider.Consul
  and the main **Ocelot** project.
- No [StyleCop.Analyzers](https://www.nuget.org/packages/StyleCop.Analyzers/) references in projects:
  [Ocelot.Provider.Kubernetes](../blob/develop/src/Ocelot.Provider.Kubernetes/Ocelot.Provider.Kubernetes.csproj#L30-L33)
  [Ocelot.Tracing.Butterfly](../blob/develop/src/Ocelot.Tracing.Butterfly/Ocelot.Tracing.Butterfly.csproj#L30-L33)
  [Ocelot.Tracing.OpenTracing](../blob/develop/src/Ocelot.Tracing.OpenTracing/Ocelot.Tracing.OpenTracing.csproj#L14-L16)

## Steps to Reproduce the Problem
  1. The CI-build: [690](https://circleci.com/gh/ThreeMammals/Ocelot/690) or any latest builds of [Ocelot](https://app.circleci.com/pipelines/github/ThreeMammals/Ocelot) pipeline
  1. The **develop** branch. Open solution. Visual Studio **Error List** window. Select **Warnings** tab.
  1. The **develop** branch. Open and build solution. Visual Studio **Output Build** window. Build console output is full of warnings.

## Specifications
  - Version: **19.0.2**
  - Platform: Any, Windows

### PR DESCRIPTION
**Pull request by raman-m**
## Fixes #1660
A long list of [StyleCop.Analyzers](https://www.nuget.org/packages/StyleCop.Analyzers/) warnings in build logs: [CircleCI](https://app.circleci.com/pipelines/github/ThreeMammals/Ocelot), VS Output Build, VS Error List Warnings.

## Proposed Changes
- [Add StyleCop.Analyzers package](https://github.com/ThreeMammals/Ocelot/pull/1663/commits/371d8cfe0082ab8af92d8d40e28be8c35810369f) to Ocelot.Provider.Kubernetes, Ocelot.Tracing.Butterfly, Ocelot.Tracing.OpenTracing
- Fix SA* StyleCop warnings
- Fix CA* C# Styling warnings
- Fix CS* C# warnings
- Fix IDE* C# errors, warnings and info
- Upgrade **Basic** and **K8s** samples to ASP.NET 7 to fix warnings and apply ASP.NET 7 MVC templates

### CODE REVIEW

**Comment by raman-m** [comment]
@RaynaldM  Hey Ray!
Could you review my PR please?

File: src/Ocelot/Multiplexer/SimpleJsonResponseAggregator.cs [hunk 1]
```diff
@@ -82,7 +82,7 @@ private static async Task MapAggregateContent(HttpContext originalContext, List<
 
             var stringContent = new StringContent(contentBuilder.ToString())
             {
-                Headers = { ContentType = new MediaTypeHeaderValue("application/json") }
+                Headers = { ContentType = new MediaTypeHeaderValue("application/json") },
```
Comment (RaynaldM) [inline src/Ocelot/Multiplexer/SimpleJsonResponseAggregator.cs:85]: comma is useless

Comment (raman-m) [reply src/Ocelot/Multiplexer/SimpleJsonResponseAggregator.cs:85]: In the previous version (target):

image

This is [SA1413](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1413.md) StyleCop rule. 

> ## Cause
>
>The last statement in a multi-line C# initializer or list is missing a trailing comma.
>
>### Rationale
>
>This rule is specifically designed to work well with the most widely used source control systems as an aid to long-term
code review. By placing a comma on the last line of a multi-line sequence, developers who append an item to the list or reorder the list at some point in the future will not need to modify any more lines than absolutely necessary for the
change. As a result, the size of the subsequent code review is minimized and focused, and tools like **git blame**
continue to show the original author and commit for the item that was previously last in the list.

I believe the most importand part of the Rationale is:
> and focused, and tools like **git blame**
continue to show the original author and commit for the item that was previously last in the list.

So, the restriction of **git** compare/diff tool is tracking changes per line. That's why this rule was introduced in StyleCop Analyzer. The history of the line should not be overridden by absent comma if the next line will be changed in future.
Yeah, now I have overridden the author of this line. But that's how to fix it.
That's why I fixed the violation of SA1413 rule.

Finally,
I believe this is not a major issue to fix, but thank you for your comment!
