### PR TITLE
#1590 Use correct interval for request counting

### LINKED ISSUE #1590: Rate Limiting works incorrectly if `PeriodTimespan` value is greater than `Period`
## Expected Behavior
[Rate Limiting](../blob/develop/docs/features/ratelimiting.rst) works as documented for such parameter values:
- **Period**: 1 second
- **PeriodTimespan**:  30 seconds
- **Limit**: 100

**Scenario**:
Request flow, 10-20 requests per sec, should be allowed.

**Status**: not equal to **429**

## Actual Behavior / Motivation for New Feature
With the same parameter values from **Expected Behavior** Ocelot returns status **429** aka "Rate limit exceeded".
It seems this issue caused by code in the `if (entry.HasValue)` block:
https://github.com/ThreeMammals/Ocelot/blob/0b247afdf0c9cba7fd37f603102d151dc7e74487/src/Ocelot/RateLimit/RateLimitCore.cs#L31-L39

Ocelot increments request counter if request has been received in interval: `[FirstRequestTime : FirstRequestTime + PeriodTimeSpan]` 
According to [the documentation](https://ocelot.readthedocs.io/en/latest/features/ratelimiting.html) counter should be incremented if request is in interval: `[FirstRequestTime : FirstRequestTime + Period]`.

## Steps to Reproduce the Problem

1. Set **Rate Limiting** configuration parameters:
  - **Period**: 1 second
  - **PeriodTimespan**: 30 seconds
  - **Limit**: 100
 3. Generate a consequent request flow (10-20 requests per second) for more than 12 seconds
 4. Ensure Ocelot returns status **429**

## Specifications
- Ocelot Version: **Latest**, [**19.0.2**](https://www.nuget.org/packages/Ocelot/19.0.2)
- Feature: [Rate Limiting](https://ocelot.readthedocs.io/en/latest/features/ratelimiting.html)

### PR DESCRIPTION
**Pull request by sergio-str**
## Fixes #1590 
- #1590 

Incrementing request counter if request time is in the interval
`[FirstRequestTime, FirstRequestTime + PeriodTimespan]` seems is incorrect. **PeriodTimespan** is a "ban" period, not a period for request counting. In case of **PeriodTimespan** interval significantly exceeds **Period**, Rate Limiting feature counts number of requests longer than expected. It leads to false rate limit exceeding error.

## Proposed Changes
Increment request counter when request time within interval
`[FirstRequestTime, FirstRequestTime + RateLimitingSettingPeriod]` respectively to the [Rate Limiting](../blob/develop/docs/features/ratelimiting.rst) docs.

### CODE REVIEW

**Comment by raman-m** [comment]
Hi Sergii!

Thanks for the solution and interest in the project!

I've resolved one merge conflict. And pipelines are green.
Could we discuss the issue #1590 first plz?

**Comment by sergio-str** [comment]
Yes, sure.

**Comment by sergio-str** [comment]
Yes, sure.

**Comment by raman-m** [comment]
Sergii,

Now I see that at least your changes don't break current features.
But we have 2 parents in commit [Merge branch 'develop' into Rate_linit_counting_interval_fix__issue_#…](https://github.com/ThreeMammals/Ocelot/pull/1592/commits/a26e1ac3dddd8f452611478397ef20987ecb342c).
I'm not a fan of merge commits with two parents after conflicts resolution, because they make non-linear history in base branch.
You need to put your commits on the top commit from **base:develop**!

Could I ask you to re-create PR please? Unfortunately your [feature branch](https://github.com/sergio-str/Ocelot/tree/Rate_linit_counting_interval_fix__issue_%231590) is broken. Your forked **develop** branch must be the same as **develop** branch in source repo!

- Just backup files please with new changes.
- Remove current fork, and make new fork to be sure you have the same history as in source repo having all commits up to date
  Or pull down all **base:develop** commits 
- Don't apply changes in **develop**, just keep it updated via pull operation always, just for future usage
- Create new feature branch from **develop** one, for example, **feat/1590**
- Apply new changes from files backup.
- Create new PR
- Do not forget to link both PRs (old and new ones) for tracking purposes

As soon as you've created new PR, this PR will be closed as duplicate.
Thanks!

**Comment by sergio-str** [comment]
Hello Raman.
Sorry for significant delay, many things required my attention. 
First, let me please confirm that you title and descr update is correct.
As for my implementation, I have a small doubt concerning timing calculation. I need to recheck them, and, perhaps, extend existing tests. Unfortunately I could not promise I will have solved it fast, but I will do all my best to finish with code changes in 2-3 weeks.
Cheers
S.

**Comment by raman-m** [comment]
No worries, Sergii!
Take some time to finish the solution!
Tom will wait for your fix for a couple of years. 🤣 It's a joke!

**Comment by raman-m** [comment]
Sergii,
Please merge [PR 1](/sergio-str/Ocelot/pull/1) to update your repo!
Thank you!

**Comment by raman-m** [comment]
[sergio-str](https://github.com/sergio-str) commented [on May 29, 2023](#issuecomment-1567081447):
> Unfortunately I could not promise I will have solved it fast, but I will do all my best to finish with code changes in 2-3 weeks.

Well... 3 weeks have been passed.
Any progress on that?
May I help you with this PR by some pair programming?

**Comment by raman-m** [comment]
The [feature branch](/sergio-str/Ocelot/tree/Rate_linit_counting_interval_fix__issue_%231590) has been [rebased](#event-10309430240) onto [ThreeMammals:develop](../tree/develop)!
**Welcome to code review!**
I guess we can develop and review the code simultaneously.

**Review by raman-m — CHANGES_REQUESTED** [review]
```diff
! There are no unit and acceptance tests!
```
@sergio-str  Sergii,
I believe writing tests will help you to understand, check and improve your solution.
I hope you will be able to write test which should show the correctness of your assumption that  calculations and intervals are incorrect now.

**Review by RaynaldM — APPROVED** [review]

**Comment by raman-m** [comment]
>@RaynaldM approved these changes [on Sep 18](#pullrequestreview-1630365268)

I would rather **do not** approve PR without any tests. And sorry, I think I asked to review too early.

**Comment by raman-m** [comment]
The branch has been [rebased](https://github.com/ThreeMammals/Ocelot/pull/1592#event-12494715401) onto [release/24.0](https://github.com/ThreeMammals/Ocelot/tree/release/24.0) with top commit https://github.com/ThreeMammals/Ocelot/commit/59b63eab9c2cd2ab33c5752bbc3bd00a079cd74c !

**Comment by raman-m** [comment]
### ⚠️ Development Complete❕
@RaynaldM @ggnaegi Could you please review?
The remaining work involves testing the user scenario from #1590. I will add a few tests in the next day or two.
I anticipate that the user scenario tests will be completed by Monday.

I was somewhat taken aback by the code quality. This is the oldest Ocelot feature that was not covered by unit tests, although it does have some very basic acceptance tests.
The feature was initially developed in PR #37 back in 2017.

**Comment by ggnaegi** [comment]
@raman-m Yes, around midnight your time!

File: src/Ocelot/RateLimiting/RateLimiting.cs [hunk 1]
```diff
@@ -0,0 +1,195 @@
...
+    }
+
+    public virtual RateLimitCounter ProcessRequest(ClientRequestIdentity identity, RateLimitOptions options)
+    {
+        RateLimitCounter counter;
+        var rule = options.RateLimitRule;
+        var counterId = GetStorageKey(identity, options);
+
+        // Serial reads and writes
+        lock (ProcessLocker)
```
Comment (ggnaegi) [inline src/Ocelot/RateLimiting/RateLimiting.cs:25]: I'm wondering why you are using lock only for the lines 26-29, why not 26-49? MemoryCache is thread safe yes, but the implemented logic isn't.

File: src/Ocelot/RateLimiting/RateLimiting.cs [hunk 2]
```diff
@@ -0,0 +1,195 @@
...
+        if (startedAt + ToTimespan(rule.Period) >= now) // counting Period is active
+        {
+            var exceededAt = total >= rule.Limit && !counter.ExceededAt.HasValue // current request number equals to the limit
+                ? now // the exceeding moment is now, the next request will fail but the current one doesn't
+                : counter.ExceededAt;
+            return new RateLimitCounter(startedAt, exceededAt, total); // deep copy
+        }
+
+        var wasExceededAt = counter.ExceededAt;
+        if (wasExceededAt + TimeSpan.FromSeconds(rule.PeriodTimespan) >= now) // ban PeriodTimespan is active
```
Comment (ggnaegi) [inline src/Ocelot/RateLimiting/RateLimiting.cs:78]: Might be converted to return statement...

File: src/Ocelot/RateLimiting/MemoryCacheRateLimitStorage.cs [hunk 3]
```diff
@@ -1,28 +1,34 @@
...
-
-        public RateLimitCounter? Get(string id) => _memoryCache.TryGetValue(id, out RateLimitCounter counter) ? counter : null;
-
-        public void Remove(string id)
-        {
-            _memoryCache.Remove(id);
-        }
-    }
+
+namespace Ocelot.RateLimiting
```
Comment (ggnaegi) [inline src/Ocelot/RateLimiting/MemoryCacheRateLimitStorage.cs:3]: Since you refactored the whole rate limiting feature, why not use file scoped namespaces?

File: src/Ocelot/RateLimiting/DistributedCacheRateLimitStorage.cs [hunk 4]
```diff
@@ -1,13 +1,19 @@
...
-    public class DistributedCacheRateLimitCounterHandler : IRateLimitCounterHandler
+    /// <summary>
+    /// Custom storage based on a distributed cache of a remote/local services.
+    /// </summary>
+    /// <remarks>
+    /// See the <see cref="IDistributedCache"/> interface docs for more details.
+    /// </remarks>
+    public class DistributedCacheRateLimitStorage : IRateLimitStorage
     {
         private readonly IDistributedCache _memoryCache;
```
Comment (ggnaegi) [inline src/Ocelot/RateLimiting/DistributedCacheRateLimitStorage.cs:14]: Not part of the PR, but since you are refactoring it, the code could be simplified.
```c#
public void Set(string id, RateLimitCounter counter, TimeSpan expirationTime) => 
    _memoryCache.SetString(id, JsonConvert.SerializeObject(counter), new DistributedCacheEntryOptions().SetAbsoluteExpiration(expirationTime));

public bool Exists(string id) => !string.IsNullOrEmpty(_memoryCache.GetString(id));

public void Remove(string id) => _memoryCache.Remove(id);
```

File: src/Ocelot/RateLimiting/IRateLimiting.cs [hunk 5]
```diff
@@ -0,0 +1,60 @@
...
+    /// <summary>
+    /// Gets the seconds to wait for the next retry by starting moment and the rule.
+    /// </summary>
+    /// <remarks>The method must be called after the counting by the <see cref="Count(RateLimitCounter?, RateLimitRule)"/> method is completed; otherwise it doesn't make sense.</remarks>
+    /// <param name="counter">The counter with starting moment inside.</param>
+    /// <param name="rule">The limiting rule.</param>
+    /// <returns>A <see cref="double"/> value in seconds.</returns>
+    double RetryAfter(RateLimitCounter counter, RateLimitRule rule);
+
+    void SaveCounter(ClientRequestIdentity identity, RateLimitOptions options, RateLimitCounter counter, TimeSpan expiration);
```
Comment (ggnaegi) [inline src/Ocelot/RateLimiting/IRateLimiting.cs:52]: This method is implemented in RateLimiter but isn't used anywhere...

**Review by ggnaegi — COMMENTED** [review]
Ok, some questions from my side, but then ok. Thanks!

File: src/Ocelot/RateLimiting/RateLimiting.cs (hunk 1 above)
Comment (raman-m) [reply src/Ocelot/RateLimiting/RateLimiting.cs:25]: Correct! I plan(ed) to undertake more refactoring in the next PR to achieve 100% coverage for the feature, as the current PR resolves the reported bug. However, testing the feature was challenging due to the absence of unit tests and DI interfaces, this is the main reason of refactoring. Since you've highlighted the issue with the locking block, let's address this in the current PR.

Comment (raman-m) [reply src/Ocelot/RateLimiting/RateLimiting.cs:32]: Fixed in commit https://github.com/ThreeMammals/Ocelot/pull/1592/commits/ebd24a1180189d1ea496fe7e6896a9fc9ba5838e ✔️

File: src/Ocelot/RateLimiting/RateLimiting.cs (hunk 2 above)
Comment (raman-m) [reply src/Ocelot/RateLimiting/RateLimiting.cs:85]: Are you asking to condense the code from this line into a **single** `return` statement?

Comment (raman-m) [reply src/Ocelot/RateLimiting/RateLimiting.cs]: Fixed in commit https://github.com/ThreeMammals/Ocelot/pull/1592/commits/f70fc80adf5aca1c74525c836b3cb683e1051c27 ✔️

File: src/Ocelot/RateLimiting/MemoryCacheRateLimitStorage.cs (hunk 3 above)
Comment (raman-m) [reply src/Ocelot/RateLimiting/MemoryCacheRateLimitStorage.cs:3]: Indeed, it's important to note that the GitHub diff tool highlights the entire file or namespace block when:
- transitioning between file-scoped and block-scoped namespaces,
- renaming or relocating a code file.

However, the Visual Studio Diff tool, also known as Blame, along with GitHub Blame, function effectively, pinpointing only the precise changes.
This issue is exclusive to GitHub PRs.
Nonetheless, converting to file-scoped namespaces makes sense because of significant refactoring...

Comment (raman-m) [reply src/Ocelot/RateLimiting/MemoryCacheRateLimitStorage.cs]: Fixed in commit https://github.com/ThreeMammals/Ocelot/pull/1592/commits/b862dc310aa9da15eae6f532149cd9d65f6a77dd ✔️ 

#### Files skipped
- `src/Ocelot/RateLimiting/Middleware/RateLimitingMiddleware.cs`: the file is old and I want to point your attention to the exact changes
- all old test classes except new ones

File: src/Ocelot/RateLimiting/DistributedCacheRateLimitStorage.cs (hunk 4 above)
Comment (raman-m) [reply src/Ocelot/RateLimiting/DistributedCacheRateLimitStorage.cs]: Fixed in commit https://github.com/ThreeMammals/Ocelot/pull/1592/commits/2b0639cc3adfeffc812f785d39e9e72fb052057f ✔️

File: src/Ocelot/RateLimiting/IRateLimiting.cs (hunk 5 above)
Comment (raman-m) [reply src/Ocelot/RateLimiting/IRateLimiting.cs]: Removed in commit https://github.com/ThreeMammals/Ocelot/pull/1592/commits/b3f0d8708d0ecb6c99c60d6bb3f91d70e368ab0c ✔️

**Comment by raman-m** [comment]
All [code review issues](https://github.com/ThreeMammals/Ocelot/pull/1592#pullrequestreview-2039549596) have been resolved! Awaiting your approval, @ggnaegi.

**Review by ggnaegi — APPROVED** [review]

**Review by raman-m — APPROVED** [review]
Approved, but the rest of work is 👇 
- [ ] Update feature docs
