### PR TITLE
#2165 Global configuration `SecurityOptions`

### LINKED ISSUE #2165: Issue with IP Blocking and Allowing in global configuration
I configured IP blocking and allowing in Ocelot using SecurityOptions, but it's not working.

 
```
{
  "GlobalConfiguration": {
    "BaseUrl": "http://localhost:5000",
    "SecurityOptions": {
      "IPBlockedList": ["192.168.0.23"]
    }
  }
}


```

The IP blocking configuration is not working as expected.

### PR DESCRIPTION
**Pull request by Fabman08**
## Closes #2165 
- #2165 

## Proposed Changes

As the issue #2165 reports, the `SecurityOptions` are missing in `GlobalConfiguration`.

This pull request adds the ability to configure Allowed and Blocked IPs globally: the global configuration will be applied for every route unless an existing `SecurityOptions` is present on it

### CODE REVIEW

**Review by raman-m — CHANGES_REQUESTED** [review]
### Absence of Acceptance Tests❗
What I realized, currently, there are no [Security acceptance tests](https://github.com/search?q=repo%3AThreeMammals%2FOcelot+Security+path%3A%2F%5Etest%5C%2F%2F+path%3A%2F%5Etest%5C%2FOcelot%5C.AcceptanceTests%5C%2F%2F&type=code) in place, which is undoubtedly a significant concern.

Please develop acceptance tests:
- Create "Security" folder in [Ocelot.AcceptanceTests](https://github.com/ThreeMammals/Ocelot/tree/develop/test/Ocelot.AcceptanceTests) project
- Add `IpSecurityTests` class inheriting from `Steps`
- Develop basic config tests

File: src/Ocelot/Configuration/Creator/SecurityOptionsCreator.cs [hunk 1]
```diff
@@ -35,5 +27,21 @@ public SecurityOptions Create(FileSecurityOptions securityOptions)
...
+            {
+                if (IPAddressRange.TryParse(ipValue, out var ipAddressRange))
+                {
+                    var ips = ipAddressRange.Select<IPAddress, string>(x => x.ToString());
+                    ipList.AddRange(ips);
+                }
+            }
+
+            return ipList;
+        }
```
Comment (RaynaldM) [inline src/Ocelot/Configuration/Creator/SecurityOptionsCreator.cs:45]:
```suggestion
       private static IReadOnlyCollection<string> SetIpAddressList(IList<string> ipValueList)
{
    return ipValueList
        .Where(ipValue => IPAddressRange.TryParse(ipValue, out _))
        .SelectMany(ipValue => IPAddressRange.Parse(ipValue).Select(ip => ip.ToString()))
        .ToArray();
}
```

**Review by RaynaldM — APPROVED** [review]

File: src/Ocelot/Configuration/Creator/SecurityOptionsCreator.cs (hunk 1 above)
Comment (Fabman08) [reply src/Ocelot/Configuration/Creator/SecurityOptionsCreator.cs:45]: @RaynaldM I've to modify `.Select(ip => ip.ToString())` into `.Select<IPAddress, string>(ip => ip.ToString())` otherwise the code doesn't build.  I've to modify also the `SecurityOptions` class due to the constructor parameters actually set to `List<string>`

Comment (raman-m) [reply src/Ocelot/Configuration/Creator/SecurityOptionsCreator.cs:45]: You may modify the `SecurityOptions` constructors to generalize with more abstract types such as `IList<string>` or `IEnumerable<string>` if necessary.

Comment (Fabman08) [reply src/Ocelot/Configuration/Creator/SecurityOptionsCreator.cs:45]: @raman-m yes, my comment is strictly referred to _Commit suggestion action_ because the project won't build 😊

Comment (Fabman08) [reply src/Ocelot/Configuration/Creator/SecurityOptionsCreator.cs]: commit reverted and splitted into 3 different ones.

**Comment by raman-m** [comment]
Dear Fabrizio,
Why are you pushing commits to the origin when the tests fail? Please verify that the tests pass locally before pushing new commits to the origin. My mailbox is overflowing with failed build reports from your feature branch!

**Comment by Fabman08** [comment]
> Dear Fabrizio, Why are you pushing commits to the origin when the tests fail? Please verify that the tests pass locally before pushing new commits to the origin. My mailbox is overflowing with failed build reports from your feature branch!

@raman-m sorry for the mail bombing, but switching to _develop_ and running all tests the result is the following

Ocelot_develop_summary

Am I missing something to run unit test correctly?

**Comment by raman-m** [comment]
Oh, you love screenshots, my dear friend...
image
Current builds in develop: **Passed**
Top commit checks status: https://github.com/ThreeMammals/Ocelot/commit/ce0227c059f220761acc2d880e554174bdb3c544 has [passed](https://github.com/ThreeMammals/Ocelot/runs/31636398913)
All CircleCI builds here: [develop builds](https://app.circleci.com/pipelines/github/ThreeMammals/Ocelot?branch=develop)

**Comment by raman-m** [comment]
> but switching to develop and running all tests the result is the following

Regarding the execution of tests in Visual Studio locally, we have certain precise tests that are highly sensitive to CPU resource availability. These tests generally pass when run silently through the terminal. They are designed to pass 99% of the time, but occasionally they may fail. In Visual Studio, additional UI tasks may be running, and if your PC's CPU is at 90-100% capacity, these precise tests might fail. Usually, running the tests again resolves the issue. Ensure that your PC's CPU is not busy, and Visual Studio is not engaged in background compilation or other intensive tasks. If the tests fail, attempt to run them once more.

**Comment by raman-m** [comment]
My proof that we should not panic. Below are the results from my local testing in Visual Studio, which indicate that everything is functioning correctly.
image
Everything is fine!

**Review by RaynaldM — APPROVED** [review]

File: src/Ocelot/Security/IPSecurity/IPSecurityPolicy.cs [hunk 2]
```diff
@@ -18,7 +18,7 @@ public async Task<Response> Security(DownstreamRoute downstreamRoute, HttpContex
 
             if (securityOptions.IPBlockedList != null)
             {
-                if (securityOptions.IPBlockedList.Exists(f => f == clientIp.ToString()))
+                if (securityOptions.IPBlockedList.Contains(clientIp.ToString()))
```
Comment (ggnaegi) [inline src/Ocelot/Security/IPSecurity/IPSecurityPolicy.cs:21]: ClientIp could be null, it's not handled

File: src/Ocelot/Security/IPSecurity/IPSecurityPolicy.cs [hunk 3]
```diff
@@ -27,7 +27,7 @@ public async Task<Response> Security(DownstreamRoute downstreamRoute, HttpContex
 
             if (securityOptions.IPAllowedList?.Count > 0)
```
Comment (ggnaegi) [inline src/Ocelot/Security/IPSecurity/IPSecurityPolicy.cs:28]: Probably not your fault, but i would avoid the nesting...

File: src/Ocelot/Configuration/Creator/SecurityOptionsCreator.cs [hunk 4]
```diff
@@ -5,35 +5,33 @@ namespace Ocelot.Configuration.Creator
 {
     public class SecurityOptionsCreator : ISecurityOptionsCreator
     {
-        public SecurityOptions Create(FileSecurityOptions securityOptions)
+        public SecurityOptions Create(FileSecurityOptions securityOptions, FileGlobalConfiguration globalConfiguration)
```
Comment (ggnaegi) [inline src/Ocelot/Configuration/Creator/SecurityOptionsCreator.cs:8]:
```c#
public SecurityOptions Create(FileSecurityOptions securityOptions, FileGlobalConfiguration globalConfiguration) => Create(securityOptions.IsFullFilled() ? securityOptions : globalConfiguration.SecurityOptions);
```
might be simplified

**Review by ggnaegi — COMMENTED** [review]
Ok for me, but I would add some changes...

**Comment by raman-m** [comment]
> @raman-m @Fabman08 could you please rebase instead of merge?

Again please! Rebase or merge.
A new commit is available in develop!

**Comment by raman-m** [comment]
> Ok for me, but I would add some changes...

Gui, do you know that this feature and its internal classes can produce 1 million of string in memory? 😂

File: src/Ocelot/Security/IPSecurity/IPSecurityPolicy.cs (hunk 2 above)
Comment (Fabman08) [reply src/Ocelot/Security/IPSecurity/IPSecurityPolicy.cs:21]: Fixed!

File: src/Ocelot/Configuration/Creator/SecurityOptionsCreator.cs (hunk 4 above)
Comment (Fabman08) [reply src/Ocelot/Configuration/Creator/SecurityOptionsCreator.cs:8]: Fixed!

File: src/Ocelot/Configuration/SecurityOptions.cs [hunk 5]
```diff
@@ -4,31 +4,31 @@ public class SecurityOptions
...
+            IPBlockedList = new List<string>();
         }
 
         public SecurityOptions(string allowed = null, string blocked = null)
             : this()
         {
             if (!string.IsNullOrEmpty(allowed))
             {
-                IPAllowedList.Add(allowed);
+                IPAllowedList = IPAllowedList.Append(allowed).ToList();
```
[the remark this answers is not in the document]
Comment (ggnaegi) [reply src/Ocelot/Configuration/SecurityOptions.cs:16]: ??? Could you explain?

**Comment by raman-m** [comment]
Could we reduce the number of rebase operations that involve force pushes? A rebase is necessary when conflicts arise, but if are no conflicts, it would be better to simply merge from develop. The reason I bring this up is messages from the team during code reviews seem to be lost after rebasing.
Ultimately, I would prefer not to lose our code review results.

**Comment by raman-m** [comment]
@ggnaegi commented [on Oct 25](https://github.com/ThreeMammals/Ocelot/pull/2170#issuecomment-2437511334)
> @raman-m @Fabman08 could you please rebase instead of merge?

I disagree! Read my msg above! There were no conflicts. Let's rebase only in case of merge conflicts...

File: src/Ocelot/Configuration/SecurityOptions.cs (hunk 5 above)
[the remark this answers is not in the document]
Comment (raman-m) [reply src/Ocelot/Configuration/SecurityOptions.cs:16]: @ggnaegi The issue lies in the design of the [IPSecurityPolicy](https://github.com/ThreeMammals/Ocelot/pull/2170/files#diff-d964726ca860b79e9aaf467165b3ecc847a810d3a8c6f0c81a4200f334a32a11), which relies on processing string objects, often referred to as a flawed design (aka Chinese design). It is my firm belief that IP policy processing should be based on `IpAddress` objects instead of solely relying on strings.

> So what's the relation with the 1 million of strings in memory?

This is a problem of the design issue mentioned above, descendant problem. The [Creator class logic](https://github.com/ThreeMammals/Ocelot/pull/2170/files#diff-7ce752e07b4e6102e72adac03d23a9bbfaf87bf18320ae962e7258d78c9354a3R26-R27) parses the `IpAddress object and converts it into strings.
Let's consider the following test cases:
- the range `192.168.1.1-192.168255.255`: it produces 256<sup>2</sup>, a maximum of 65 536 strings in the list
- the range `10.1.1.1-10.255.255.255`: it generates 256<sup>3</sup>, a maximum of 16 777 216 string objects in the list, resulting in 16 million items❗ This highlights a significant problem.

However, this design issue is out of the current scope. Let the author to complete this config-feat.

[the remark this answers is not in the document]
Comment (raman-m) [reply src/Ocelot/Configuration/SecurityOptions.cs:16]: @Fabman08 Do you understand this code review issue?
Would you prefer to keep calling base constructor `this()` but remove producing new list `.ToList()`?
Or would you remove `this()` but wanna keep `.ToList()`? 😃

File: src/Ocelot/Security/IPSecurity/IPSecurityPolicy.cs (hunk 2 above)
Comment (raman-m) [reply src/Ocelot/Security/IPSecurity/IPSecurityPolicy.cs:21]: The funny fact is that YARP project developers sometimes implement operators: only [3 types](https://github.com/search?q=repo%3Amicrosoft%2Freverse-proxy%20operator&type=code) in whole project ! 🤣 
But they are Microsoft senior engineers with 150K+ salaries, right @ggnaegi ? 😄

File: src/Ocelot/Configuration/SecurityOptions.cs (hunk 5 above)
[the remark this answers is not in the document]
Comment (Fabman08) [reply src/Ocelot/Configuration/SecurityOptions.cs:16]: @raman-m Yes, I understand the issue reported, and I choose to keep calling `this()` and remove `.ToList()`.
Fixed in last commit

File: src/Ocelot/Security/IPSecurity/IPSecurityPolicy.cs (hunk 2 above)
Comment (Fabman08) [reply src/Ocelot/Security/IPSecurity/IPSecurityPolicy.cs:21]: Maybe in a next Feature PR ? 🤣

File: src/Ocelot/Configuration/Creator/SecurityOptionsCreator.cs [hunk 6]
```diff
@@ -5,35 +5,26 @@ namespace Ocelot.Configuration.Creator
...
             {
-                ipBlockedList = ipBlockedList.Except(ipAllowedList).ToList();
+                ipBlockedList = ipBlockedList.Except(ipAllowedList).ToArray();
             }
 
             return new SecurityOptions(ipAllowedList, ipBlockedList);
         }
-    }
+
+        private static string[] SetIpAddressList(IList<string> ipValueList)
```
Comment (raman-m) [inline src/Ocelot/Configuration/Creator/SecurityOptionsCreator.cs:24]: Method is private! You should you native types for performance reasons.
Why do you use abstract `IList<string>` type to pass the `List<string>` argument aka `FileSecurityOptions` lists?
```suggestion
        private static string[] SetIpAddressList(List<string> ipValueList)
```
It is correct change if the method will be public, but private methods should have native type arguments.

File: src/Ocelot/Configuration/Creator/SecurityOptionsCreator.cs [hunk 7]
```diff
@@ -5,35 +5,26 @@ namespace Ocelot.Configuration.Creator
...
+            => ipValueList
+                .Where(ipValue => IPAddressRange.TryParse(ipValue, out _))
+                .SelectMany(ipValue => IPAddressRange.Parse(ipValue).Select<IPAddress, string>(ip => ip.ToString()))
```
Comment (raman-m) [inline src/Ocelot/Configuration/Creator/SecurityOptionsCreator.cs:27]: Double parsing issue❗

File: src/Ocelot/Configuration/File/FileSecurityOptionsExtensions.cs [hunk 8]
```diff
@@ -0,0 +1,8 @@
+﻿namespace Ocelot.Configuration.File
+{
+    internal static class FileSecurityOptionsExtensions
```
Comment (raman-m) [inline src/Ocelot/Configuration/File/FileSecurityOptionsExtensions.cs:3]: Extensions are required when used types from external libs! But you are able to develop, common!
The method should be moved to extended type!

File: test/Ocelot.AcceptanceTests/Security/SecurityOptionsTests.cs [hunk 9]
```diff
@@ -0,0 +1,163 @@
+﻿using Microsoft.AspNetCore.Http;
+using Ocelot.Configuration.File;
+
+namespace Ocelot.AcceptanceTests.Security
```
Comment (raman-m) [inline test/Ocelot.AcceptanceTests/Security/SecurityOptionsTests.cs:4]: Should be file-scoped!

File: test/Ocelot.AcceptanceTests/Security/SecurityOptionsTests.cs [hunk 10]
```diff
@@ -0,0 +1,163 @@
...
+            _serviceHandler = new ServiceHandler();
+        }
+
+        public override void Dispose()
+        {
+            _serviceHandler.Dispose();
+            base.Dispose();
+        }
+
+        [Fact]
```
Comment (raman-m) [inline test/Ocelot.AcceptanceTests/Security/SecurityOptionsTests.cs:21]: No traits!

File: test/Ocelot.UnitTests/Configuration/SecurityOptionsCreatorTests.cs [hunk 11]
```diff
@@ -31,20 +52,57 @@ public void should_create_security_config()
...
-              .BDDfy();
+            this.Given(x => x.GivenThe(globalConfig))
+                .Given(x => x.GivenThe(new FileSecurityOptions()))
+                .When(x => x.WhenICreate())
+                .Then(x => x.ThenTheResultIs(expected))
+                .BDDfy();
+        }
+
+        [Fact]
+        public void should_create_global_route_security_config()
```
Comment (raman-m) [inline test/Ocelot.UnitTests/Configuration/SecurityOptionsCreatorTests.cs:63]: No traits!

File: test/Ocelot.UnitTests/Configuration/SecurityOptionsCreatorTests.cs [hunk 12]
```diff
@@ -31,20 +52,57 @@ public void should_create_security_config()
...
+                },
+            };
+
+            var expected = new SecurityOptions(routeIpAllowedList, routeIpBlockedList);
+
+            this.Given(x => x.GivenThe(globalConfig))
+                .Given(x => x.GivenThe(securityOptions))
+                .When(x => x.WhenICreate())
+                .Then(x => x.ThenTheResultIs(expected))
+                .BDDfy();
```
Comment (raman-m) [inline test/Ocelot.UnitTests/Configuration/SecurityOptionsCreatorTests.cs:90]: We don't use BDDfy in unit tests!

File: test/Ocelot.UnitTests/Security/IPSecurityPolicyTests.cs [hunk 13]
```diff
@@ -312,6 +314,17 @@ public void should_exludeAllowedFromBlocked_moreBlocked_clientIp_not_block()
...
 
+        [Fact]
+        public void should_route_config_overrides_global_config()
+        {
+            _httpContext.Connection.RemoteIpAddress = Dns.GetHostAddresses("192.168.1.10")[0];
+            this.Given(x => x.GivenRouteConfigAndGlobalConfig(false))
+                .Given(x => x.GivenSetDownstreamRoute())
+                .When(x => x.WhenTheSecurityPolicy())
+                .Then(x => x.ThenSecurityPassing())
+                .BDDfy();
```
Comment (raman-m) [inline test/Ocelot.UnitTests/Security/IPSecurityPolicyTests.cs:325]: No traits! BDDfy must be removed!

**Review by raman-m — CHANGES_REQUESTED** [review]
My final suggestions below 👇

File: src/Ocelot/Configuration/Creator/SecurityOptionsCreator.cs (hunk 7 above)
Comment (raman-m) [reply src/Ocelot/Configuration/Creator/SecurityOptionsCreator.cs:27]: Solution:
```csharp
        private static string[] SetIpAddressList(List<string> ipValues) => ipValues.SelectMany(Parse).ToArray();
        private static string[] Parse(string ipValue)
        {
            if (IPAddressRange.TryParse(ipValue, out var range))
            {
                return range.Select<IPAddress, string>(ip => ip.ToString()).ToArray();
            }

            return Array.Empty<string>();
        }
```

Comment (raman-m) [reply src/Ocelot/Configuration/Creator/SecurityOptionsCreator.cs:27]: Please address all the issues in code review within 1 hour please!
I would like to merge it today and do not wish to waste any more time.

Comment (Fabman08) [reply src/Ocelot/Configuration/Creator/SecurityOptionsCreator.cs]: fixed

File: test/Ocelot.UnitTests/Configuration/SecurityOptionsCreatorTests.cs (hunk 11 above)
Comment (Fabman08) [reply test/Ocelot.UnitTests/Configuration/SecurityOptionsCreatorTests.cs]: I fixed putting fist char uppecare likes the others tests

File: test/Ocelot.UnitTests/Configuration/SecurityOptionsCreatorTests.cs (hunk 12 above)
Comment (Fabman08) [reply test/Ocelot.UnitTests/Configuration/SecurityOptionsCreatorTests.cs]: Removed in all tests

File: src/Ocelot/Configuration/File/FileSecurityOptionsExtensions.cs (hunk 8 above)
Comment (raman-m) [reply src/Ocelot/Configuration/File/FileSecurityOptionsExtensions.cs]: Yes, that is right!

**Comment by raman-m** [comment]
@Fabman08 Please stop any development! Don't push anything!.. I'm making final review...

**Review by raman-m — APPROVED** [review]
### Ready for Delivery ✅

File: src/Ocelot/Security/IPSecurity/IPSecurityPolicy.cs (hunk 2 above)
Comment (raman-m) [reply src/Ocelot/Security/IPSecurity/IPSecurityPolicy.cs]: Yes, next time... 😋

File: src/Ocelot/Configuration/SecurityOptions.cs (hunk 5 above)
[the remark this answers is not in the document]
Comment (raman-m) [reply src/Ocelot/Configuration/SecurityOptions.cs]: I will add [my concerns](https://github.com/ThreeMammals/Ocelot/pull/2170#discussion_r1848536987) as a new task for the next refactoring round.

**Comment by Fabman08** [comment]
> @Fabman08  Thank you, Fabrizio, for this contribution! 👍 
> We completed the feature in 40 days. Not bad! 😄 

@raman-m thank you too!! It's a pleasure for me collaborate for this project! I'm sorry for the misunderstanding, I hope to be more accurate the next collaboration
