### PR TITLE
#585 #2316 Authentication global configuration

### LINKED ISSUE #2316: #585 Dynamic routes are unable to utilize `AuthenticationOptions` for global authentication
```json
{
  "Routes": [],
  "Aggregates": [],
  "GlobalConfiguration": {
    "RequestIdKey": null,
    "ServiceDiscoveryProvider": {
      "Host": "localhost",
      "Port": 8500,
      "Type": "Consul",
      "Token": null,
      "ConfigurationKey": null
    },
    "RateLimitOptions": {
      "ClientIdHeader": "ClientId",
      "QuotaExceededMessage": null,
      "RateLimitCounterPrefix": "ocelot",
      "DisableRateLimitHeaders": false,
      "HttpStatusCode": 429
    },
    "QoSOptions": {
      "ExceptionsAllowedBeforeBreaking": 0,
      "DurationOfBreak": 0,
      "TimeoutValue": 0
    },
    "BaseUrl": null,
    "LoadBalancerOptions": {
      "Type": "LeastConnection",
      "Key": null,
      "Expiry": 0
    },
    "DownstreamScheme": "http",
    "HttpHandlerOptions": {
      "AllowAutoRedirect": false,
      "UseCookieContainer": false,
      "UseTracing": false
    },
    "AuthenticationOptions": {
      "AuthenticationProviderKey": "MyKey", //指定一个key
      "AllowedScopes": [ "apiScopes" ] //id4的作用域名称
    }
  }
}
```

### PR DESCRIPTION
**Pull request by raman-m**
## Closes #2316 
- #585 
- #2316 

## Proposed Changes
- Refactored the [AuthenticationMiddleware](https://github.com/ThreeMammals/Ocelot/pull/2336/files#diff-bdd777af872cf3a7c8e2c1c19ec743ca0ccaf4b3e0fac8af3c6c3c11de4c355e): **first**, removed the checker from the `AuthenticateAsync` method that ensured all keys were empty, which felt awkward due to filtering out empty keys—and honestly, we already have an [auth validator](https://github.com/ThreeMammals/Ocelot/pull/2336/files#diff-c5585b0a7a61bae9bafe8b5e0c0092c291db740b026d717aaef4d510d796b2c6). **Second**, while [the validator](https://github.com/ThreeMammals/Ocelot/pull/2336/files#diff-c5585b0a7a61bae9bafe8b5e0c0092c291db740b026d717aaef4d510d796b2c6) doesn’t check for empty keys, I believe the IsSupportedAuthenticationProviders method handles this by validating against supported schemes. As a follow-up action, we could implement empty key checking in the validator to prevent Ocelot from starting.
- Cleaned up unnecessary code in the [AuthenticationOptionsBuilder](https://github.com/ThreeMammals/Ocelot/pull/2336/files#diff-ee2e5a8fa1dba4dbdc5207deac9f852d673cb2d4edd5b10089c7685b8b63c06d), [RouteOptionsBuilder](https://github.com/ThreeMammals/Ocelot/pull/2336/files#diff-a5cb5abde21d2eba9bb6d0e9892c21e77ad9b094aff4deca834a76e787c54de3), [RouteOptionsCreator](https://github.com/ThreeMammals/Ocelot/pull/2336/files#diff-adcfe2780254a381f737312363ab46e8c4087948223d85b0c6cb897786c60be0), and [RouteOptions](https://github.com/ThreeMammals/Ocelot/pull/2336/files#diff-1ac83e1f66716f4c8ed4f735bdd4c61f5a86642351403ad8f63c43bfff5d88c8) classes. As a result, the [IRouteOptionsCreator](https://github.com/ThreeMammals/Ocelot/pull/2336/files#diff-565208f090a684ffed5dba8c2b16c8c4d276d49d4abe7d753de307b4d35b7f37) service was removed from the DI container. The [RouteOptionsCreator](https://github.com/ThreeMammals/Ocelot/pull/2336/files#diff-adcfe2780254a381f737312363ab46e8c4087948223d85b0c6cb897786c60be0) service used to analyze configuration in File models and create a [RouteOptions](https://github.com/ThreeMammals/Ocelot/pull/2336/files#diff-1ac83e1f66716f4c8ed4f735bdd4c61f5a86642351403ad8f63c43bfff5d88c8) model to pass certain flags to the [DownstreamRoute](https://github.com/ThreeMammals/Ocelot/pull/2336/files#diff-91f77268e2513800fea3711da0f151cc5563af89391413161726e1eb6e29fe83) business model, where relevant boolean properties were set. Interestingly, those flags can already be accessed from existing options models, so a few small helper properties were added directly to the [DownstreamRoute](https://github.com/ThreeMammals/Ocelot/pull/2336/files#diff-91f77268e2513800fea3711da0f151cc5563af89391413161726e1eb6e29fe83) model.
- ⚠️ Feature update❗The [AuthenticationOptions](https://github.com/ThreeMammals/Ocelot/pull/2336/files#diff-02026ba2fd3808c949e5d49eae3c36900983f8b86b7d99427c7ae02864e20f7a) business model has been redesigned as the final step in merging the entire configuration. This model has no uninitialized aggregations, preventing runtime `ArgumentNullException` objects to be thrown.
- ⚠️ Feature update❗The [AuthenticationOptionsCreator](https://github.com/ThreeMammals/Ocelot/pull/2336/files#diff-0d7ec8f153d011202ad1c2407c0d94aa1cc98da986fc3210b29f78584a325ab4) service class is at the heart of the feature. It combines all configurations and produces the final `AuthenticationOptions` business model for the middleware and custom services. The merging process takes route groups into account for global application.
- ⚠️ Feature update❗Reviewed the [file models](https://github.com/ThreeMammals/Ocelot/pull/2336/files#diff-ef3eefad2a0aa18ce6439cae66195f589ac0ed2be9d02ed9316184e555a80e5f) to support global auth configuration for dynamic routes, and we’ll be [deprecating the AuthenticationProviderKey option](https://github.com/ThreeMammals/Ocelot/pull/2336/files#diff-ef3eefad2a0aa18ce6439cae66195f589ac0ed2be9d02ed9316184e555a80e5fR29-R30) in version 25.0.
- ⚠️ Feature update❗[Creator classes](https://github.com/ThreeMammals/Ocelot/pull/2336/files#diff-0d7ec8f153d011202ad1c2407c0d94aa1cc98da986fc3210b29f78584a325ab4) now support auth options for dynamic routing, including [ConfigurationCreator](https://github.com/ThreeMammals/Ocelot/pull/2336/files#diff-76bcce684b21dc8accf2cdb7b4d9ee8b98b6fbb865337f329a14909f6185995e) and [DynamicRoutesCreator](https://github.com/ThreeMammals/Ocelot/pull/2336/files#diff-10d2d90244db27112a15630e613b4989d154a201b93de60d4bf98b62d73920b0). Plus, trash code has been cleaned up from [StaticRoutesCreator](https://github.com/ThreeMammals/Ocelot/pull/2336/files#diff-207e4e66c3797dfb40a7dfc9e4f8437737ee2219bfa26a8cad966d107ecdb850).
- ⚠️ Feature update❗The `AuthenticationOptions` model is mainly used by [DiscoveryDownstreamRouteFinder](https://github.com/ThreeMammals/Ocelot/pull/2336/files#diff-9cf090f3385573ce16d00fecb3d1f6fe512da25f13022282b85565e02cae8e66), which sets up the `AuthenticationOptions` property of [DownstreamRoute](https://github.com/ThreeMammals/Ocelot/pull/2336/files#diff-91f77268e2513800fea3711da0f151cc5563af89391413161726e1eb6e29fe83) so it can be read by middleware that works independently of the routing mode, whether static or dynamic.
- Reviewed the [FileAuthenticationOptionsValidator](https://github.com/ThreeMammals/Ocelot/pull/2336/files#diff-c5585b0a7a61bae9bafe8b5e0c0092c291db740b026d717aaef4d510d796b2c6) class, but it could be further developed in the future since our `AuthenticationOptions` include more features now.
- Removed the [IRouteOptionsCreator](https://github.com/ThreeMammals/Ocelot/pull/2336/files#diff-8f16fc8879d2a7b30200bf1a3aafbb7baf957f49c53db5db704a3c3fbd985c71) service from DI after moving its functionality to [DownstreamRoute](https://github.com/ThreeMammals/Ocelot/pull/2336/files#diff-91f77268e2513800fea3711da0f151cc5563af89391413161726e1eb6e29fe83), opting instead for custom business micro-helpers. As a result, a lot of trash code was cleaned up from the codebase, with the final step prepared in a few recent pull requests merged during this milestone.
- Unit tests: Main classes are [AuthenticationOptionsCreatorTests](https://github.com/ThreeMammals/Ocelot/pull/2336/files#diff-2715b78f0469d68152db4c62e5f6c977397ffab8b80dd8d14c9a49fa94c95199R177), [FileGlobalAuthenticationOptionsTests](https://github.com/ThreeMammals/Ocelot/pull/2336/files#diff-2d5b5b7729e1c6569ae5bda6cc6b8a562c6d20bb7911ff61c422cebc1f9e1253). Reviewed [AuthenticationMiddlewareTests](https://github.com/ThreeMammals/Ocelot/pull/2336/files#diff-456ee3e33833ba9a0c7c1f77415593a4a621b5465b3f42a436d6cd6ede23f647) and [AuthorizationMiddlewareTests](https://github.com/ThreeMammals/Ocelot/pull/2336/files#diff-9109f3b8bb0a66c9348b131c66f753d1a722051bb7e961777909877056c22b85). Also, many tests have been added in the [Infrastructure/Extensions](https://github.com/ThreeMammals/Ocelot/pull/2336/files#diff-2a09f3a92cd914ba6a448490a8618aa988ecaeddbcd25fd03e9ebe1984827083) area, improving coverage.
- Acceptance tests. Main classes are [AuthenticationTests](https://github.com/ThreeMammals/Ocelot/pull/2336/files#diff-18ce20ee54a3cfcab0449eea791662f960711ceb34739d5f1ef26ecf87dcac87R141-R145) and [DynamicRoutingTests](https://github.com/ThreeMammals/Ocelot/pull/2336/files#diff-2defc760a62ed9bd22d98d63da25fee35ff933ee227f04477781204e7496a783) for sure. With the acceptance testing and refactoring done, we can now test authentication and authorization features using a custom JWT signing server which is now micro service as part of acceptance steps. Check out the new steps in the [AuthenticationSteps](https://github.com/ThreeMammals/Ocelot/pull/2336/files#diff-dd6b017d0712967918c35f8d56f71f466fe22df57436c3d601c2d16026636f9e) class. Since we deprecated IdentityServer4 in Administration feat and removed references to the lib, we now have the freedom to further evolve our testing approach.
- Documentation: The docs were updated in commit https://github.com/ThreeMammals/Ocelot/pull/2336/commits/a4de853564537d3dbef837b21081d2f7ea80c441 &rarr; [html docs in develop](https://ocelot.readthedocs.io/en/develop/) &rarr; [Authentication](https://ocelot.readthedocs.io/en/develop/features/authentication.html)

### CODE REVIEW

File: src/Ocelot/Authentication/AuthenticationMiddleware.cs [hunk 1]
```diff
@@ -20,28 +20,25 @@ public async Task Invoke(HttpContext httpContext)
     {
         var request = httpContext.Request;
         var path = httpContext.Request.Path;
-        var downstreamRoute = httpContext.Items.DownstreamRoute();
+        var route = httpContext.Items.DownstreamRoute();
 
-        // reducing nesting, returning early when no authentication is needed.
-        if (request.Method.Equals("OPTIONS", StringComparison.OrdinalIgnoreCase) || !downstreamRoute.IsAuthenticated)
+        if (request.Method.Equals("OPTIONS", StringComparison.OrdinalIgnoreCase) || !route.IsAuthenticated)
```
Comment (ggnaegi) [inline src/Ocelot/Authentication/AuthenticationMiddleware.cs]: instead of using "OPTIONS", why not use `HttpMethod.Options.Method` ?

File: src/Ocelot/Authorization/Middleware/AuthorizationMiddleware.cs [hunk 2]
```diff
@@ -25,13 +24,13 @@ public AuthorizationMiddleware(RequestDelegate next,
 
     public async Task Invoke(HttpContext httpContext)
     {
-        var downstreamRoute = httpContext.Items.DownstreamRoute();
+        var route = httpContext.Items.DownstreamRoute();
 
-        if (!IsOptionsHttpMethod(httpContext) && IsAuthenticatedRoute(downstreamRoute))
+        if (!IsOptionsHttpMethod(httpContext) && route.IsAuthenticated)
```
Comment (ggnaegi) [inline src/Ocelot/Authorization/Middleware/AuthorizationMiddleware.cs]: why IsOptionsHttpMethod? Could we centralize that kind of logic?

File: src/Ocelot/Configuration/AuthenticationOptions.cs [hunk 3]
```diff
@@ -1,49 +1,52 @@
...
-    /// Multiple authentication schemes registered in DI services with appropriate authentication providers.
-    /// </summary>
-    /// <remarks>
-    /// The order in the collection matters: first successful authentication result wins.
-    /// </remarks>
-    /// <value>
-    /// An array of <see langword="string"/> values of the scheme names.
-    /// </value>
-    public string[] AuthenticationProviderKeys { get; }
+    public static string[] Merge(string primaryKey, string[] keys)
```
Comment (ggnaegi) [inline src/Ocelot/Configuration/AuthenticationOptions.cs]: private, protected?

File: src/Ocelot/Configuration/Creator/AuthenticationOptionsCreator.cs [hunk 4]
```diff
@@ -1,56 +1,63 @@
...
+        if (options == null && globalOptions != null && isGlobal)
+        {
+            return new(globalOptions);
+        }
 
-        MergeScopes(opts, global);
-        MergeSchemes(opts, global);
-        return new(opts);
-    }
+        if (options != null && globalOptions == null)
```
Comment (ggnaegi) [inline src/Ocelot/Configuration/Creator/AuthenticationOptionsCreator.cs:38]: the logic can be simplified, options != null && globalOptions == null, if not verified, it implies that, if options != null, globalOptions != null
```c#
if (options == null && globalOptions != null && isGlobal)
        {
            return new(globalOptions);
        }

        if (options != null && globalOptions == null || options != null && !isGlobal)
        {
            return new(options);
        }

        return options != null ? Merge(options, globalOptions) : new();
```

File: src/Ocelot/Configuration/File/FileGlobalAuthenticationOptions.cs [hunk 5]
```diff
@@ -0,0 +1,13 @@
+﻿namespace Ocelot.Configuration.File;
+
+public class FileGlobalAuthenticationOptions : FileAuthenticationOptions, IRouteGroup
+{
+    public FileGlobalAuthenticationOptions() : base() { }
+    public FileGlobalAuthenticationOptions(string authScheme) : base(authScheme) { }
```
Comment (ggnaegi) [inline src/Ocelot/Configuration/File/FileGlobalAuthenticationOptions.cs:6]: never used, why auth scheme as string?

File: src/Ocelot/Configuration/File/FileRoute.cs [hunk 6]
```diff
@@ -18,7 +18,7 @@ public FileRoute()
         AddClaimsToRequest = new Dictionary<string, string>();
         AddHeadersToRequest = new Dictionary<string, string>();
         AddQueriesToRequest = new Dictionary<string, string>();
-        AuthenticationOptions = new FileAuthenticationOptions();
+        AuthenticationOptions = default;
```
Comment (ggnaegi) [inline src/Ocelot/Configuration/File/FileRoute.cs]: i prefer null instead of default, default is a bit supercalifragilistic.

File: src/Ocelot/Authentication/AuthenticationMiddleware.cs (hunk 1 above)
Comment (raman-m) [reply src/Ocelot/Authentication/AuthenticationMiddleware.cs]: OK This constant will be removed

File: src/Ocelot/Authorization/Middleware/AuthorizationMiddleware.cs (hunk 2 above)
Comment (raman-m) [reply src/Ocelot/Authorization/Middleware/AuthorizationMiddleware.cs]: OK, I’ll introduce an extension for `HttpRequest` that will be placed in the Infrastructure.

File: src/Ocelot/Configuration/AuthenticationOptions.cs (hunk 3 above)
Comment (raman-m) [reply src/Ocelot/Configuration/AuthenticationOptions.cs]: Protected for the sealed class? Awesome!
But what a debate about privacy!

File: src/Ocelot/Configuration/Creator/AuthenticationOptionsCreator.cs (hunk 4 above)
Comment (raman-m) [reply src/Ocelot/Configuration/Creator/AuthenticationOptionsCreator.cs:38]: What does concern mean? Have less return statements?
And I'm not sure if the last line is correct when returning.

File: src/Ocelot/Configuration/File/FileGlobalAuthenticationOptions.cs (hunk 5 above)
Comment (raman-m) [reply src/Ocelot/Configuration/File/FileGlobalAuthenticationOptions.cs:6]: After adding tests, the number of references to constructors will increase. Another reason is that base model constructors should be reflected in descendant classes, correct?

Not an issue!

Comment (raman-m) [reply src/Ocelot/Configuration/File/FileGlobalAuthenticationOptions.cs:6]: Here are the references for the global model cache options that were merged recently 👇
image
For the global model for auth opts the picture will be the same: more refs.

File: src/Ocelot/Configuration/File/FileRoute.cs (hunk 6 above)
Comment (raman-m) [reply src/Ocelot/Configuration/File/FileRoute.cs]: Thinking of opening a ticket on Microsoft boards? 🤣 How about writing to the .NET team with a concern about the `default` keyword in C# 😄
To keep it constructive, I'd suggest removing that line entirely since, for reference types, the default value is `null`. Agreed?

File: src/Ocelot/Configuration/File/FileGlobalAuthenticationOptions.cs (hunk 5 above)
Comment (raman-m) [reply src/Ocelot/Configuration/File/FileGlobalAuthenticationOptions.cs:6]: Ah, I forgot about developers creating the `FileConfiguration` model on the fly to inject configuration in app startup  C# (aka `Program.cs`) and update it before adding it to the ASP.NET configuration provider.
The [Build From Scratch](https://ocelot.readthedocs.io/en/latest/features/configuration.html#build-from-scratch) feature is handy, and having more constructors for `File`-models adds flexibility when building, right? 👉  Moreover, I'd say having more constructors allows for more flexible and practical building, right?

File: src/Ocelot/Configuration/File/FileRoute.cs (hunk 6 above)
Comment (raman-m) [reply src/Ocelot/Configuration/File/FileRoute.cs]: Do you want to have a debate about the `default` keyword in C# and the reasons it was introduced?

File: src/Ocelot/Authentication/AuthenticationMiddleware.cs (hunk 1 above)
Comment (raman-m) [reply src/Ocelot/Authentication/AuthenticationMiddleware.cs]: Fixed in https://github.com/ThreeMammals/Ocelot/pull/2336/commits/1fb06ecd0f6f8494743ff510494b3238c4521882 ✔️

File: src/Ocelot/Authorization/Middleware/AuthorizationMiddleware.cs (hunk 2 above)
Comment (raman-m) [reply src/Ocelot/Authorization/Middleware/AuthorizationMiddleware.cs]: Fixed in https://github.com/ThreeMammals/Ocelot/pull/2336/commits/1fb06ecd0f6f8494743ff510494b3238c4521882 ✔️

File: src/Ocelot/Configuration/AuthenticationOptions.cs (hunk 3 above)
Comment (raman-m) [reply src/Ocelot/Configuration/AuthenticationOptions.cs]: Fixed in https://github.com/ThreeMammals/Ocelot/pull/2336/commits/1fb06ecd0f6f8494743ff510494b3238c4521882 ✔️

File: src/Ocelot/Configuration/File/FileRoute.cs (hunk 6 above)
Comment (raman-m) [reply src/Ocelot/Configuration/File/FileRoute.cs]: Fixed in https://github.com/ThreeMammals/Ocelot/pull/2336/commits/1fb06ecd0f6f8494743ff510494b3238c4521882 ✔️

File: src/Ocelot/Configuration/Creator/AuthenticationOptionsCreator.cs (hunk 4 above)
Comment (raman-m) [reply src/Ocelot/Configuration/Creator/AuthenticationOptionsCreator.cs:38]: I suggest [another version](https://github.com/ThreeMammals/Ocelot/pull/2336/files#diff-0d7ec8f153d011202ad1c2407c0d94aa1cc98da986fc3210b29f78584a325ab4R25-R41) with the same idea, but with fewer if-blocks and the simplest algorithm to merge options with(out) the global group 👇 
```csharp
    protected virtual AuthenticationOptions Create(IRouteGrouping grouping,
        FileAuthenticationOptions options, FileGlobalAuthenticationOptions globalOptions)
    {
        ArgumentNullException.ThrowIfNull(grouping);
        bool isGlobal = globalOptions?.RouteKeys is null // undefined section or array option -> is global
            || globalOptions.RouteKeys.Count == 0 // empty collection -> is global
            || globalOptions.RouteKeys.Contains(grouping.Key); // this route is in the group

        if (options == null && globalOptions != null && isGlobal)
            return new(globalOptions);

        if (options != null && globalOptions == null)
            return new(options);

        if (options != null && globalOptions != null)
            return isGlobal ? Merge(options, globalOptions) : new(options);

        return new();
    }
```
So, it is fixed in commit https://github.com/ThreeMammals/Ocelot/pull/2336/commits/64a9bbf78e473cadbc206975d5bdec7648793fa8 ✔️ 

If you are okay with this version, please approve, since all code review issues have been resolved.

File: src/Ocelot/Authorization/AuthorizationMiddleware.cs [hunk 7]
```diff
@@ -0,0 +1,94 @@
...
+            {
+                Logger.LogWarning("error authorizing user scopes");
+
+                context.Items.UpsertErrors(authorized.Errors);
+                return;
+            }
+
+            if (IsAuthorized(authorized))
+            {
+                Logger.LogInformation("user scopes is authorized calling next authorization checks");
```
Comment (RaynaldM) [inline src/Ocelot/Authorization/AuthorizationMiddleware.cs]: same : just noise

File: src/Ocelot/Authorization/AuthorizationMiddleware.cs [hunk 8]
```diff
@@ -0,0 +1,94 @@
...
+                Logger.LogWarning("user scopes is not authorized setting pipeline error");
+
+                context.Items.SetError(new UnauthorizedError(
+                        $"{context.User.Identity.Name} unable to access {route.UpstreamPathTemplate.OriginalValue}"));
+            }
+        }
+
+        if (!context.IsOptionsMethod() && route.IsAuthorized)
+        {
+            Logger.LogInformation("route is authorized");
```
Comment (RaynaldM) [inline src/Ocelot/Authorization/AuthorizationMiddleware.cs]: We are in middleware, so every CPU cycle must be spent usefully !
Who is going to read (and for what purpose) this log line repeated 1,000 times per second?

File: src/Ocelot/Authorization/AuthorizationMiddleware.cs [hunk 9]
```diff
@@ -0,0 +1,94 @@
...
+
+                context.Items.SetError(new UnauthorizedError($"{context.User.Identity.Name} is not authorized to access {route.UpstreamPathTemplate.OriginalValue}"));
+            }
+        }
+        else
+        {
+            Logger.LogInformation(() => $"No authorization needed for upstream path: { route.UpstreamPathTemplate.OriginalValue}");
+            await _next.Invoke(context);
+        }
+    }
```
Comment (RaynaldM) [inline src/Ocelot/Authorization/AuthorizationMiddleware.cs:86]: All these logs remind me of my early days in the 80s, when we used to put “print...” everywhere to debug our apps.

Ocelot is a tool used in production applications that sometimes process tens of thousands of requests per second. These logs are just CPU consumers and noise generators.

If you want to debug based on logs, use the “#if DEBUG” directive.

File: src/Ocelot/Configuration/File/FileAuthenticationOptions.cs [hunk 10]
```diff
@@ -1,20 +1,20 @@
...
-        AllowedScopes = new();
-        AuthenticationProviderKey = null;
-        AuthenticationProviderKeys = Array.Empty<string>();
-    }
+    { }
+
+    public FileAuthenticationOptions(string authScheme) : this()
+        => AuthenticationProviderKeys = [authScheme];
 
     public FileAuthenticationOptions(FileAuthenticationOptions from)
```
Comment (RaynaldM) [inline src/Ocelot/Configuration/File/FileAuthenticationOptions.cs]:
```suggestion
    public FileAuthenticationOptions(FileAuthenticationOptions fromOptions)
```

File: src/Ocelot/DownstreamUrlCreator/DownstreamPathPlaceholderReplacer.cs [hunk 11]
```diff
@@ -1,23 +1,22 @@
...
+/// <summary>
+/// TODO Move this service to the middleware as a protected virtual method. Having a separate interface is absolutely useless.
+/// </summary>
 public class DownstreamPathPlaceholderReplacer : IDownstreamPathPlaceholderReplacer
 {
-    public Response<DownstreamPath> Replace(string downstreamPathTemplate,
-        List<PlaceholderNameAndValue> urlPathPlaceholderNameAndValues)
+    public DownstreamPath Replace(string downstreamPathTemplate, List<PlaceholderNameAndValue> urlPathPlaceholderNameAndValues)
     {
         var downstreamPath = new StringBuilder();
```
Comment (RaynaldM) [inline src/Ocelot/DownstreamUrlCreator/DownstreamPathPlaceholderReplacer.cs]:
```suggestion
        var downstreamPath = new StringBuilder(downstreamPathTemplate);
```

File: src/Ocelot/DownstreamUrlCreator/DownstreamPathPlaceholderReplacer.cs [hunk 12]
```diff
@@ -1,23 +1,22 @@
...
-
         downstreamPath.Append(downstreamPathTemplate);
```
Comment (RaynaldM) [inline src/Ocelot/DownstreamUrlCreator/DownstreamPathPlaceholderReplacer.cs]:
```suggestion
```

File: src/Ocelot/DownstreamUrlCreator/DownstreamUrlCreatorMiddleware.cs [hunk 13]
```diff
@@ -1,173 +1,169 @@
...
+    {
+        var downstreamRoute = context.Items.DownstreamRoute();
+        var placeholders = context.Items.TemplatePlaceholderNameAndValues();
+        var downstreamPath = _replacer.Replace(downstreamRoute.DownstreamPathTemplate.Value, placeholders);
+        var downstreamRequest = context.Items.DownstreamRequest();
+        var upstreamPath = downstreamRequest.AbsolutePath;
+        if (downstreamPath.Value.IsEmpty())
+        {
+            throw new NotSupportedException($"{_replacer.GetType().Name} returned an empty {nameof(DownstreamPath)} for the route {downstreamRoute.Name()}.");
+        }
```
Comment (RaynaldM) [inline src/Ocelot/DownstreamUrlCreator/DownstreamUrlCreatorMiddleware.cs:44]:
```suggestion
        var downstreamRoute = context.Items.DownstreamRoute();
        var placeholders = context.Items.TemplatePlaceholderNameAndValues();
        var downstreamPath = _replacer.Replace(downstreamRoute.DownstreamPathTemplate.Value, placeholders);
        if (downstreamPath.Value.IsEmpty())
        {
            throw new NotSupportedException($"{_replacer.GetType().Name} returned an empty {nameof(DownstreamPath)} for the route {downstreamRoute.Name()}.");
        }
        
        var downstreamRequest = context.Items.DownstreamRequest();
        var upstreamPath = downstreamRequest.AbsolutePath;
```

File: src/Ocelot/DownstreamUrlCreator/DownstreamUrlCreatorMiddleware.cs [hunk 14]
```diff
@@ -1,173 +1,169 @@
...
+        foreach (var queryKey in queries.AllKeys.Where(placeholderNames.Contains))
+        {
+            queries.Remove(queryKey);
+        }
+
+        var parameters = newQueries.AllKeys
+            .Where(key => !string.IsNullOrEmpty(key))
+            .ToDictionary(key => key, key => newQueries[key]);
+
+        _ = queries.AllKeys
```
Comment (RaynaldM) [inline src/Ocelot/DownstreamUrlCreator/DownstreamUrlCreatorMiddleware.cs:115]: could you explain with a comment what is the goal of it

File: src/Ocelot/DownstreamUrlCreator/DownstreamUrlCreatorMiddleware.cs [hunk 15]
```diff
@@ -1,173 +1,169 @@
...
+                .Append(downstreamRequest.Query)
+                .Replace(parameter, string.Empty)
+                .Remove(--questionMarkOrAmpersand, 1);
+            downstreamRequest.Query = builder.Length > 0
+                ? builder.Remove(0, 1).Insert(0, QuestionMark).ToString()
+                : string.Empty;
+        }
+    }
+
+    private static string GetPath(string downstreamPath)
```
Comment (RaynaldM) [inline src/Ocelot/DownstreamUrlCreator/DownstreamUrlCreatorMiddleware.cs]: not sure, but maybe
```suggestion
    private static ReadOnlySpan<char> GetPath(ReadOnlySpan<char> downstreamPath)
```

File: src/Ocelot/DownstreamUrlCreator/DownstreamUrlCreatorMiddleware.cs [hunk 16]
```diff
@@ -1,173 +1,169 @@
...
+    {
+        int length = downstreamPath.IndexOf(QuestionMark, StringComparison.Ordinal);
+        return downstreamPath[..length];
+    }
+
+    private static string GetQueryString(string downstreamPath)
```
Comment (RaynaldM) [inline src/Ocelot/DownstreamUrlCreator/DownstreamUrlCreatorMiddleware.cs]: same

**Review by RaynaldM — APPROVED** [review]

File: src/Ocelot/Authorization/AuthorizationMiddleware.cs (hunk 9 above)
Comment (raman-m) [reply src/Ocelot/Authorization/AuthorizationMiddleware.cs:86]: > If you want to debug

I don’t want anything by this code. **This isn't my code**, so I just moved the file. Can you run a Git blame on it to see the authors?

File: src/Ocelot/DownstreamUrlCreator/DownstreamUrlCreatorMiddleware.cs (hunk 14 above)
Comment (raman-m) [reply src/Ocelot/DownstreamUrlCreator/DownstreamUrlCreatorMiddleware.cs:115]: I need not anything to explain you
Start contributing to the project, Ray

File: src/Ocelot/DownstreamUrlCreator/DownstreamUrlCreatorMiddleware.cs (hunk 13 above)
Comment (raman-m) [reply src/Ocelot/DownstreamUrlCreator/DownstreamUrlCreatorMiddleware.cs:44]: Sorry, what is the change?

File: src/Ocelot/DownstreamUrlCreator/DownstreamUrlCreatorMiddleware.cs (hunk 14 above)
Comment (raman-m) [reply src/Ocelot/DownstreamUrlCreator/DownstreamUrlCreatorMiddleware.cs:115]: Your curiosity will be satisfied if you use git blame on the method. This is about [merging query parameters](https://ocelot.readthedocs.io/en/latest/features/routing.html#merging-of-query-parameters) in the "[Query Placeholders](https://ocelot.readthedocs.io/en/latest/features/routing.html#query-placeholders)" feature.

File: src/Ocelot/DownstreamUrlCreator/DownstreamUrlCreatorMiddleware.cs (hunk 16 above)
Comment (raman-m) [reply src/Ocelot/DownstreamUrlCreator/DownstreamUrlCreatorMiddleware.cs]: You thoroughly reviewed the middleware, but the file was simply moved!
image
You can see the actual changes of my minor styling refactoring by checking the file’s history in VS.
image
and here are the changes 👇 
image
1. Invoke argument renaming 😄 
2. and [changed returning type](https://github.com/ThreeMammals/Ocelot/pull/2336/files#diff-b4ed158e4393b6ace878bd989c8238b2a52a8fec87ef496f9f6ab64104147b22) of `_replacer.Replace` method
3. My actual change is converting `response.IsError` to a simple empty string check as a consequence of changing the return type of the `IDownstreamPathPlaceholderReplacer.Replace` method, see point 2.

Comment (raman-m) [reply src/Ocelot/DownstreamUrlCreator/DownstreamUrlCreatorMiddleware.cs]: @RaynaldM FYI, you are a teammate and can push commits to any PRs or branches❗ Feel free to make improvements as needed.
I will focus on the acceptance tests since @ggnaegi [is waiting](https://github.com/ThreeMammals/Ocelot/pull/2336#pullrequestreview-3471728607) for them.

File: src/Ocelot/DownstreamUrlCreator/DownstreamUrlCreatorMiddleware.cs (hunk 15 above)
Comment (raman-m) [reply src/Ocelot/DownstreamUrlCreator/DownstreamUrlCreatorMiddleware.cs]: It could improve performance by reducing RAM usage, I guess, to process the string data in stack instead of object in heap, right? Not entirely sure, though.

File: src/Ocelot/Authorization/AuthorizationMiddleware.cs (hunk 9 above)
Comment (raman-m) [reply src/Ocelot/Authorization/AuthorizationMiddleware.cs:86]: This middleware was just moved as a file
image
The real changes 👇 
image
image
image
1. Apply argument renaming  
2. Incorporate Gui’s IsOptions styling suggestion  
3. Remove unnecessary code at the end of the class  

**Conclusion**: So, this `LogDebug`, `LogInformation`, `LogWarning` methods were not added by me.

File: src/Ocelot/Authorization/AuthorizationMiddleware.cs (hunk 8 above)
Comment (raman-m) [reply src/Ocelot/Authorization/AuthorizationMiddleware.cs]: The real issue with this line is using a string argument instead of `Func<string>`. In late 2023, we optimized the Logger to use the `IsEnabled` property for the current logging level, minimizing CPU and RAM usage when the level is disabled. Actual logging occurs only if the `Information` level is enabled, but the argument type still needs to be converted. @ggnaegi, right?
The issue is due to an incorrect argument type. Alright, I'll fix it.

Comment (raman-m) [reply src/Ocelot/Authorization/AuthorizationMiddleware.cs]: I suggest removing informational logging while keeping the warnings intact!

File: src/Ocelot/Authorization/AuthorizationMiddleware.cs (hunk 9 above)
Comment (RaynaldM) [reply src/Ocelot/Authorization/AuthorizationMiddleware.cs:86]: I hear this every day: it's not my code.
True, but when you touch a method/class and see problems, you fix them, especially in the case of Ocelot with a very high test coverage rate.

File: src/Ocelot/DownstreamUrlCreator/DownstreamUrlCreatorMiddleware.cs (hunk 13 above)
Comment (RaynaldM) [reply src/Ocelot/DownstreamUrlCreator/DownstreamUrlCreatorMiddleware.cs:44]: set downstreamRequest and upstreamPath  later

File: src/Ocelot/DownstreamUrlCreator/DownstreamUrlCreatorMiddleware.cs (hunk 14 above)
Comment (RaynaldM) [reply src/Ocelot/DownstreamUrlCreator/DownstreamUrlCreatorMiddleware.cs:115]: > I need not anything to explain you Start contributing to the project, Ray

very constructive remark

Comment (RaynaldM) [reply src/Ocelot/DownstreamUrlCreator/DownstreamUrlCreatorMiddleware.cs:115]: My comment is that if an average developer comes across this piece of code, it's not certain that they will understand what it's supposed to do (myself included).

File: src/Ocelot/DownstreamUrlCreator/DownstreamUrlCreatorMiddleware.cs (hunk 15 above)
Comment (RaynaldM) [reply src/Ocelot/DownstreamUrlCreator/DownstreamUrlCreatorMiddleware.cs]: That's right, it doesn't cost anything to make the change.

File: src/Ocelot/DownstreamUrlCreator/DownstreamUrlCreatorMiddleware.cs (hunk 16 above)
Comment (RaynaldM) [reply src/Ocelot/DownstreamUrlCreator/DownstreamUrlCreatorMiddleware.cs]: > @RaynaldM FYI, you are a teammate and can push commits to any PRs or branches❗ Feel free to make improvements as needed. I will focus on the acceptance tests since @ggnaegi [is waiting](https://github.com/ThreeMammals/Ocelot/pull/2336#pullrequestreview-3471728607) for them.

I am not knowledgeable enough to do that.

File: src/Ocelot/Authorization/AuthorizationMiddleware.cs (hunk 9 above)
Comment (raman-m) [reply src/Ocelot/Authorization/AuthorizationMiddleware.cs:86]: Regarding coverage of this middleware &rarr; [Coveralls build](https://coveralls.io/builds/76483973) &rarr; [AuthorizationMiddleware](https://coveralls.io/builds/76483973/source?filename=Ocelot%2FAuthorization%2FAuthorizationMiddleware.cs) &rarr; **67%** Ups! 🤣 
This middleware hasn’t been updated or modified by any developer since it was created in 2016/17.

Scenario:  
- Given I refactor outdated middleware developed ages ago  
- And I rename one argument  
- And remove one-reference helper methods  
- When I ask Raynald to review the code  
- Then Raynald does NOT like the coverage or source quality  
- And things in the project start to go downhill

So, true!

File: src/Ocelot/DownstreamUrlCreator/DownstreamUrlCreatorMiddleware.cs (hunk 15 above)
Comment (raman-m) [reply src/Ocelot/DownstreamUrlCreator/DownstreamUrlCreatorMiddleware.cs]: It has a single reference and is called at this line:
```csharp
downstreamRequest.AbsolutePath = GetPath(dsPath);
```
If it returns a Span, then calling `ToString()` is necessary to assign it to the `AbsolutePath` property.
But suggestion still makes sense.

File: src/Ocelot/Authorization/AuthorizationMiddleware.cs (hunk 8 above)
Comment (raman-m) [reply src/Ocelot/Authorization/AuthorizationMiddleware.cs]: Fixed in commit https://github.com/ThreeMammals/Ocelot/pull/2336/commits/a5f95213bda902591315cbe6c8a225c5321fc63f ✔️ 
Removed logging before service calls, and wrapped all other logging lines with `#if DEBUG`. All arguments are now `Func<string>`

File: src/Ocelot/Authorization/AuthorizationMiddleware.cs (hunk 9 above)
Comment (raman-m) [reply src/Ocelot/Authorization/AuthorizationMiddleware.cs:86]: Fixed in commit https://github.com/ThreeMammals/Ocelot/pull/2336/commits/a5f95213bda902591315cbe6c8a225c5321fc63f ✔️ 
All logging statements are now enclosed within `#if DEBUG` blocks.

File: src/Ocelot/Configuration/File/FileAuthenticationOptions.cs (hunk 10 above)
Comment (raman-m) [reply src/Ocelot/Configuration/File/FileAuthenticationOptions.cs]: Fixed in https://github.com/ThreeMammals/Ocelot/pull/2336/commits/a5f95213bda902591315cbe6c8a225c5321fc63f in favor of `options` due to `from` C# keyword

File: src/Ocelot/DownstreamUrlCreator/DownstreamPathPlaceholderReplacer.cs (hunk 11 above)
Comment (raman-m) [reply src/Ocelot/DownstreamUrlCreator/DownstreamPathPlaceholderReplacer.cs]: Fixed in commit https://github.com/ThreeMammals/Ocelot/pull/2336/commits/a5f95213bda902591315cbe6c8a225c5321fc63f ✔️

File: src/Ocelot/DownstreamUrlCreator/DownstreamUrlCreatorMiddleware.cs (hunk 13 above)
Comment (raman-m) [reply src/Ocelot/DownstreamUrlCreator/DownstreamUrlCreatorMiddleware.cs:44]: Lines have been relocated to the suggested positions in commit https://github.com/ThreeMammals/Ocelot/pull/2336/commits/a5f95213bda902591315cbe6c8a225c5321fc63f ✔️

File: src/Ocelot/DownstreamUrlCreator/DownstreamUrlCreatorMiddleware.cs (hunk 14 above)
Comment (raman-m) [reply src/Ocelot/DownstreamUrlCreator/DownstreamUrlCreatorMiddleware.cs:115]: Added description in https://github.com/ThreeMammals/Ocelot/pull/2336/commits/a5f95213bda902591315cbe6c8a225c5321fc63f ✔️ 

This code also enables [control over parameter existence](https://ocelot.readthedocs.io/en/latest/features/routing.html#control-over-parameter-existence), which is a nice feature. Previously, this capability was unpublished, but I refactored the method to fully support it, added test coverage, and released it in version [22.0.0](https://github.com/ThreeMammals/Ocelot/releases/tag/22.0.0) (see PRs #1182 and #2003).

File: src/Ocelot/DownstreamUrlCreator/DownstreamUrlCreatorMiddleware.cs (hunk 15 above)
Comment (raman-m) [reply src/Ocelot/DownstreamUrlCreator/DownstreamUrlCreatorMiddleware.cs]: Fixed in commit https://github.com/ThreeMammals/Ocelot/pull/2336/commits/a5f95213bda902591315cbe6c8a225c5321fc63f ✔️

File: src/Ocelot/DownstreamUrlCreator/DownstreamUrlCreatorMiddleware.cs (hunk 16 above)
Comment (raman-m) [reply src/Ocelot/DownstreamUrlCreator/DownstreamUrlCreatorMiddleware.cs]: But, I am...
Fixed in commit https://github.com/ThreeMammals/Ocelot/pull/2336/commits/a5f95213bda902591315cbe6c8a225c5321fc63f ✔️

**Review by RaynaldM — APPROVED** [review]
