### PR TITLE
Placeholders matching must work if RouteIsCaseSensitive = false

### LINKED ISSUE #2209: routes became case-sensitive after updating from 23.3.6 to 23.4.0
## Expected Behavior / New Feature
I expected the route to hit

## Actual Behavior / Motivation for New Feature
Route didn't hit. Got 400 error . 

## Steps to Reproduce the Problem

1. Updated `Ocelot` and `Ocelot.Cache.CacheManager` from 23.3.6 to 23.4.0
2. I called this from my frontend. Notice the uppercase letters of the request issued.
```typescript
getEntityRecords(id: number): Observable<EventLogData[]> {
  const url = 'https://blablabla.azurecontainerapps.io/Entities/${id}/Events/RecordsData';
  return this.httpClient.get<EventLogData[]>(url);
}
```
ocelot.json looks like this
```json
{
  "Routes": [
    {
      "DownstreamPathTemplate": "/api/entities/{id}/events/recordsdata",
      "DownstreamScheme": "https",
      "DownstreamHostAndPorts": [
        {
          "Host": "blabla-service.net",
          "Port": 443
        }
      ],
      "UpstreamPathTemplate": "/entities/{id}/events/recordsdata",
      "UpstreamHttpMethod": [
        "GET"
      ],
      "FileCacheOptions": {
        "TtlSeconds": 0,
        "Region": "UserCache"
      },
      "RouteClaimsRequirement": {
        "Claims": "ReadEntities"
      }
    }
  ],
  "GlobalConfiguration": {
    "BaseUrl": "https://blablabla.azurecontainerapps.io"
  }
}
```
3. What's interesting is when I send the request `const url = 'https://blablabla.azurecontainerapps.io/entities/${id}/events/recordsdata';` i.e same case as defined in ocelot it worked. The docs mention that it is [case-insensitive](https://ocelot.readthedocs.io/en/latest/features/routing.html) by default. Is this expected behavior in 23.4.0 or have i missed something.

## Specifications

  - Version: 23.4.0
  - Platform:  .NET 8
  - Subsystem: Windows

### PR DESCRIPTION
**Pull request by ggnaegi**
## Fixes #2209 
- #2209 
 

## Proposed Changes
  - We are now performing case-insensitive matching for the path pattern, but we preserve the case for the placeholders. The verification of case sensitivity is not handled in this part of the code.
  - Adding several unit and acceptance tests to verify the behavior

### CODE REVIEW

**Comment by ggnaegi** [comment]
@raman-m ready for review

File: test/Ocelot.AcceptanceTests/Routing/RoutingTests.cs [hunk 1]
```diff
@@ -442,6 +442,64 @@ public void ShouldMatchComplexQueriesWithEmbeddedPlaceholders(string downstream,
...
+        "/api/CATEGORIES_home/furniture_items/789?sort=asc", "/api/categories/home-furniture", "?sort=asc")]
+    [InlineData("/api/orders/{order}-{detail}?status={status}", "/api/orders_{order}/{detail}_invoice/{ref}?status={status}", 
+        "/API/ORDERS_987/abc_invOiCE/123?status=shipped", "/api/orders/987-abc", "?status=shipped")]
+    [InlineData("/api/transactions/{type}-{region}", "/api/transactions_{type}/{region}_summary/{year}?q={query}", 
+        "/api/TRanSacTIONS_sales/NA_summary/2024?q=forecast", "/api/transactions/sales-NA", "?q=forecast")]
+    public void ShouldNotMatchComplexQueriesCaseSensitive(string downstream, string upstream, string requestUrl, string downstreamPath, string queryString)
+    {
+        var port = PortFinder.GetRandomPort();
+        var route = GivenRoute(port, upstream, downstream);
+        route.RouteIsCaseSensitive = true;
```
Comment (raman-m) [inline test/Ocelot.AcceptanceTests/Routing/RoutingTests.cs:494]: Well... Again, I'm trying to understand entire logic.
We have only 2 places where the property is applied:
### 1
https://github.com/ThreeMammals/Ocelot/blob/7a5046f18899f97639777604a4be8192abfbbb29/src/Ocelot/Configuration/Creator/UpstreamHeaderTemplatePatternCreator.cs#L42-L44
### 2
https://github.com/ThreeMammals/Ocelot/blob/7a5046f18899f97639777604a4be8192abfbbb29/src/Ocelot/Configuration/Creator/UpstreamTemplatePatternCreator.cs#L76-L78
This 2nd code snippet seems the right place where we apply case sensitivity.

Not an issue.

**Review by raman-m — APPROVED** [review]

File: src/Ocelot/DownstreamRouteFinder/UrlMatcher/UrlPathPlaceholderNameAndValueFinder.cs [hunk 2]
```diff
@@ -149,7 +150,10 @@ private static string EscapeExceptBraces(string input)
                 escaped.Append(Regex.Escape(c.ToString()));
             }
         }
- 
-        return escaped.ToString();
+
+        // Here we are not interested in the path itself, only the placeholders.
+        // Path validation is not part of this class, therefore allowing case-insensitive 
+        // matching.
+        return $"^(?i){escaped}";
```
[the remark this answers is not in the document]
Comment (ggnaegi) [reply src/Ocelot/DownstreamRouteFinder/UrlMatcher/UrlPathPlaceholderNameAndValueFinder.cs:157]: @raman-m What we have lost: `/blabla/bliBLI/{PlaceHolder}` wil not match `/blabla/blibli/{PlaceHolder}` because the elements after the host name could be case sensitive, and stricly taken `/blabla/bliBLI` can't match `/blabla/blibli`. But, yes, the behavior with `^(?i)` is the same as the code snippet you provided.

File: test/Ocelot.AcceptanceTests/Routing/RoutingTests.cs (hunk 1 above)
Comment (ggnaegi) [reply test/Ocelot.AcceptanceTests/Routing/RoutingTests.cs:494]: @raman-m And we don't pass the pattern to the placeholder finder, but the original one, without the regex chars.

**Comment by raman-m** [comment]
@ggnaegi  Regarding the merged commit https://github.com/ThreeMammals/Ocelot/commit/fe029eb0d574ee8ec9d91618b5fa2023966f40b6, there has been an override of the name/title of the PR. The significant issue is the lack of reference to the fixed bug. In the future, please maintain the original commit name while prefixing it with the reference to the issue:
```diff
- Fixing issue 2209, adding extensive set of unit and acceptance tests (#2210)
+ #2209 Placeholders matching must work if RouteIsCaseSensitive = false (#2210)
```
As an Administrator, I will now proceed to rectify the commit name...

**Comment by raman-m** [comment]
### New commit in develop is https://github.com/ThreeMammals/Ocelot/commit/d41f8fa9436ba984ca12503bc9bd3be1db51d7de ❕
