### PR TITLE
#952 #1174 Merge query strings without duplicate values

### LINKED ISSUE #952: Query string parameters are not correctly removed from downstream template
## Expected Behavior
I want to be able to map a query parameter on my gateway API to a query parameter with a different name on my downstream API.

```json
{
  "Routes": [
    {
      "DownstreamPathTemplate": "/persons?personId={userId}",
      "UpstreamPathTemplate": "/users?userId={userId}"
    } 
  ]
}
```
When calling `/users?userId=webley`, I would expect the downstream call to be `/persons?personId=webley`

## Actual Behavior
The downstream route generated is `/persons?userId=webley&personId=webley`

## Steps to Reproduce the Problem
  1. Create a re-route with query strings in both the upstream and downstream templates
  1. Call into the upstream endpoint
  1. The unwanted query parameter will remain on the downstream request

In **DownstreamUrlCreatorMiddleware.cs**, the method `RemoveQueryStringParametersThatHaveBeenUsedInTemplate(context)` seems to be called if the downstream path does not contain a query string. I have tested that this works as expected.  However, if the downstream path contains a query string, unused params from the upstream template are never removed. I think they probably should be.

## Specifications
  - Version: 13.8.0-alpha0006 (and 13.5.2)
  - Platform: Win 10

### LINKED ISSUE #1174: Query string parameter getting duplicated in downstream path
## Expected Behavior
Query string parameter should not duplicate. 

1. 

Upstream Request: `contracts?projectNumber=45&startDate=2019-12-12&endDate=2019-12-12`
Downstream Request: `api/contracts?projectNumber=45&startDate=2019-12-12&endDate=2019-12-12`

2. 

Upstream Request: `contracts?$filter=ProjectNumber eq 45 and DateOfSale ge 2020-03-01T00:00:00z and DateOfSale le 2020-03-15T00:00:00z`
Downstream Request: `api/contracts?$filter=ProjectNumber eq 45 and DateOfSale ge 2020-03-01T00:00:00z and DateOfSale le 2020-03-15T00:00:00z`

## Actual Behavior
Query string parameter is duplicated. This works fine with web api endpoints even if query string parameter gets duplicated but fails on OData endpoints. 

1. 

Upstream Request: `contracts?projectNumber=45&startDate=2019-12-12&endDate=2019-12-12`
Downstream Request: `api/contracts?projectNumber=45&startDate=2019-12-12&endDate=2019-12-12&projectNumber=45`

2. 

Upstream Request: `contracts?$filter=ProjectNumber eq 45 and DateOfSale ge 2020-03-01T00:00:00z and DateOfSale le 2020-03-15T00:00:00z`
Downstream Request: `api/contracts?$filter=ProjectNumber eq 45 and DateOfSale ge 2020-03-01T00:00:00z and DateOfSale le 2020-03-15T00:00:00z&$filter=ProjectNumber eq 45 and DateOfSale ge 2020-03-01T00:00:00z and DateOfSale le 2020-03-15T00:00:00z`

Please see console log below
```
info: Ocelot.RateLimit.Middleware.ClientRateLimitMiddleware[0]
      requestId: 0HLUK013URU17:00000001, previousRequestId: no previous request id, message: EndpointRateLimiting is not enabled for /api/contracts?{everythingelse}
info: Ocelot.Authentication.Middleware.AuthenticationMiddleware[0]
      requestId: 0HLUK013URU17:00000001, previousRequestId: no previous request id, message: No authentication needed for /contracts
info: Ocelot.Authorisation.Middleware.AuthorisationMiddleware[0]
      requestId: 0HLUK013URU17:00000001, previousRequestId: no previous request id, message: /api/contracts?{everythingelse} route does not require user to be authorised
info: Ocelot.Requester.Middleware.HttpRequesterMiddleware[0]
      requestId: 0HLUK013URU17:00000001, previousRequestId: no previous request id, message: 200 (OK) status code, request uri: http://localhost:45626/api/contracts?**projectNumber=45**&startDate=2019-12-12&endDate=2019-12-12**&projectNumber=45**
info: Ocelot.RateLimit.Middleware.ClientRateLimitMiddleware[0]
      requestId: 0HLUK013URU18:00000001, previousRequestId: no previous request id, message: EndpointRateLimiting is not enabled for /api/contracts?{everythingelse}
info: Ocelot.Authentication.Middleware.AuthenticationMiddleware[0]
      requestId: 0HLUK013URU18:00000001, previousRequestId: no previous request id, message: No authentication needed for /contracts
info: Ocelot.Authorisation.Middleware.AuthorisationMiddleware[0]
      requestId: 0HLUK013URU18:00000001, previousRequestId: no previous request id, message: /api/contracts?{everythingelse} route does not require user to be authorised
warn: Ocelot.Requester.Middleware.HttpRequesterMiddleware[0]
      requestId: 0HLUK013URU18:00000001, previousRequestId: no previous request id, message: 404 (Not Found) status code, request uri: http://localhost:45626/api/contracts?**$filter=ProjectNumber eq 45 and DateOfSale ge 2020-03-01T00:00:00z and DateOfSale le 2020-03-15T00:00:00z**&$**filter=ProjectNumber eq 45 and DateOfSale ge 2020-03-01T00:00:00z and DateOfSale le 2020-03-15T00:00:00z**
```

## Steps to Reproduce the Problem

  1. Create an api controller with two actions, one normal web api and other one as OData.
  1. Define Reroute as below
```json
{ 
      "DownstreamPathTemplate": "/api/contracts?{everythingelse}",
      "DownstreamScheme": "http",
      "DownstreamHostAndPorts": [
        {
          "Host": "localhost",
          "Port": 45626
        }
      ],
      "UpstreamPathTemplate": "/contracts?{everythingelse}",
      "UpstreamHttpMethod": [ "Get" ]
}
```
  3. Fire get request on OData endpoint with $filter query string parameter and it return 404 not found while directly hitting same endpoint by removing duplicate query string it works fine.

## Specifications

  - Version: 14.1.0
  - Platform: .NET Core 3.1 on Windows

## More Details
While debugging I found following code block in `DownstreamUrlCreatorMiddleware` is causing query string duplication.
```csharp
  if (string.IsNullOrEmpty(context.DownstreamRequest.Query))
  {
       context.DownstreamRequest.Query = GetQueryString(dsPath);
  }
  else
  {
      context.DownstreamRequest.Query += GetQueryString(dsPath).Replace('?', '&');
  }
```
Removing this code block solved the problem but i don't know what other negative impact it would cause.

### PR DESCRIPTION
**Pull request by wast**
## Fixes #952 
- #952 

## Fixes #1174 
- #1174 

## Proposed Changes

  - added method to merge query strings without duplicate values
  - added tests
  - changed logic

### CODE REVIEW

**Comment by raman-m** [comment]
Hi!

Cannot review PR with conflicts!
You can do the following:
1. Resolve all merge conflicts
2. Update/pull develop branch and merge it to current feature branch. Try to rebase.
3. Close this PR. Create new feature branch from develop one. And apply all changes. Create new PR.

The best option is **3** for sure, because we will have linear history in **develop**.

Please note, this PR is created in your fork. You are the member of Ocelot team, so you can create branches inside of [this repo](../) (**not forked**)!

**Comment by wast** [comment]
I guess that was before joining :) I will try to rebase and if no success, will proceed with option 3.

**Comment by raman-m** [comment]
Perfect!
Wish you good luck! 😉

**Comment by raman-m** [comment]
@wast commented [on Jun 19, 2023](#issuecomment-1597082029):
> I guess that was before joining :) I will try to rebase and if no success, will proceed with option 3.

Lazy bones, Stjepan! 😉 
I've done merging develop and resolved all merge conflicts, and made a successful build.
We can go with code review now... 😸

File: src/Ocelot/DownstreamUrlCreator/Middleware/DownstreamUrlCreatorMiddleware.cs [hunk 1]
```diff
@@ -1,156 +1,179 @@
...
+                    if (string.IsNullOrEmpty(downstreamRequest.Query))
+                    {
+                        downstreamRequest.Query = GetQueryString(dsPath);
+                    }
+                    else
+                    {
+                        //downstreamRequest.Query += GetQueryString(dsPath).Replace('?', '&');
+                        var newQueryString = GetQueryString(dsPath).Replace('?', '&');
+                        newQueryString = MergeQueryStringsWithoutDuplicateValues(downstreamRequest.Query, newQueryString);
+                        downstreamRequest.Query = "?" + newQueryString;                    }
```
Comment (RaynaldM) [inline src/Ocelot/DownstreamUrlCreator/Middleware/DownstreamUrlCreatorMiddleware.cs:86]:
```suggestion
                        downstreamRequest.Query = '?' + newQueryString;                    }
```

File: src/Ocelot/DownstreamUrlCreator/Middleware/DownstreamUrlCreatorMiddleware.cs [hunk 2]
```diff
@@ -1,156 +1,179 @@
...
+
+            await _next.Invoke(httpContext);
+        }
+
+        private static string MergeQueryStringsWithoutDuplicateValues(string queryString, string newQueryString)
+        {
+            var queries = HttpUtility.ParseQueryString(queryString);
+            var newQueries = HttpUtility.ParseQueryString(newQueryString);
+
+            var dict = new Dictionary<string, string>();
```
Comment (RaynaldM) [inline src/Ocelot/DownstreamUrlCreator/Middleware/DownstreamUrlCreatorMiddleware.cs:106]:
```suggestion
            newQueries.AllKeys.Where(key => !string.IsNullOrEmpty(key)).ToDictionary(key => key, key => newQueries[key]);
```

File: src/Ocelot/DownstreamUrlCreator/Middleware/DownstreamUrlCreatorMiddleware.cs [hunk 3]
```diff
@@ -1,156 +1,179 @@
...
+            {
+                if (string.IsNullOrEmpty(key) || dict.ContainsValue(queries[key]))
+                {
+                    continue;
+                }
+
+                dict.Add(key, queries[key]);
+            }
+
+            return string.Join("&", dict.Select(kvp => string.Format("{0}={1}", kvp.Key, kvp.Value)));
```
Comment (RaynaldM) [inline src/Ocelot/DownstreamUrlCreator/Middleware/DownstreamUrlCreatorMiddleware.cs:125]:
```suggestion
            return string.Join('&', dict.Select(kvp => $"{kvp.Key}={kvp.Value}"));
```

File: src/Ocelot/DownstreamUrlCreator/Middleware/DownstreamUrlCreatorMiddleware.cs [hunk 4]
```diff
@@ -1,156 +1,179 @@
...
+                    {
+                        downstreamRequest.Query = '?' + downstreamRequest.Query.Substring(1);
+                    }
+                }
+            }
+        }
+
+        private static string GetPath(DownstreamPath dsPath)
+        {
+            return dsPath.Value.Substring(0, dsPath.Value.IndexOf('?', StringComparison.Ordinal));
```
Comment (RaynaldM) [inline src/Ocelot/DownstreamUrlCreator/Middleware/DownstreamUrlCreatorMiddleware.cs:153]: '?' could a private const of class

**Review by RaynaldM — APPROVED** [review]
I added some suggestions and comments

**Comment by raman-m** [comment]
> @RaynaldM left [a comment](#pullrequestreview-1540839845)

In fact, you should have requested changes, not give the approval. 🤣 
Let me do that...

**Review by raman-m — CHANGES_REQUESTED** [review]
@wast Hi!
Could you work on [code review issues](#pullrequestreview-1540839845) by @RaynaldM please?

---

image

And, Stjepan,
I don't see **develop** branch in [your fork](/wast/Ocelot/branches)! Your fork is too old.

Could you [Sync fork](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork) please? So, new **develop** branch will occur with all top commits!

---

If [Sync fork](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork) button won't help to make **develop** branch as default one,
Run this script please:
```shell
git remote add upstream https://github.com/ThreeMammals/Ocelot.git // add original repo as upstream remote
git fetch upstream                                                 // pull changes from original repo
git checkout -b develop upstream/develop                           // pull down develop branch locally
git push -u origin develop                                         // push develop branch to fork
```
Don't forget to make **develop** as default branch in GitHub.

---
⚠️  After that, could you rebase feature branch (**master**) onto **develop** please?
Let me know updating results please!

**Review by RaynaldM — APPROVED** [review]

**Comment by raman-m** [comment]
@wast 
Could you [add me as collaborator](/wast/Ocelot/settings/access) to your forked repo please? I will create **develop** branch and make it default.

**Comment by wast** [comment]
Sorry for inactivity. Been busy lately with vacation :P I'm on it tomorrow

**Comment by raman-m** [comment]
> @wast commented [on Aug 2](#issuecomment-1662547412)

Congrats with vacation starting!
When will you come back?

File: src/Ocelot/DownstreamUrlCreator/Middleware/DownstreamUrlCreatorMiddleware.cs [hunk 5]
```diff
@@ -102,6 +98,35 @@ public async Task Invoke(HttpContext httpContext)
...
+                if (!string.IsNullOrEmpty(key))
+                {
+                    dict.Add(key, newQueries[key]);
+
+                }
+            }
+
+            foreach (var key in queries.AllKeys)
+            {
+                if (string.IsNullOrEmpty(key) || dict.ContainsValue(queries[key]))
```
Comment (raman-m) [inline src/Ocelot/DownstreamUrlCreator/Middleware/DownstreamUrlCreatorMiddleware.cs:119]: Cannot get it!
Why do we have to check value existence, not key one, to skip the key?

File: src/Ocelot/DownstreamUrlCreator/Middleware/DownstreamUrlCreatorMiddleware.cs [hunk 6]
```diff
@@ -102,6 +98,35 @@ public async Task Invoke(HttpContext httpContext)
...
+                {
+                    continue;
+                }
+
+                dict.Add(key, queries[key]);
+            }
+
+            return string.Join("&", dict.Select(kvp => string.Format("{0}={1}", kvp.Key, kvp.Value)));
```
Comment (raman-m) [inline src/Ocelot/DownstreamUrlCreator/Middleware/DownstreamUrlCreatorMiddleware.cs:127]: Perfect!
Now imagine we have such query string: `?id=1&id=2&id=3`  😉 
This query string is standard template for array parameter binding in ASP.NET controller action. 
How will your merging algorithm process this case? 🤣

File: test/Ocelot.AcceptanceTests/RoutingWithQueryStringTests.cs [hunk 7]
```diff
@@ -62,7 +62,85 @@ public void should_return_response_200_with_query_string_template()
...
+            };
+
+            this.Given(x => x.GivenThereIsAServiceRunningOn($"http://localhost:{port}", $"/api/subscriptions/{subscriptionId}/updates", $"?unitId={unitId}&x=y", 200, "Hello from Laura"))
+                .And(x => _steps.GivenThereIsAConfiguration(configuration))
+                .And(x => _steps.GivenOcelotIsRunning())
+                .When(x => _steps.WhenIGetUrlOnTheApiGateway($"/api/units/{subscriptionId}/updates?unit={unitId}&x=y"))
+                .Then(x => _steps.ThenTheStatusCodeShouldBe(HttpStatusCode.OK))
+                .And(x => _steps.ThenTheResponseBodyShouldBe("Hello from Laura"))
+                .BDDfy();
+        }
```
Comment (raman-m) [inline test/Ocelot.AcceptanceTests/RoutingWithQueryStringTests.cs:139]: I see a copy-paste code! So, DRY violation has detected!

You can extract the body code and define a private helper with one string parameter
```csharp
private void ShouldReturnResponse200WithQueryStringTemplate(string queryUrl)
{
    // ...
    .When(x => _steps.WhenIGetUrlOnTheApiGateway(queryUrl))
    // ...
}
```
and reuse this private helper for both fact-methods varying the param like that:
```csharp
public void Should_return_response_200_with_query_string_template_different_keys()
{
    // ...
    ShouldReturnResponse200WithQueryStringTemplate($"/api/units/{subscriptionId}/updates?unit={unitId}"));
}

public void Should_return_response_200_with_query_string_template_additional_key()
{
    // ...
    ShouldReturnResponse200WithQueryStringTemplate($"/api/units/{subscriptionId}/updates?unit={unitId}&x=y"));
}
```
Finally, it is better to define xUnit Theory. 😄

File: test/Ocelot.AcceptanceTests/RoutingWithQueryStringTests.cs
Comment (raman-m) [inline test/Ocelot.AcceptanceTests/RoutingWithQueryStringTests.cs:1]: What about testing user scenarios from #952 and #1174 ?

**Review by raman-m — CHANGES_REQUESTED** [review]
Hi @wast !
Your changes are quite small, but sometimes small things need to be thoroughly tested.

And, we are going to fix #952 and #1174. 
Could you add acceptance tests for both issues please?

**Comment by raman-m** [comment]
@wast  Stjepan, how are you?

We have 2 pending code review sessions:
- @RaynaldM previously approved these changes [on Jul 21](#pullrequestreview-1540839845)
- @raman-m requested changes [on Aug 3](#pullrequestreview-1561165802)

Will you come back to us to work on these review issues?

**Comment by wast** [comment]
If you guys feel another week of away time is fine, then yes, I'll be back.

**Comment by raman-m** [comment]
Sorry, did not get you... I cannot joking now.

Your last previous message
> @wast commented [on Aug 2](#issuecomment-1662547412)
Sorry for inactivity. Been busy lately with vacation :P I'm on it tomorrow

Looks like your vacation is still going on, right?

**Comment by raman-m** [comment]
> @wast [commented](#issuecomment-1781624639)
If you guys feel another week of away time is fine, then yes, I'll be back.

It is absolutely fine! Enjoy your free time. 😉

File: src/Ocelot/DownstreamUrlCreator/Middleware/DownstreamUrlCreatorMiddleware.cs [hunk 8]
```diff
@@ -90,6 +92,33 @@ public async Task Invoke(HttpContext httpContext)
...
+            }
+
+            foreach (var key in queries.AllKeys)
+            {
+                if (string.IsNullOrEmpty(key) || dict.ContainsValue(queries[key]))
+                {
+                    continue;
+                }
+
+                dict.Add(key, queries[key]);
```
Comment (raman-m) [inline src/Ocelot/DownstreamUrlCreator/Middleware/DownstreamUrlCreatorMiddleware.cs:116]: The main concern about usage of `Add` method is that this method generates exception when duplicate key has detected. Why not to use `TryAdd` instead of `Add`?
```suggestion
                dict.TryAdd(key, queries[key]);
```

**Review by raman-m — CHANGES_REQUESTED** [review]

File: src/Ocelot/DownstreamUrlCreator/Middleware/DownstreamUrlCreatorMiddleware.cs (hunk 8 above)
Comment (raman-m) [reply src/Ocelot/DownstreamUrlCreator/Middleware/DownstreamUrlCreatorMiddleware.cs]: Fixed in https://github.com/ThreeMammals/Ocelot/pull/1182/commits/fef94b63b48cea1bbdd36180001e4e44d5586905

File: src/Ocelot/DownstreamUrlCreator/Middleware/DownstreamUrlCreatorMiddleware.cs (hunk 5 above)
Comment (raman-m) [reply src/Ocelot/DownstreamUrlCreator/Middleware/DownstreamUrlCreatorMiddleware.cs]: Not an issue, this is merging feature.
Fixed in https://github.com/ThreeMammals/Ocelot/pull/1182/commits/fef94b63b48cea1bbdd36180001e4e44d5586905

File: src/Ocelot/DownstreamUrlCreator/Middleware/DownstreamUrlCreatorMiddleware.cs [hunk 9]
```diff
@@ -102,6 +98,35 @@ public async Task Invoke(HttpContext httpContext)
...
+
+            var dict = new Dictionary<string, string>();
+            foreach (var key in newQueries.AllKeys)
+            {
+                if (!string.IsNullOrEmpty(key))
+                {
+                    dict.Add(key, newQueries[key]);
+
+                }
+            }
```
[the remark this answers is not in the document]
Comment (raman-m) [reply src/Ocelot/DownstreamUrlCreator/Middleware/DownstreamUrlCreatorMiddleware.cs]: ✔️ Fixed in https://github.com/ThreeMammals/Ocelot/pull/1182/commits/fef94b63b48cea1bbdd36180001e4e44d5586905

File: src/Ocelot/DownstreamUrlCreator/Middleware/DownstreamUrlCreatorMiddleware.cs [hunk 10]
```diff
@@ -102,6 +98,35 @@ public async Task Invoke(HttpContext httpContext)
...
+
+            foreach (var key in queries.AllKeys)
+            {
+                if (string.IsNullOrEmpty(key) || dict.ContainsValue(queries[key]))
+                {
+                    continue;
+                }
```
[the remark this answers is not in the document]
Comment (raman-m) [reply src/Ocelot/DownstreamUrlCreator/Middleware/DownstreamUrlCreatorMiddleware.cs]: Not an issue, this is the merging feature 🐞 
Fixed in https://github.com/ThreeMammals/Ocelot/pull/1182/commits/fef94b63b48cea1bbdd36180001e4e44d5586905

File: src/Ocelot/DownstreamUrlCreator/Middleware/DownstreamUrlCreatorMiddleware.cs (hunk 2 above)
Comment (raman-m) [reply src/Ocelot/DownstreamUrlCreator/Middleware/DownstreamUrlCreatorMiddleware.cs]: ✔️ Fixed in https://github.com/ThreeMammals/Ocelot/pull/1182/commits/fef94b63b48cea1bbdd36180001e4e44d5586905

File: src/Ocelot/DownstreamUrlCreator/Middleware/DownstreamUrlCreatorMiddleware.cs (hunk 1 above)
Comment (raman-m) [reply src/Ocelot/DownstreamUrlCreator/Middleware/DownstreamUrlCreatorMiddleware.cs]: Fixed in https://github.com/ThreeMammals/Ocelot/pull/1182/commits/275d034250762557f50e8461d27b3446893b54a1

File: src/Ocelot/DownstreamUrlCreator/Middleware/DownstreamUrlCreatorMiddleware.cs (hunk 3 above)
Comment (raman-m) [reply src/Ocelot/DownstreamUrlCreator/Middleware/DownstreamUrlCreatorMiddleware.cs]: Fixed in https://github.com/ThreeMammals/Ocelot/pull/1182/commits/275d034250762557f50e8461d27b3446893b54a1

File: src/Ocelot/DownstreamUrlCreator/Middleware/DownstreamUrlCreatorMiddleware.cs (hunk 4 above)
Comment (raman-m) [reply src/Ocelot/DownstreamUrlCreator/Middleware/DownstreamUrlCreatorMiddleware.cs]: Fixed in https://github.com/ThreeMammals/Ocelot/pull/1182/commits/275d034250762557f50e8461d27b3446893b54a1

**Comment by raman-m** [comment]
>@RaynaldM previously approved these changes [on Jul 21](#pullrequestreview-1540839845)

Ray, your code review issues have been fixed by commit https://github.com/ThreeMammals/Ocelot/pull/1182/commits/275d034250762557f50e8461d27b3446893b54a1

**Review by raman-m — APPROVED** [review]
Ready for delivery!
