### PR TITLE
#2116 Escaping unsafe pattern values of `Regex` constructor ​​derived from URL query parameter values containing special `Regex` chars

### LINKED ISSUE #2116: `Regex` exception when route template placeholder contains invalid character `)`
## Expected Behavior 
Given a route parameter including a `)` character, then a 4** status code is expected. 

Earlier versions before 19.0.4 returned status code 404.

## Actual Behavior 
Exception which causes a response with status code 500.

StackTrace:
`
Exception caught in global error handler, exception message: Invalid pattern '\b*path=debug)\b' at offset 14. Too many )'s., exception stack:    at System.Text.RegularExpressions.RegexParser.ScanRegex()
         at System.Text.RegularExpressions.RegexParser.Parse(String pattern, RegexOptions options, CultureInfo culture)
         at System.Text.RegularExpressions.Regex..ctor(String pattern, CultureInfo culture)
         at Ocelot.DownstreamUrlCreator.Middleware.DownstreamUrlCreatorMiddleware.RemoveQueryStringParametersThatHaveBeenUsedInTemplate(DownstreamRequest downstreamRequest, List`1 templatePlaceholderNameAndValues)
         at Ocelot.DownstreamUrlCreator.Middleware.DownstreamUrlCreatorMiddleware.Invoke(HttpContext httpContext)
         at Ocelot.LoadBalancer.Middleware.LoadBalancingMiddleware.Invoke(HttpContext httpContext)
         at Ocelot.DownstreamPathManipulation.Middleware.ClaimsToDownstreamPathMiddleware.Invoke(HttpContext httpContext)
         at Ocelot.QueryStrings.Middleware.ClaimsToQueryStringMiddleware.Invoke(HttpContext httpContext)
         at Ocelot.Headers.Middleware.ClaimsToHeadersMiddleware.Invoke(HttpContext httpContext)
         at Ocelot.Authorization.Middleware.AuthorizationMiddleware.Invoke(HttpContext httpContext)
         at Ocelot.Claims.Middleware.ClaimsToClaimsMiddleware.Invoke(HttpContext httpContext)
         at Ocelot.Authentication.Middleware.AuthenticationMiddleware.Invoke(HttpContext httpContext)
         at Ocelot.RequestId.Middleware.RequestIdMiddleware.Invoke(HttpContext httpContext)
         at Ocelot.RateLimit.Middleware.ClientRateLimitMiddleware.Invoke(HttpContext httpContext)
         at Ocelot.Request.Middleware.DownstreamRequestInitialiserMiddleware.Invoke(HttpContext httpContext)
         at Ocelot.Headers.Middleware.HttpHeadersTransformationMiddleware.Invoke(HttpContext httpContext)
         at Ocelot.Security.Middleware.SecurityMiddleware.Invoke(HttpContext httpContext)
         at Ocelot.Multiplexer.MultiplexingMiddleware.Fire(HttpContext httpContext, RequestDelegate next)
         at Ocelot.Multiplexer.MultiplexingMiddleware.Invoke(HttpContext httpContext)
         at Ocelot.DownstreamRouteFinder.Middleware.DownstreamRouteFinderMiddleware.Invoke(HttpContext httpContext)
         at Ocelot.Responder.Middleware.ResponderMiddleware.Invoke(HttpContext httpContext)
         at Ocelot.Errors.Middleware.ExceptionHandlerMiddleware.Invoke(HttpContext httpContext) RequestId: 0HN4SP4CA0UMM:00000001, exception: System.Text.RegularExpressions.RegexParseException: Invalid pattern '\b*path=debug)\b' at offset 14. Too many )'s.
         at System.Text.RegularExpressions.RegexParser.ScanRegex()
         at System.Text.RegularExpressions.RegexParser.Parse(String pattern, RegexOptions options, CultureInfo culture)
         at System.Text.RegularExpressions.Regex..ctor(String pattern, CultureInfo culture)
         at Ocelot.DownstreamUrlCreator.Middleware.DownstreamUrlCreatorMiddleware.RemoveQueryStringParametersThatHaveBeenUsedInTemplate(DownstreamRequest downstreamRequest, List`1 templatePlaceholderNameAndValues)
         at Ocelot.DownstreamUrlCreator.Middleware.DownstreamUrlCreatorMiddleware.Invoke(HttpContext httpContext)
         at Ocelot.LoadBalancer.Middleware.LoadBalancingMiddleware.Invoke(HttpContext httpContext)
         at Ocelot.DownstreamPathManipulation.Middleware.ClaimsToDownstreamPathMiddleware.Invoke(HttpContext httpContext)
         at Ocelot.QueryStrings.Middleware.ClaimsToQueryStringMiddleware.Invoke(HttpContext httpContext)
         at Ocelot.Headers.Middleware.ClaimsToHeadersMiddleware.Invoke(HttpContext httpContext)
         at Ocelot.Authorization.Middleware.AuthorizationMiddleware.Invoke(HttpContext httpContext)
         at Ocelot.Claims.Middleware.ClaimsToClaimsMiddleware.Invoke(HttpContext httpContext)
         at Ocelot.Authentication.Middleware.AuthenticationMiddleware.Invoke(HttpContext httpContext)
         at Ocelot.RequestId.Middleware.RequestIdMiddleware.Invoke(HttpContext httpContext)
         at Ocelot.RateLimit.Middleware.ClientRateLimitMiddleware.Invoke(HttpContext httpContext)
         at Ocelot.Request.Middleware.DownstreamRequestInitialiserMiddleware.Invoke(HttpContext httpContext)
         at Ocelot.Headers.Middleware.HttpHeadersTransformationMiddleware.Invoke(HttpContext httpContext)
         at Ocelot.Security.Middleware.SecurityMiddleware.Invoke(HttpContext httpContext)
         at Ocelot.Multiplexer.MultiplexingMiddleware.Fire(HttpContext httpContext, RequestDelegate next)
         at Ocelot.Multiplexer.MultiplexingMiddleware.Invoke(HttpContext httpContext)
         at Ocelot.DownstreamRouteFinder.Middleware.DownstreamRouteFinderMiddleware.Invoke(HttpContext httpContext)
         at Ocelot.Responder.Middleware.ResponderMiddleware.Invoke(HttpContext httpContext)
         at Ocelot.Errors.Middleware.ExceptionHandlerMiddleware.Invoke(HttpContext httpContext)
      System.Text.RegularExpressions.RegexParseException: Invalid pattern '\b*path=debug)\b' at offset 14. Too many )'s.
         at System.Text.RegularExpressions.RegexParser.ScanRegex()
         at System.Text.RegularExpressions.RegexParser.Parse(String pattern, RegexOptions options, CultureInfo culture)
         at System.Text.RegularExpressions.Regex..ctor(String pattern, CultureInfo culture)
         at Ocelot.DownstreamUrlCreator.Middleware.DownstreamUrlCreatorMiddleware.RemoveQueryStringParametersThatHaveBeenUsedInTemplate(DownstreamRequest downstreamRequest, List`1 templatePlaceholderNameAndValues)
         at Ocelot.DownstreamUrlCreator.Middleware.DownstreamUrlCreatorMiddleware.Invoke(HttpContext httpContext)
         at Ocelot.LoadBalancer.Middleware.LoadBalancingMiddleware.Invoke(HttpContext httpContext)
         at Ocelot.DownstreamPathManipulation.Middleware.ClaimsToDownstreamPathMiddleware.Invoke(HttpContext httpContext)
         at Ocelot.QueryStrings.Middleware.ClaimsToQueryStringMiddleware.Invoke(HttpContext httpContext)
         at Ocelot.Headers.Middleware.ClaimsToHeadersMiddleware.Invoke(HttpContext httpContext)
         at Ocelot.Authorization.Middleware.AuthorizationMiddleware.Invoke(HttpContext httpContext)
         at Ocelot.Claims.Middleware.ClaimsToClaimsMiddleware.Invoke(HttpContext httpContext)
         at Ocelot.Authentication.Middleware.AuthenticationMiddleware.Invoke(HttpContext httpContext)
         at Ocelot.RequestId.Middleware.RequestIdMiddleware.Invoke(HttpContext httpContext)
         at Ocelot.RateLimit.Middleware.ClientRateLimitMiddleware.Invoke(HttpContext httpContext)
         at Ocelot.Request.Middleware.DownstreamRequestInitialiserMiddleware.Invoke(HttpContext httpContext)
         at Ocelot.Headers.Middleware.HttpHeadersTransformationMiddleware.Invoke(HttpContext httpContext)
         at Ocelot.Security.Middleware.SecurityMiddleware.Invoke(HttpContext httpContext)
         at Ocelot.Multiplexer.MultiplexingMiddleware.Fire(HttpContext httpContext, RequestDelegate next)
         at Ocelot.Multiplexer.MultiplexingMiddleware.Invoke(HttpContext httpContext)
         at Ocelot.DownstreamRouteFinder.Middleware.DownstreamRouteFinderMiddleware.Invoke(HttpContext httpContext)
         at Ocelot.Responder.Middleware.ResponderMiddleware.Invoke(HttpContext httpContext)
         at Ocelot.Errors.Middleware.ExceptionHandlerMiddleware.Invoke(HttpContext httpContext)
`

## Steps to Reproduce the Problem

  1. Simple Route configuration
      {
      "DownstreamPathTemplate": "/api/{*path}",
      "DownstreamScheme": "http",
      "DownstreamHostAndPorts": [{...}],
      "UpstreamPathTemplate": "/api/{*path}",
      "UpstreamHttpMethod": [ "Get" ]
    }
  1.  `GET /api/debug)`
  1. Or with urlencoded parameter: `GET /api/debug%29`

## Specifications

  - Version: 23.2.2
  - Platform: Dotnet 8

### PR DESCRIPTION
**Pull request by int0x81**
## Fixes #2116 
- This PR introduces unit tests as well as a fix for issue: #2116

## Bug
When the downstream URL was created dynamically by a path like `api/{path}` **and** the URL contained malicious characters, the request might result in a 500 response from the server. This happened because malicious characters were used for **dynamic `Regex` creation**.

## Solution
All parameters that are used for template replacements are now `Regex`-escaped before they are used in the `Regex` constructor.

### CODE REVIEW

**Comment by raman-m** [comment]
Hello Finn!
Welcome to the world of Ocelot! 🐅
Thank you for creating the PR!

Could we please scan the codebase and other `Regex` constructors for potentially similar issues?

File: src/Ocelot/DownstreamUrlCreator/Middleware/DownstreamUrlCreatorMiddleware.cs [hunk 1]
```diff
@@ -165,5 +166,10 @@ private static bool ServiceFabricRequest(IInternalConfiguration config, Downstre
         {
             return config.ServiceProviderConfiguration.Type?.ToLower() == "servicefabric" && downstreamRoute.UseServiceDiscovery;
         }
+
+        /// <summary>
+        /// Takes in a string value and transforms it, so it can be later used in a Regex constructor.
+        /// </summary>
+        private static string BuildRegexSafeValue(string input) => Regex.Escape(input);
```
Comment (raman-m) [inline src/Ocelot/DownstreamUrlCreator/Middleware/DownstreamUrlCreatorMiddleware.cs:173]: I find little purpose in this static helper. It takes a single parameter and merely delegates to the `Regex` helper.

File: test/Ocelot.UnitTests/DownstreamUrlCreator/DownstreamUrlCreatorMiddlewareTests.cs [hunk 2]
```diff
@@ -611,6 +611,43 @@ public void Should_map_when_query_parameters_has_same_names_with_placeholder()
...
+        GivenTheDownstreamRequestUriIs($"http://localhost:5000/{urlPath}");
+        GivenTheServiceProviderConfigIs(new ServiceProviderConfigurationBuilder().Build());
+        GivenTheUrlReplacerWillReturn($"routed/{urlPath}");
+
+        // Act
+        WhenICallTheMiddleware();
+
+        // Assert
+        ThenTheDownstreamRequestUriIs($"http://localhost:5000/routed/{urlPath}");
+        Assert.True(_httpContext.Response.StatusCode < 500);
```
Comment (raman-m) [inline test/Ocelot.UnitTests/DownstreamUrlCreator/DownstreamUrlCreatorMiddlewareTests.cs:648]: It's peculiar... A strict assertion is required in this case, for example `HttpStatusCode.OK`

Comment (raman-m) [reply test/Ocelot.UnitTests/DownstreamUrlCreator/DownstreamUrlCreatorMiddlewareTests.cs:648]: An acceptance test is also necessary!

Comment (int0x81) [reply test/Ocelot.UnitTests/DownstreamUrlCreator/DownstreamUrlCreatorMiddlewareTests.cs]: Hi Raman, I will create an additional Acceptance test👍

Comment (raman-m) [reply test/Ocelot.UnitTests/DownstreamUrlCreator/DownstreamUrlCreatorMiddlewareTests.cs]: Your **complete code** will undoubtedly be a valuable addition. However, please be aware that we are currently focusing on the hot🔥[v23.3 Hotfixes](https://github.com/ThreeMammals/Ocelot/milestone/8) milestone, so we would greatly appreciate your prompt development of tests and submission of commits. Also, note that we follow Pair Programming practices to accelerate delivery, allowing both you and other code reviewers to commit.

Comment (int0x81) [reply test/Ocelot.UnitTests/DownstreamUrlCreator/DownstreamUrlCreatorMiddlewareTests.cs]: I created an Acceptance Test that helped me reproduce and validate the bug successfully.

File: test/Ocelot.AcceptanceTests/PathToDownstreamUrlTests.cs [hunk 3]
```diff
@@ -0,0 +1,96 @@
+﻿using IdentityServer4.AccessTokenValidation;
+using Microsoft.AspNetCore.Builder;
+using Microsoft.AspNetCore.Hosting;
+using Ocelot.Configuration.File;
+
+namespace Ocelot.AcceptanceTests;
+
+public class PathToDownstreamUrlTests : IDisposable
```
Comment (raman-m) [inline test/Ocelot.AcceptanceTests/PathToDownstreamUrlTests.cs:8]: Can we move the test to more appropriate class which is `RoutingTests` in namespace `Ocelot.AcceptanceTests.Routing`?
We keep all routing vs path tests in this class.

File: test/Ocelot.AcceptanceTests/PathToDownstreamUrlTests.cs [hunk 4]
```diff
@@ -0,0 +1,96 @@
...
+        this.Given(x => x.GivenThereIsAServiceRunningOn($"http://localhost:{port}", 200))
+                .And(x => _steps.GivenThereIsAConfiguration(configuration))
+                .And(x => _steps.GivenOcelotIsRunning(_options, "Test"))
+                .When(x => _steps.WhenIGetUrlOnTheApiGateway("/api/debug("))
+                .Then(x => _steps.ThenTheStatusCodeShouldBe(HttpStatusCode.OK))
+                .And(x => ThenTheDownstreamPathIs("/routed/api/debug("))
+                .BDDfy();
+    }
+
+    private void GivenThereIsAServiceRunningOn(string url, int statusCode)
```
Comment (raman-m) [inline test/Ocelot.AcceptanceTests/PathToDownstreamUrlTests.cs:65]: This helper is redundant because you can reuse [_downstreamPath](https://github.com/ThreeMammals/Ocelot/blob/develop/test/Ocelot.AcceptanceTests/Routing/RoutingTests.cs#L10) class member in the `RoutingTests` class

**Review by raman-m — CHANGES_REQUESTED** [review]
Please move the test to https://github.com/ThreeMammals/Ocelot/blob/develop/test/Ocelot.AcceptanceTests/Routing/RoutingTests.cs

File: test/Ocelot.UnitTests/DownstreamUrlCreator/DownstreamUrlCreatorMiddlewareTests.cs [hunk 5]
```diff
@@ -611,6 +611,43 @@ public void Should_map_when_query_parameters_has_same_names_with_placeholder()
         ThenTheQueryStringIs($"?roleId={roleid}&{everything}");
     }
 
+    [Theory]
+    [Trait("Bug", "2116")]
+    [InlineData("api/debug()")] // no query
+    [InlineData("api/debug%28%29")] // debug()
```
Comment (raman-m) [inline test/Ocelot.UnitTests/DownstreamUrlCreator/DownstreamUrlCreatorMiddlewareTests.cs:617]: Hello @ggnaegi,
I would like to delay my approval until we have made a decision on the additional test case:
```suggestion
    [InlineData("api/debug()")] // no query
    [InlineData("api/debug%28%29")] // encoded debug()
    [InlineData("api/debug()?special=(\\,*,+,?,|,{,},[,],(,),^,$,.,#, ,)&2=(2)&3=[3]&4={4}")] // with query
```
The third test has revealed issues within the middleware logic, indicating that this test case is likely to fail. The `MergeQueryStringsWithoutDuplicateValues` method struggles to handle URLs containing query strings with special characters, such as `Regex` patterns and reserved URL specification characters. This issue became apparent in release 20.0.0 during the refactoring of the `MergeQueryStringsWithoutDuplicateValues` method, which aimed to integrate existing and new logic (for example OData filters in query parameters). Regrettably, the method fails to process special characters in parameter values.

Would you recommend addressing the design bottleneck within this bug fix, or would creating a new TODO task be a better approach to ensure the current release proceeds without delay?

Comment (ggnaegi) [reply test/Ocelot.UnitTests/DownstreamUrlCreator/DownstreamUrlCreatorMiddlewareTests.cs:617]: @raman-m the whole thing is a mess, @int0x81 who is new to ocelot said straight away that the whole implementation could be optimized. For now, I would suggest merging the current changes, refactorings are out of scope in my opinion. @int0x81 would be happy to create a follow up issue and PR.

**Review by raman-m — APPROVED** [review]
It looks good to me!
I've marked the message as the follow-up [TODO task](https://github.com/ThreeMammals/Ocelot/pull/2150#discussion_r1767004179).
@ggnaegi, if we're done, please press the magic **Squash** button 🪄.

**Comment by ggnaegi** [comment]
Squash and Merge it is!
