### PR TITLE
#1228 #1235 #1247 Overloaded AddOcelot method for dynamic FileConfiguration construction

### LINKED ISSUE #1228: Dynamically set/add Configuration for rate limiting
## Expected Behavior / New Feature
For every re-route, we need to add  
 "RateLimitOptions": {
        "ClientWhitelist": [],
        "EnableRateLimiting": true,
        "Period": "10s",
        "PeriodTimespan": 3,
        "Limit": 1
      }

Now, if I want to fetch this configuration from a database or any file at run time and assign it for specific routes

For eg"
Startup.cs
```
ConfigureServices()
{
services.AddOcelot().AddRateLimitingConfiguration( Datatable or file )
}

```

### LINKED ISSUE #1235: Extend AddOcelot to EnumerateFiles in subfdirectories
## Expected Behavior / New Feature
Search ocelot.json files in given directory and all subdirectories.

## Actual Behavior / Motivation for New Feature
Currently AddOcelot only enumerates files in top directory only.

 I would like to add even more structure to my ocelot files and keep them as small and maintainable as possible.

## Steps to Reproduce the Problem
Only one piece of code would need to be changed in:
**Ocelot.DependencyInjection.ConfigurationBuilderExtensions.AddOcelot(this IConfigurationBuilder builder, string folder, IWebHostEnvironment env)** 
starting at line **37**:

var files = new DirectoryInfo(folder)
                **.EnumerateFiles("*", SearchOption.AllDirectories)**
                .Where(fi => reg.IsMatch(fi.Name) && (fi.Name != excludeConfigName))
                .ToList();

## Specifications
  - Version: 14.0.9

### LINKED ISSUE #1247: Upgrade to 3.1 produces empty ocelot.json
## Expected Behavior

In .NET Core 2.2, inside the _Startup_ constructor we have the following configuration:

``` csharp
var builder = new ConfigurationBuilder().SetBasePath(env.ContentRootPath);

if (env.IsLocal())
{
  builder.AddJsonFile("appsettings.json", optional: true, reloadOnChange: true);
} else
{
   builder.AddJsonFile($"appsettings.{env.EnvironmentName}.json", optional: true, reloadOnChange: true);
}
builder.AddEnvironmentVariables();

 // Loads corresponding folder -> e.g. Products/Local/*.json
var gateway = System.Environment.GetEnvironmentVariable("ASPNETCORE_GATEWAY");
builder.AddOcelot($"/{gateway}/{env.EnvironmentName}/", env);

Configuration = builder.Build();
Environment = env;
```

In ConfigureServices we use the following line to add Ocelot as a middleware:

``` csharp
services.AddOcelot(Configuration);
```

As you can see, we specify a certain path for merging ocelot files for different environments.

After upgrading to .NET Core 3.1 the only difference is in _Configure_ method: 

``` csharp
app.UseRouting();

app.UseCors("CorsPolicy"); // to remove

app.UseAuthentication();

app.UseEndpoints(endpoints =>
{
    endpoints.MapControllers();
});

app.UseOcelot().Wait();
```

The above snippets should merge all ocelot.*.json files into ocelot.json and _work_ as intended. At least with 2.2 that was the case.

## Actual Behavior
In 3.1, the generated ocelot.json is empty! So every request leads to => **404**

One thing I noticed is in this line: 
``` csharp
builder.AddOcelot(string, env);
```

It used to get the ContentRootPath and add the rest {gateway}/{env.name}. 
Instead, it goes to "C:/" now. I fixed this by adding the ContentRootPath in front, but still the generated routing config is empty.

Produced ocelot.json:

``` json
{"Routes":[],"DynamicRoutes":[],"Aggregates":[],"GlobalConfiguration":{"RequestIdKey":null,"ServiceDiscoveryProvider":{"Scheme":null,"Host":null,"Port":0,"Type":null,"Token":null,"ConfigurationKey":null,"PollingInterval":0,"Namespace":null},"RateLimitOptions":{"ClientIdHeader":"ClientId","QuotaExceededMessage":null,"RateLimitCounterPrefix":"ocelot","DisableRateLimitHeaders":false,"HttpStatusCode":429},"QoSOptions":{"ExceptionsAllowedBeforeBreaking":0,"DurationOfBreak":0,"TimeoutValue":0},"BaseUrl":"http://localhost:56512","LoadBalancerOptions":{"Type":null,"Key":null,"Expiry":0},"DownstreamScheme":null,"HttpHandlerOptions":{"AllowAutoRedirect":false,"UseCookieContainer":false,"UseTracing":false,"UseProxy":true,"MaxConnectionsPerServer":2147483647},"DownstreamHttpVersion":null}}
```

## Specifications

  - Version: Ocelot 16.0.1
  - Platform: .NET Core 3.1

### PR DESCRIPTION
**Pull request by vijay-karavadra**
## Closes #1228 #1235 #1247 
- #1228 
- #1235 
- #1247 

## New Feature
Added an `AddOcelot` overload to load `FileConfiguration` directly from the application, so that all the routes could be made configurable and could be load from anywhere.

## Proposed Changes
  - Added a new overload to the `AddOcelot` in `ConfigurationBuilder` to remove Ocelot file dependency from the application.

### CODE REVIEW

**Comment by vijay-karavadra** [comment]
@TomPallister Please review.

**Comment by raman-m** [comment]
@vijay-karavadra Hi Vijay!
What issue is this PR related to?

Could you write a couple of unit/integration tests for your proposed feature, please?

File: src/Ocelot/DependencyInjection/ConfigurationBuilderExtensions.cs [hunk 1]
```diff
@@ -84,5 +84,20 @@ public static IConfigurationBuilder AddOcelot(this IConfigurationBuilder builder
 
             return builder;
         }
+
+
+        public static IConfigurationBuilder AddOcelot(
+            this IConfigurationBuilder builder, FileConfiguration fileConfiguration, IWebHostEnvironment env)
+        {
+            const string primaryConfigFile = "ocelot.json";
```
Comment (raman-m) [inline src/Ocelot/DependencyInjection/ConfigurationBuilderExtensions.cs:92]: I would recommend to move this string constant declaration to the class level:
```csharp
public static class ConfigurationBuilderExtensions
{
    private const string primaryConfigFile = "ocelot.json";

    // usage on the lines 81 and 92.
}
```

File: src/Ocelot/DependencyInjection/ConfigurationBuilderExtensions.cs [hunk 2]
```diff
@@ -84,5 +84,20 @@ public static IConfigurationBuilder AddOcelot(this IConfigurationBuilder builder
 
             return builder;
```
Comment (raman-m) [inline src/Ocelot/DependencyInjection/ConfigurationBuilderExtensions.cs:85]: You can reuse new defined method (line 89) in the overloaded `AddOcelot` method (line 40) like this:
```csharp
public static IConfigurationBuilder AddOcelot(this IConfigurationBuilder builder, string folder, IWebHostEnvironment env)
{
    // line 78
    return AddOcelot(builder, fileConfiguration, env); // merge block of lines 79-85
}
```

**Review by raman-m — CHANGES_REQUESTED** [review]
Please, fix minor issues!

Also, I would welcome you to write unit and/or integration test(s).

**Comment by vijay-karavadra** [comment]
Hey @raman-m ,

First of all, thanks for the review. I appreciate it.

I had added this overload because I wanted to load ocelot configuration from a third party configuration manager(AWS SSM). So, I was thinking to load them on startup and then seed them into ocelot with this overload.

So, the thing is I'm a little bit busy right now and this has been deprioritized at the moment. But, I still think that this feature makes sense, so I'll try to give some time to it by this or next weekend and will try to complete it.

Thanks!

**Comment by raman-m** [comment]
@vijay-karavadra commented [on Jul 10, 2023](#issuecomment-1629460664)
> I had added this overload because I wanted to load ocelot configuration from a third party configuration manager(AWS SSM). So, I was thinking to load them on startup and then seed them into ocelot with this overload.

OK. New extensions for the `IConfigurationBuilder` interface are welcome! We created the similar extensions for ` IMvcCoreBuilder` interface, see #1655 please. You could get some inspiration from this PR. 

---

>  But, I still think that this feature makes sense, so I'll try to give some time to it by this or next weekend and will try to complete it.

Sure thing, Vijay!

Pay attention that if you introduce new extension-method, it is required to update docs to show how to use your extended functionality. More in #1655 .
Ping me if you need a help!

**Comment by raman-m** [comment]
Is this PR related to some existed issue?

**Comment by raman-m** [comment]
@vijay-karavadra  Hi!
How was your summer?
Are you going to contribute (fix code review issues, write unit tests)?

Pay attention this is production ready project. A number of projects use this gateway.
And the quality of the source code should be high.
For new functionality unit & acceptance tests must be written. But especially for this PR only unit test could be accepted.
It is better to update docs too. Tom can ask to write examples, code snippets in docs.

Are you ready for new code challenges? 😉

**Comment by raman-m** [comment]
@vijay-karavadra commented [on Jul 10](#issuecomment-1629460664):
> I had added this overload because I wanted to load ocelot configuration from a third party configuration manager (AWS SSM). So, I was thinking to load them on startup and then seed them into ocelot with this overload.

Do you have a successful and workable solution now? I meant store file config object in AWS SSM, inject this object during app startup, pass the object to your extension-method...

It seems we have to write some acceptance test(s) to emulate AWS environment, and integrate to Ocelot environment.
But having such solutions from your side, writing an acceptance tests won't be a difficult challenge.

File: src/Ocelot/DependencyInjection/ConfigurationBuilderExtensions.cs (hunk 1 above)
Comment (vijay-karavadra) [reply src/Ocelot/DependencyInjection/ConfigurationBuilderExtensions.cs]: @raman-m Moved PrimaryConfigFile & GlobalConfigFile both at class level. Please review.

File: src/Ocelot/DependencyInjection/ConfigurationBuilderExtensions.cs (hunk 2 above)
Comment (vijay-karavadra) [reply src/Ocelot/DependencyInjection/ConfigurationBuilderExtensions.cs]: @raman-m Reused the new method. Please review.

**Comment by vijay-karavadra** [comment]
Hey @raman-m ,

I had a great summer! I hope you had a great one too and also you are doing well.

I was somewhat busy in some projects, thanks for bringing me back to this. I appreciate your patience and I grasp the gravity and significance of this project.

I added the code review changes as per suggestions, please review. Also I started working on unit and acceptance tests and will push once done.

**Comment by raman-m** [comment]
> @vijay-karavadra commented [on Sep 8](#issuecomment-1711167323)

Perfect! Added code is fine. 2 code review issues have been resolved.
Waiting for the next commits with tests...

**Comment by vijay-karavadra** [comment]
@raman-m 

I have recently incorporated unit tests, and I would greatly appreciate your review of them. In regard to the acceptance tests, I've conducted a thorough examination of the existing ones. It appears that the acceptance tests have been designed under the presumption that the configuration builder functions seamlessly. To clarify, the configuration builder is not included as a component of the acceptance tests. Nevertheless, I am open to your insights and suggestions, so please do inform me if there are any specific tests you believe should be integrated into our suite of unit and acceptance tests.

**Comment by raman-m** [comment]
> @vijay-karavadra commented [on Sep 8](#issuecomment-1711466168)

Yes, for configuration extensions we **do have** unit tests only.
Thanks for covering your method by new unit tests and updating others!

**Review by raman-m — APPROVED** [review]
One more approval is required.

**Review by RaynaldM — APPROVED** [review]

**Review by RaynaldM — APPROVED** [review]

**Comment by vijay-karavadra** [comment]
Thanks @raman-m . It was a very good experience in working in this library. Feel free to assign me any issues in this library where the help is needed. I'd be happy to help!

**Comment by raman-m** [comment]
> @vijay-karavadra commented [on Sep 23](#issuecomment-1732336952)

You are welcome!
Much help is needed in [backlog](../issues). There are a lot of issues! And you are free to assign any of them 😉 
I would suggest to [assign a bug](../issues?q=is%3Aopen+is%3Aissue+label%3Abug) to yourself, because bugs have highest priority. Skip bugs which have attacked PR, for sure. So, take any bug without a PR. And ping me a message in the bug's thread, and you'll be assigned.
