### PR TITLE
#1375 #1237 #925 #920 Fix DownstreamRoute DangerousAcceptAnyServerCertificateValidator

### LINKED ISSUE #1375: "DangerousAcceptAnyServerCertificateValidator=true" when "DownstreamScheme=wss" does not work
```json
{
      "ServiceName": "MessageCenter", 
      "UseServiceDiscovery": true,
      "UpstreamPathTemplate": "/Hub/{catchAll}",
      "UpstreamHttpMethod": [ "GET", "POST", "DELETE", "PUT" ],
      "DownstreamScheme": "wss",
      "DownstreamPathTemplate": "/{catchAll}",
      "LoadBalancerOptions": {
        "Type": "LeastConnection"
      },
      "DangerousAcceptAnyServerCertificateValidator": true
    }
```

### PR DESCRIPTION
**Pull request by zqlovejyc**
## Fixes #1375 #1237 #925 #920 
- #1375 
- #1237 
- #925 
- #920

### CODE REVIEW

**Review by evgslyusar — APPROVED** [review]

**Comment by raman-m** [comment]
Hi zhangq!
Thanks for your interest in Ocelot!

Could you [Sync fork](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork) please? So, your **master** branch was outdated!
And I don't see **develop** branch... It seems the fork is very old.

**Comment by raman-m** [comment]
The [feature branch](/zqlovejyc/Ocelot/tree/master) has been rebased onto [ThreeMammals:develop](../tree/develop)!
Welcome to code review!

File: src/Ocelot/LoadBalancer/LoadBalancers/RoundRobin.cs [hunk 1]
```diff
@@ -25,6 +25,12 @@ public RoundRobin(Func<Task<List<Service>>> services)
         public async Task<Response<ServiceHostAndPort>> Lease(HttpContext httpContext)
         {
             var services = await _services();
```
Comment (RaynaldM) [inline src/Ocelot/LoadBalancer/LoadBalancers/RoundRobin.cs:27]:
```suggestion
            var servicesList = await _services();
```

File: src/Ocelot/LoadBalancer/LoadBalancers/RoundRobin.cs [hunk 2]
```diff
@@ -25,6 +25,12 @@ public RoundRobin(Func<Task<List<Service>>> services)
...
+
+            if (services == null || services.Count == 0)
+            {
+                return new ErrorResponse<ServiceHostAndPort>(new ServicesAreEmptyError($"There were no services in {nameof(RoundRobin)} during {nameof(Lease)} operation."));
+            }
+
             lock (_lock)
```
Comment (RaynaldM) [inline src/Ocelot/LoadBalancer/LoadBalancers/RoundRobin.cs:34]: use semaphorSlim in async context

File: src/Ocelot/WebSockets/Middleware/WebSocketsProxyMiddleware.cs [hunk 3]
```diff
@@ -119,11 +127,10 @@ private static async Task Proxy(HttpContext context, string serverEndpoint)
...
             var destinationUri = new Uri(serverEndpoint);
             await client.ConnectAsync(destinationUri, context.RequestAborted);
-            using (var server = await context.WebSockets.AcceptWebSocketAsync(client.SubProtocol))
-            {
-                var bufferSize = DefaultWebSocketBufferSize;
-                await Task.WhenAll(PumpWebSocket(client, server, bufferSize, context.RequestAborted), PumpWebSocket(server, client, bufferSize, context.RequestAborted));
-            }
+
+            using var server = await context.WebSockets.AcceptWebSocketAsync(client.SubProtocol);
+            var bufferSize = DefaultWebSocketBufferSize;
```
Comment (RaynaldM) [inline src/Ocelot/WebSockets/Middleware/WebSocketsProxyMiddleware.cs:132]: bufferSize is useless

File: src/Ocelot/WebSockets/Middleware/WebSocketsProxyMiddleware.cs [hunk 4]
```diff
@@ -119,11 +127,10 @@ private static async Task Proxy(HttpContext context, string serverEndpoint)
 
             var destinationUri = new Uri(serverEndpoint);
             await client.ConnectAsync(destinationUri, context.RequestAborted);
-            using (var server = await context.WebSockets.AcceptWebSocketAsync(client.SubProtocol))
-            {
-                var bufferSize = DefaultWebSocketBufferSize;
-                await Task.WhenAll(PumpWebSocket(client, server, bufferSize, context.RequestAborted), PumpWebSocket(server, client, bufferSize, context.RequestAborted));
-            }
+
+            using var server = await context.WebSockets.AcceptWebSocketAsync(client.SubProtocol);
```
Comment (RaynaldM) [inline src/Ocelot/WebSockets/Middleware/WebSocketsProxyMiddleware.cs:131]: Personally, I prefer usings with braces, I find that we see more clearly where we free up the resources.
It is just a personal opinion

Comment (raman-m) [reply src/Ocelot/WebSockets/Middleware/WebSocketsProxyMiddleware.cs:131]: It is freed up on line 134, at the end of local scope.
So the using-block (lines 131-133) locates at the end.

**Comment by raman-m** [comment]
@zqlovejyc Hey zhangq!
Sorry, but your PR is very important! 😜 
The community is waiting for this to be released!

**Review by RaynaldM — APPROVED** [review]

File: src/Ocelot/WebSockets/Middleware/WebSocketsProxyMiddleware.cs (hunk 3 above)
Comment (raman-m) [reply src/Ocelot/WebSockets/Middleware/WebSocketsProxyMiddleware.cs]: ✔️ Fixed in commit https://github.com/ThreeMammals/Ocelot/pull/1377/commits/e48e04aaa63f7ab00bb7d3356b3687a3f8ceb14c

File: src/Ocelot/WebSockets/Middleware/WebSocketsProxyMiddleware.cs (hunk 4 above)
Comment (raman-m) [reply src/Ocelot/WebSockets/Middleware/WebSocketsProxyMiddleware.cs]: ✔️ Fixed in commit https://github.com/ThreeMammals/Ocelot/pull/1377/commits/e48e04aaa63f7ab00bb7d3356b3687a3f8ceb14c

**Review by RaynaldM — APPROVED** [review]

**Comment by raman-m** [comment]
@RaynaldM Please, review, carefully! 😉 
I've added unit tests for **WebSockets** feature because there were no unit testing class at all.
And, hope for your approval...

**Review by RaynaldM — APPROVED** [review]

**Comment by raman-m** [comment]
@RaynaldM Everything fine in testing? 😄 
Anyway, thanks for approval! 😍

File: src/Ocelot/WebSockets/WebSocketsProxyMiddlewareExtensions.cs
Comment (raman-m) [inline src/Ocelot/WebSockets/WebSocketsProxyMiddlewareExtensions.cs:1]: The `UseWebSocketsProxyMiddleware` method enables custom `WebSocketsProxyMiddleware` in the pipeline.
But there is no usage of native [WebSocketMiddleware](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.websockets.websocketmiddleware?view=aspnetcore-7.0) class which is industry standard. But instead of standard framework middleware a custom `WebSocketsProxyMiddleware` class was written with custom `Invoke` method. This is design issue...

File: src/Ocelot/WebSockets/WebSocketsProxyMiddleware.cs [hunk 5]
```diff
@@ -1,26 +1,33 @@
...
 using Microsoft.AspNetCore.Http;
+using Ocelot.Configuration;
 using Ocelot.Logging;
 using Ocelot.Middleware;
 using System.Net.WebSockets;
 
-namespace Ocelot.WebSockets.Middleware
+namespace Ocelot.WebSockets
 {
     public class WebSocketsProxyMiddleware : OcelotMiddleware
```
Comment (raman-m) [inline src/Ocelot/WebSockets/WebSocketsProxyMiddleware.cs:13]: - This class should be removed at all in favor of [WebSocketMiddleware](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.websockets.websocketmiddleware?view=aspnetcore-7.0) by Microsoft .NET team.
- This class should be redesigned based on [WebSocketMiddleware](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.websockets.websocketmiddleware?view=aspnetcore-7.0) by Microsoft .NET team.

**Comment by RaynaldM** [comment]
@raman-m When it's urgent, I just read the code and "judge" the form, and a little less the content. :)

**Review by raman-m — APPROVED** [review]
Follow up issue should be created.

**Comment by raman-m** [comment]
>@raman-m approved these changes [on Sep 28](#pullrequestreview-1649078874)

@RaynaldM  FYI
But I'm going to merge...
