### PR TITLE
#2039 Buffer request body and copy the body to downstreams during multiplexing

### LINKED ISSUE #2039: Body cannot be forwarded twice on Aggregator
## Expected Behavior / New Feature
Aggregation cannot currently forward the body of the upstream to several downstreams. This is mentioned in :

https://github.com/ThreeMammals/Ocelot/blob/7c26c073dc02ec7e430d43428ad6906da484cd50/src/Ocelot/Multiplexer/MultiplexingMiddleware.cs#L218

## Actual Behavior / Motivation for New Feature
The error is not really explicit right now, it's a hidden message. The first downstream correctly reads the body and returns the expected result, but the second request has the following error:
``` 
Error connecting to downstream service, exception: System.Net.Http.HttpRequestException: An error occurred while sending the request.
 ---> System.InvalidOperationException: Sent 0 request content bytes, but Content-Length promised xxx.
   at Ocelot.Request.Mapper.StreamHttpContent.CopyAsync(Stream input, Stream output, Int64 announcedContentLength, Boolean autoFlush, CancellationToken cancellation) 
```

This obviously comes from the fact that the body was already read and is not.

I feel this is a reasonable request to be able to forward a body to multiple downstreams.

## Steps to Reproduce the Problem

  1. Define two routes with requests having a body (GET requests for me)
  2. Define an aggregation of these two
  3. Call the aggregation

## Specifications
Aggregators are said not to be able to manage POST requests, but they mainly can't manage bodies. The aggregation just forwards the stream of the body to the following requests.

Still, I got it to work but this leads to major discussions and impactful choices.

## Fix
I created a basic method (which should be rewritten properly) to clone the body
```csharp
    protected static async Task<MemoryStream> CloneBodyAsync(Stream body)
    {
        var memoryStream = new MemoryStream();
        await body.CopyToAsync(memoryStream);
        body.Position = 0;
        memoryStream.Position = 0;
        return memoryStream;
    }
```
Which can be used in the `CreateThreadContextAsync` (must be set Async) that way:
```csharp
    private static async Task<HttpContext> CreateThreadContextAsync(HttpContext source)
    {
        var from = source.Request;
        var bodyCopy = await CloneBodyAsync(from.Body);
        var target = new DefaultHttpContext
        {
            Request =
            {
                Body = bodyCopy,
…
```
The fix was pretty straightforward to integrate, even when switching to Async methods because we have an asynchronous context just before.

However, it is important to note that being able to set back the position of the stream body at the beginning (`body.Position = 0;`) is not supported by default.
I had to enable buffering to be able to do this.
Example code:
```C#
app.Use(
    async (context, next) =>
    {
        context.Request.EnableBuffering(); // necessary for aggregation body copy
        await next();
    }
);
```
ASP Net also doesn't allow synchronous operations for this, which is why it is heavily recommended to switch to async methods as I did.

## Discussion
The way I fixed it locally is definitely a choice and should be carefully considered. This requires to enable buffering of the body (pretty obvious if we want to use it multiple times). That means Ocelot has to buffer the requests, which could be potentially impactful on performances.

I fixed it in a very trivial way, but we could actually also buffer manually by loading the body into a first memory stream before doing the copy for each downstream. That way we are not reliant on enabling the buffering for all the requests, simply on complex aggregations that requires it.

I feel this is the main reason the POST method is not available for aggregations, and I think this could be a major improvement for Ocelot if done right. Supporting the forwarding of a body to multiple streams is really useful feature.
I know I stumped on this limitation by doing a borderline thing using body with GET (although I'll die on the hill that the spec does not forbid it), but I think it opens a really meaningful discussion on a key feature.

Another possibility would be to set back the Stream position at 0 after the copy in the mapper when available (and leave the user the responsibility to enable buffering) but I think it's a less elegant solution. (https://github.com/ThreeMammals/Ocelot/blob/develop/src/Ocelot/Request/Mapper/StreamHttpContent.cs)

On a side-note, to fix it locally I had to copy a lot of Ocelot code — I think most private methods I encountered could just be protected / virtual. This would help customizing the behavior of some components.

I'm more than willing to work on it if necessary, but I feel this is a key discussion to validate with the maintainers before working on it as it has major implications.

Feel free to comment on thoughts, ideas or anything, I'm completely open to criticism and discussions.

  - Version: 23.2.2
  - Platform: .NET 8
  - Subsystem: Aggregation

### PR DESCRIPTION
**Pull request by PaulARoy**
## Closes #2039 
- #2039 

Buffers the body of the request when multiplexing multiple routes and copy the buffered body to the downstreams.

I took consideration of all your feedbacks from the previous PR, don't hesitate to tell me if something's off, either in the code or in the process.

I looked at the benchmark tests but I'm not sure on how to integrate this correctly.

## Proposed Changes

  - Smartly enables ASP.NET buffering for body copy
  - Copy the buffer to the downstream requests through a `MemoryStream`
  - Fixes broken tests due to `CreateThreadContext` name and parameter changes
  - Unit tests on `CloneRequestBodyAsync` (called n times when n > 1, not called for 1)
  - Acceptance test of body copy for multiple services

### CODE REVIEW

File: src/Ocelot/Multiplexer/MultiplexingMiddleware.cs [hunk 1]
```diff
@@ -255,5 +255,27 @@ protected virtual Task MapAsync(HttpContext httpContext, Route route, List<HttpC
 
         var aggregator = _factory.Get(route);
         return aggregator.Aggregate(route, httpContext, contexts);
+    }
+
+    protected virtual async Task<Stream> CopyBufferToTargetRequestAsync(HttpContext source)
+    {
+        source.Request.EnableBuffering();
```
Comment (PaulARoy) [inline src/Ocelot/Multiplexer/MultiplexingMiddleware.cs:262]: This `EnableBuffering()` extension method comes from the AspNet framework: https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.http.httprequestrewindextensions.enablebuffering?view=aspnetcore-8.0

This seems to be the recommended way to enable native capabilities: https://devblogs.microsoft.com/dotnet/re-reading-asp-net-core-request-bodies-with-enablebuffering/

Feel free to discuss this solution here, I think it's pretty elegant.

**Comment by raman-m** [comment]
Paul, thanks for re-creation the PR!

>I looked at the benchmark tests but I'm not sure on how to integrate this correctly.

Benchmarks testing project is here: [Ocelot.Benchmarks](https://github.com/PaulARoy/Ocelot/tree/feat/multiplexing-body-copy/test/Ocelot.Benchmarks)
So, as I said it is not required, but let @ggnaegi to decide on updating benchmarks. But he is on sick leave now...

File: src/Ocelot/Multiplexer/MultiplexingMiddleware.cs (hunk 1 above)
Comment (raman-m) [reply src/Ocelot/Multiplexer/MultiplexingMiddleware.cs:262]: We're aware of this fantastic ASP.NET feature 😄. However, as a team, we've opted not to use `HttpClient` and instead utilize the new `HttpMessageInvoker` pooling mechanism to enhance our heavy streaming capabilities.
For multiplexing, we should employ local buffering and replicate the body multiple times into downstreams.

Comment (raman-m) [reply src/Ocelot/Multiplexer/MultiplexingMiddleware.cs:262]: ### The Q
>Ensure the request [Body](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.http.httprequest.body?view=aspnetcore-8.0#microsoft-aspnetcore-http-httprequest-body) **can be read multiple times**. Normally buffers request bodies in memory; writes requests larger than 30K bytes to disk.

>Ensure the request body can be read multiple times.

This is exactly what we need for multiplexing scenario!

**Comment by raman-m** [comment]
> Would you like to move forward and add benchmark tests afterwards or do you prefer to wait for @ggnaegi? I wish him well!

Let's wait for @ggnaegi plz!

File: src/Ocelot/Multiplexer/MultiplexingMiddleware.cs [hunk 2]
```diff
@@ -255,5 +255,27 @@ protected virtual Task MapAsync(HttpContext httpContext, Route route, List<HttpC
...
         return aggregator.Aggregate(route, httpContext, contexts);
+    }
+
+    protected virtual async Task<Stream> CloneRequestBodyAsync(HttpContext source)
+    {
+        source.Request.EnableBuffering();
+        if (source.Request.Body.Position == 0)
+        {
+            var targetBuffer = new MemoryStream();
+            if (source.Request.ContentLength is not null)
```
Comment (raman-m) [inline src/Ocelot/Multiplexer/MultiplexingMiddleware.cs:266]: What to do if the header is `null`?

File: src/Ocelot/Multiplexer/MultiplexingMiddleware.cs (hunk 1 above)
Comment (PaulARoy) [reply src/Ocelot/Multiplexer/MultiplexingMiddleware.cs:262]: @raman-m thanks for the input, it is enabled on ASP.NET Request, not on HttpClient.

Where would you put the settings for this buffering? I thought it would be preferable to let it by default at first because this would not be enabled for requests that are not multiplexed, thus being a bit confusing.

Also buffering was not part of the story which is why I did the strict minimum buffering. Considering the remark on the previous PR on overstepping the boundaries of the bug, I think it would be best to postpone this (interesting) addition/customization to a more global buffering story.

**Comment by PaulARoy** [comment]
> > Would you like to move forward and add benchmark tests afterwards or do you prefer to wait for @ggnaegi? I wish him well!
> 
> 1. Let's wait for @ggnaegi plz!
> 2. Paul, have you tested the fix in your staging environment or locally? You don't see original `HttpRequestException` from [Body cannot be forwarded twice on Aggregator #2039](https://github.com/ThreeMammals/Ocelot/issues/2039) in logs, right?

Yes, I tested locally first. Also the acceptance test can show quite efficiently the resolution (disabling the copy fails the test with the correct exception).

File: src/Ocelot/Multiplexer/MultiplexingMiddleware.cs [hunk 3]
```diff
@@ -208,14 +208,14 @@ private static void CopyItemsToNewContext(HttpContext target, HttpContext source
...
     /// <returns>The cloned context.</returns>
-    private static HttpContext CreateThreadContext(HttpContext source)
+    protected virtual async Task<HttpContext> CreateThreadContextAsync(HttpContext source)
     {
         var from = source.Request;
         var target = new DefaultHttpContext
         {
             Request =
             {
-                Body = from.Body, // TODO Consider stream cloning for multiple reads
```
[the remark this answers is not in the document]
Comment (PaulARoy) [reply src/Ocelot/Multiplexer/MultiplexingMiddleware.cs:218]: Theoretically, I think so yes. But this is a way, way more complex mechanism and I'm not sure I know how to do this safely.

File: src/Ocelot/Multiplexer/MultiplexingMiddleware.cs [hunk 4]
```diff
@@ -208,14 +208,14 @@ private static void CopyItemsToNewContext(HttpContext target, HttpContext source
...
+                Body = await CloneRequestBodyAsync(source),
```
[the remark this answers is not in the document]
Comment (PaulARoy) [reply src/Ocelot/Multiplexer/MultiplexingMiddleware.cs:218]: `Form` seems to rely on `Body` from what I can see in the aspnet github repository yeah

I'll test this to validate the hypothesis

File: src/Ocelot/Multiplexer/MultiplexingMiddleware.cs (hunk 3 above)
[the remark this answers is not in the document]
Comment (raman-m) [reply src/Ocelot/Multiplexer/MultiplexingMiddleware.cs:218]: It's not an issue, merely a question. Yes, I understand... It's an enhancement that could be worked on in the future.

File: src/Ocelot/Multiplexer/MultiplexingMiddleware.cs (hunk 2 above)
Comment (PaulARoy) [reply src/Ocelot/Multiplexer/MultiplexingMiddleware.cs:266]: I just forward an empty `MemoryStream`.

Default implementation uses a `NullStream`, an internal inaccessible subclass.

**Comment by raman-m** [comment]
> Commit https://github.com/ThreeMammals/Ocelot/pull/2050/commits/8e399b06a463a6d3d417f89361583c1edb7a43b9

@PaulARoy  What is that? 
Don't edit C# code using GitHub editor please! Never! Use Visual Studio only.
Could you remove this commit please? `git reset --hard HEAD~1` should help.

**Comment by PaulARoy** [comment]
> > Commit [8e399b0](https://github.com/ThreeMammals/Ocelot/commit/8e399b06a463a6d3d417f89361583c1edb7a43b9)
> 
> @PaulARoy What is that? Don't edit C# code using GitHub editor please! Never! Use Visual Studio only. Could you remove this commit please? `git reset --hard HEAD~1` should help.

I'm fixing it yeah. I hoped it wasn't that bad – I was wrong.

File: src/Ocelot/Multiplexer/MultiplexingMiddleware.cs (hunk 4 above)
[the remark this answers is not in the document]
Comment (raman-m) [reply src/Ocelot/Multiplexer/MultiplexingMiddleware.cs]: Thank you!

File: src/Ocelot/Multiplexer/MultiplexingMiddleware.cs [hunk 5]
```diff
@@ -215,7 +215,8 @@ protected virtual async Task<HttpContext> CreateThreadContextAsync(HttpContext s
         {
             Request =
             {
-                Body = await CloneRequestBodyAsync(source.Request, source.RequestAborted),
+                Body = await CloneRequestBodyAsync(source.Request, source.RequestAborted),
+                /* Form = from.Form, // TODO */
```
Comment (PaulARoy) [inline src/Ocelot/Multiplexer/MultiplexingMiddleware.cs:219]: No, Form is not required to be mapped here.

Form is just an interpretation of the body and copying the body is enough to make it work.

Acceptance test `Should_return_response_200_with_copied_form_sent_on_multiple_service` validates this point by sending a form, reading it and responding with data from it.

File: src/Ocelot/Multiplexer/MultiplexingMiddleware.cs (hunk 2 above)
Comment (raman-m) [reply src/Ocelot/Multiplexer/MultiplexingMiddleware.cs]: This information should be included in the feature documentation. Developers need to understand that if a request contains a body, the `Content-Length` header must be present; otherwise, the body will be transmitted as `null` or empty.
Do you agree?

File: src/Ocelot/Multiplexer/MultiplexingMiddleware.cs (hunk 5 above)
Comment (raman-m) [reply src/Ocelot/Multiplexer/MultiplexingMiddleware.cs:219]: I'm confused and surprised, but it's all good. If the Form property only reads the Body, there isn't much to discuss, except perhaps for Files. However, since Files is a sub-property of Form, I anticipate there will be no issues, and the files should be forwarded as well, correct?

File: src/Ocelot/Multiplexer/MultiplexingMiddleware.cs (hunk 2 above)
Comment (PaulARoy) [reply src/Ocelot/Multiplexer/MultiplexingMiddleware.cs]: Hum that's actually an HTTP convention `https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Length`

I don't think it's necessary to document this: not sending a content-length header will prevent all http compliant servers not to read the body (in theory).

File: src/Ocelot/Multiplexer/MultiplexingMiddleware.cs (hunk 5 above)
Comment (PaulARoy) [reply src/Ocelot/Multiplexer/MultiplexingMiddleware.cs]: I hesitated to put a file in an acceptance test, but yeah everything relies on the body and how it should be interpreted through the application content type headers. So yes, correct as far as I know.

It was a nice surprise for me too :)

File: src/Ocelot/Multiplexer/MultiplexingMiddleware.cs [hunk 6]
```diff
@@ -255,5 +255,27 @@ protected virtual Task MapAsync(HttpContext httpContext, Route route, List<HttpC
...
+        request.EnableBuffering();
+        if (request.Body.Position == 0)
+        {
+            var targetBuffer = new MemoryStream();
+            if (request.ContentLength is not null)
+            {
+                await request.Body.CopyToAsync(targetBuffer, (int)request.ContentLength, aborted);
+                targetBuffer.Position = 0;
+                request.Body.Position = 0;
+            }
```
Comment (raman-m) [inline src/Ocelot/Multiplexer/MultiplexingMiddleware.cs:271]:
```suggestion
            }
            else
            {
                Logger.LogWarning("Aggregation does not support body copy without Content-Length header!");
            }
```

File: src/Ocelot/Multiplexer/MultiplexingMiddleware.cs [hunk 7]
```diff
@@ -255,5 +255,27 @@ protected virtual Task MapAsync(HttpContext httpContext, Route route, List<HttpC
 
         var aggregator = _factory.Get(route);
         return aggregator.Aggregate(route, httpContext, contexts);
+    }
+
+    protected virtual async Task<Stream> CloneRequestBodyAsync(HttpRequest request, CancellationToken aborted)
+    {
+        request.EnableBuffering();
```
Comment (raman-m) [inline src/Ocelot/Multiplexer/MultiplexingMiddleware.cs:262]: ### Next goal
- [EnableBuffering(HttpRequest, Int32, Int64)](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.http.httprequestrewindextensions.enablebuffering?view=aspnetcore-8.0#microsoft-aspnetcore-http-httprequestrewindextensions-enablebuffering(microsoft-aspnetcore-http-httprequest-system-int32-system-int64))

Let's add `MultiplexingMiddleware` options.

**Given** options for buffering from `FileAggregateRoute` class:
```csharp
public struct BufferingOptions
{
    public int BufferThreshold;
    public long BufferLimit;
}
```
**Then**, let's apply the options:
```suggestion
    protected virtual async Task<Stream> CloneRequestBodyAsync(HttpRequest request, CancellationToken aborted, BufferingOptions options)
    {
        request.EnableBuffering(options.BufferThreshold, options.BufferLimit);
```

**Review by raman-m — CHANGES_REQUESTED** [review]
I think it's necessary to introduce additional buffering options in the middleware.
Please consider my suggestions listed below. 👇

File: src/Ocelot/Multiplexer/MultiplexingMiddleware.cs (hunk 5 above)
Comment (raman-m) [reply src/Ocelot/Multiplexer/MultiplexingMiddleware.cs]: If you are inspired by the file forwarding feature, feel free to update the relevant acceptance test or write a new one.
Thank you!

File: src/Ocelot/Multiplexer/MultiplexingMiddleware.cs (hunk 7 above)
Comment (raman-m) [reply src/Ocelot/Multiplexer/MultiplexingMiddleware.cs:262]: Your [concerns](https://github.com/ThreeMammals/Ocelot/pull/2050#discussion_r1567333939) about introducing this feature have been noted. It is designed to be non-global and solely for multiplexing, as buffering is permitted only for multiplexed requests.

@ggnaegi, could you share your thoughts on this?

File: src/Ocelot/Multiplexer/MultiplexingMiddleware.cs (hunk 6 above)
Comment (PaulARoy) [reply src/Ocelot/Multiplexer/MultiplexingMiddleware.cs:271]: @raman-m it's done

I was on board for a test with a form file, but if it's enough for you I don't think it's necessary.

**Review by raman-m — APPROVED** [review]
LGFM

**Comment by raman-m** [comment]
@ggnaegi @RaynaldM  Hi Team!
Could you take a look at this multiplexer improvement please?

@ggnaegi Gui, you are key reviewer for this PR!

File: src/Ocelot/Multiplexer/MultiplexingMiddleware.cs [hunk 8]
```diff
@@ -255,5 +255,31 @@ protected virtual Task MapAsync(HttpContext httpContext, Route route, List<HttpC
 
         var aggregator = _factory.Get(route);
         return aggregator.Aggregate(route, httpContext, contexts);
+    }
+
+    protected virtual async Task<Stream> CloneRequestBodyAsync(HttpRequest request, CancellationToken aborted)
+    {
+        request.EnableBuffering();
+        if (request.Body.Position == 0)
```
Comment (ggnaegi) [inline src/Ocelot/Multiplexer/MultiplexingMiddleware.cs:263]: why not try to reduce nesting?
```c#
if (request.Body.Position != 0)
{
    return request.Body;
}
```

File: src/Ocelot/Multiplexer/MultiplexingMiddleware.cs [hunk 9]
```diff
@@ -255,5 +255,31 @@ protected virtual Task MapAsync(HttpContext httpContext, Route route, List<HttpC
...
+            else
+            {
+                Logger.LogWarning("Aggregation does not support body copy without Content-Length header!");
+            }
+
+            return targetBuffer;
+        }
+        else
+        {
+            Logger.LogWarning("Ocelot does not support body copy without stream in initial position 0");
```
Comment (ggnaegi) [inline src/Ocelot/Multiplexer/MultiplexingMiddleware.cs:281]: By the way, should this possibly happen? I'm wondering if we should throw here...

**Review by ggnaegi — COMMENTED** [review]
Just 1-2 suggestions but fine otherwise, thanks

File: src/Ocelot/Multiplexer/MultiplexingMiddleware.cs (hunk 9 above)
Comment (raman-m) [reply src/Ocelot/Multiplexer/MultiplexingMiddleware.cs:281]: I'd keep this logged warning just for debugging and proving our solution with the fix is functioning.
So, we have improved version of multiplexer but it is draft from the point of view of Production environment.
Let's keep this `else` branch!

File: src/Ocelot/Multiplexer/MultiplexingMiddleware.cs (hunk 8 above)
Comment (raman-m) [reply src/Ocelot/Multiplexer/MultiplexingMiddleware.cs:263]: Make sense! 😄

File: src/Ocelot/Multiplexer/MultiplexingMiddleware.cs (hunk 9 above)
Comment (PaulARoy) [reply src/Ocelot/Multiplexer/MultiplexingMiddleware.cs:281]: @ggnaegi I don't think it should happen in a normal scenario. The only way I can think of is Ocelot reading partially the body elsewhere by mistake.

However any type of custom middleware could potentially be reading a partial body. I don't see any use case right now but I think it's preferable to log instead of throwing an exception.

File: src/Ocelot/Multiplexer/MultiplexingMiddleware.cs [hunk 10]
```diff
@@ -260,26 +260,24 @@ protected virtual Task MapAsync(HttpContext httpContext, Route route, List<HttpC
...
+            request.Body.Position = 0;
         }
         else
         {
-            Logger.LogWarning("Ocelot does not support body copy without stream in initial position 0");
-            return request.Body;
+            Logger.LogWarning("Aggregation does not support body copy without Content-Length header!");
         }
+
+        return targetBuffer;
```
Comment (raman-m) [inline src/Ocelot/Multiplexer/MultiplexingMiddleware.cs:281]: [1]: https://stackoverflow.com/questions/8116541/what-exactly-is-streambuf-how-do-i-use-it ""
[2]: https://docs.unity3d.com/ScriptReference/AssetBundle.LoadFromStream.html ""
[3]: https://docs.simpleinjector.org/en/latest/lifetimes.html ""

Oops! I forgot to ask... How do we manage the `Stream` object's lifetime here?

File: src/Ocelot/Multiplexer/MultiplexingMiddleware.cs (hunk 8 above)
Comment (raman-m) [reply src/Ocelot/Multiplexer/MultiplexingMiddleware.cs]: Fixed by https://github.com/ThreeMammals/Ocelot/pull/2050/commits/33d1743311d1e8c4bef27a656101ad5537fc11af

File: src/Ocelot/Multiplexer/MultiplexingMiddleware.cs (hunk 9 above)
Comment (raman-m) [reply src/Ocelot/Multiplexer/MultiplexingMiddleware.cs]: Not an issue! Resolving...

File: src/Ocelot/Multiplexer/MultiplexingMiddleware.cs (hunk 10 above)
Comment (PaulARoy) [reply src/Ocelot/Multiplexer/MultiplexingMiddleware.cs:281]: > @PaulARoy Regarding the management of the `Stream` object's lifetime, it appears we are relying solely on Garbage Collector to handle it.

Yes, I assume it's disposed once the request itself is disposed by aspnet

Comment (ggnaegi) [reply src/Ocelot/Multiplexer/MultiplexingMiddleware.cs:281]: I agree with @raman-m, it might be disposed... But since it's a clone of the original HttpContext, I'm not so sure anymore. Maybe we should try to dispose the cloned http contexts afterwards?

File: src/Ocelot/Multiplexer/MultiplexingMiddleware.cs (hunk 8 above)
Comment (ggnaegi) [reply src/Ocelot/Multiplexer/MultiplexingMiddleware.cs]: I'm not a fan of deep nesting because the code can become very difficult to read. If we agree on a specific pattern we should follow it and we tend to use this pattern in later implementations in Ocelot.

File: src/Ocelot/Multiplexer/MultiplexingMiddleware.cs (hunk 10 above)
Comment (raman-m) [reply src/Ocelot/Multiplexer/MultiplexingMiddleware.cs:282]: ### The issue has been resolved in the commit  https://github.com/ThreeMammals/Ocelot/pull/2050/commits/897c3488112d1f029639b27124831cf0556acf0f ✔️

I was wrong! The `RegisterForDispose(IDisposable)` method doesn't require implementation of `IDisposable` interface in the middleware class.

**Review by raman-m — APPROVED** [review]
### Ready for delivery❗

**Comment by raman-m** [comment]
### TODO
- [ ] Next goal is https://github.com/ThreeMammals/Ocelot/pull/2050#discussion_r1568781288
