### PR TITLE
#1700 Create custom Ocelot config file when instantiating steps during parallel execution

### LINKED ISSUE #1700: Unstable test "should reload config on change"
## Expected Behavior
The test `should_reload_config_on_change` doesn't fail in 100% of running

## Actual Behavior / Motivation for New Feature
Currently the test [should_reload_config_on_change](/search?q=repo%3AThreeMammals%2FOcelot%20should_reload_config_on_change&type=code) fails sometimes: in 1/3 or even 1/2 cases.
Possible reason: multithreading for file access when test class tests being run in parallel.

## Steps to Reproduce the Problem
**develop** builds:
- Build [1666](https://circleci.com/gh/ThreeMammals/Ocelot/1666): [Scenario: should reload config on change](https://app.circleci.com/pipelines/github/ThreeMammals/Ocelot/895/workflows/02f04d5f-84ae-40a6-b9cb-bee3835bb65e/jobs/1666?invite=true#step-102-246180_40)
- Build [1592](https://circleci.com/gh/ThreeMammals/Ocelot/1592): [Scenario: should reload config on change](https://app.circleci.com/pipelines/github/ThreeMammals/Ocelot/857/workflows/cf2a0f20-4d12-4515-a251-c00a418f5259/jobs/1592?invite=true#step-102-261494_40)

PR builds:
- Build [1710](https://circleci.com/gh/ThreeMammals/Ocelot/1710): [Scenario: should reload config on change](https://app.circleci.com/pipelines/github/ThreeMammals/Ocelot/917/workflows/a8e23c40-a37a-40e4-b7c8-a071e6ce63f8/jobs/1710?invite=true#step-102-264073_40)
- [etc.](https://app.circleci.com/pipelines/github/ThreeMammals/Ocelot?status=failed)

## Specifications
  - Version: latest
  - Platform: Docker
  - Subsystem: CircleCI

### PR DESCRIPTION
**Pull request by ggnaegi**
# Fixes #1700 
- #1700 

When instantiating steps, creating a custom ocelot config file name. Finally deleting the newly created config file when disposing the `Step` instance.

## Proposed Changes
  - Since, by design, a new instance of `Step` is instantiated for each fact/theory, we need to ensure that the corresponding fact/theory only uses its own ocelot configuration file, without interfering with the configuration files of other facts and theories.

### CODE REVIEW

**Comment by raman-m** [comment]
Wow! Cool!
Let's make 10 PR builds of 10 commits being added to this PR, to get some statistics on stability of this fix.

Just commit a small change of Ocelot core, not tests, and the 2nd commit should be revert commit of previous one.
So, there will be 5 commits and 5 revert-commits.

Good plan?

**Comment by ggnaegi** [comment]
@raman-m no way, that's really funny ;-)

**Comment by ggnaegi** [comment]
@raman-m Ok, a bit better now, 9 out of 10...

**Comment by ggnaegi** [comment]
@raman-m why did you remove xunit.runner.json?

**Comment by raman-m** [comment]
I've reverted commit [9fac778](https://github.com/ThreeMammals/Ocelot/pull/1703/commits/9fac77895de19053092dc8cbe35e4bed34ab2dec)
Sorry!

It seems your solution doesn't work for some reason... That's strange... It should...

Have a rest today! 😉 
We will continue tomorrow, this week...

**Comment by raman-m** [comment]
@ggnaegi [commented](#issuecomment-1732637953)
> why did you remove xunit.runner.json?

Because you've disabled parallel execution for all tests by default.

**Comment by ggnaegi** [comment]
> @ggnaegi [commented](#issuecomment-1732637953)
> 
> > why did you remove xunit.runner.json?
> 
> Because you've disabled parallel execution for all tests by default.

Yeah, I tried...

**Comment by ggnaegi** [comment]
@raman-m 11 out of 12. It's not that bad...

**Comment by ggnaegi** [comment]
@raman-m we might have a solution...

**Comment by raman-m** [comment]
It seems this fix works! 👍 
What was the root cause of failing? I don't think it was random port finder... 🤣

**Comment by raman-m** [comment]
Do you confirm that we can still use parallelization of all tests?

**Comment by ggnaegi** [comment]
> Do you confirm that we can still use parallelization of all tests?

@raman-m Yes, we still have an issue with Open_circuit_should_not_effect_different_route though... That's the test failing at the minute. I can reproduce that on my computer, it fails after 20 minutes.

**Comment by raman-m** [comment]
> Open_circuit_should_not_effect_different_route 

Forget about this test now. It is out of the scope of linked bug-issue.
🆗 I'm going to review...

**Comment by ggnaegi** [comment]
> > Open_circuit_should_not_effect_different_route
> 
> Forget about this test now. It is out of the scope of linked bug-issue. 🆗 I'm going to revi

> It seems this fix works! 👍 What was the root cause of failing? I don't think it was random port finder... 🤣

No it wasn't, but the random port finder code doesn't seem to be thread safe, since the concurrentbag would allow identical values to be stored and the method can be accessed by several threads concurrently

**Review by RaynaldM — DISMISSED** [review]

File: test/Ocelot.AcceptanceTests/ConfigurationReloadTests.cs [hunk 1]
```diff
@@ -88,7 +87,6 @@ public void should_not_trigger_change_token_with_no_change()
         public void Dispose()
         {
             _steps.Dispose();
-            GC.SuppressFinalize(this);
```
Comment (raman-m) [inline test/Ocelot.AcceptanceTests/ConfigurationReloadTests.cs:91]: Why did you remove the GC call? Because there is no descendants of the class, and there is no finalizer?
The `GC.SuppressFinalize` makes sense for subclasses and non-sealed class.
So, why not to mark the class as `sealed`? 😉

File: test/Ocelot.AcceptanceTests/Steps.cs [hunk 2]
```diff
@@ -73,29 +54,41 @@ public class Steps : IDisposable
         private HttpContent _postContent;
         private BearerToken _token;
         public string RequestIdKey = "OcRequestId";
-        private readonly Random _random;
+        private readonly Random _random = new();
+        private readonly string _ocelotConfigFileName = $"{Guid.NewGuid():N}-ocelot.json";
```
Comment (raman-m) [inline test/Ocelot.AcceptanceTests/Steps.cs:58]: I can accept this: `private readonly Random _random = new();`
But I cannot accept on line 58. It contains business logic which is hidden in definition of the `_ocelotConfigFileName` member.
So, it is better to move all initializations to constructor.

File: test/Ocelot.AcceptanceTests/Steps.cs [hunk 3]
```diff
@@ -73,29 +54,41 @@ public class Steps : IDisposable
...
+        private bool _disposedValue;
 
         public async Task ThenConfigShouldBe(FileConfiguration fileConfig)
         {
             var internalConfigCreator = _ocelotServer.Host.Services.GetService<IInternalConfigurationCreator>();
-
             var internalConfigRepo = _ocelotServer.Host.Services.GetService<IInternalConfigurationRepository>();
-            var internalConfig = internalConfigRepo.Get();
 
+            var internalConfig = internalConfigRepo.Get();
```
Comment (raman-m) [inline test/Ocelot.AcceptanceTests/Steps.cs:70]: Was it a root cause? I mean, absence of this call?

File: test/Ocelot.AcceptanceTests/Steps.cs [hunk 4]
```diff
@@ -73,29 +54,41 @@ public class Steps : IDisposable
...
+        {
+            var result = await Wait.WaitFor(timeoutMs).Until(async () =>
+            {
+                var internalConfigCreator = _ocelotServer.Host.Services.GetService<IInternalConfigurationCreator>();
+                var internalConfigRepo = _ocelotServer.Host.Services.GetService<IInternalConfigurationRepository>();
+
+                var internalConfig = internalConfigRepo.Get();
+                var config = await internalConfigCreator.Create(fileConfig);
+
+                return internalConfig.Data.RequestId == config.Data.RequestId;
```
Comment (raman-m) [inline test/Ocelot.AcceptanceTests/Steps.cs:86]: Can we return `Tuple<T1, T2>` to perform `ShouldBe` checking?

File: test/Ocelot.AcceptanceTests/Steps.cs [hunk 5]
```diff
@@ -73,29 +54,41 @@ public class Steps : IDisposable
...
         }
 
+        public async Task ThenConfigShouldBeWithTimeout(FileConfiguration fileConfig, int timeoutMs)
+        {
+            var result = await Wait.WaitFor(timeoutMs).Until(async () =>
+            {
+                var internalConfigCreator = _ocelotServer.Host.Services.GetService<IInternalConfigurationCreator>();
+                var internalConfigRepo = _ocelotServer.Host.Services.GetService<IInternalConfigurationRepository>();
+
+                var internalConfig = internalConfigRepo.Get();
```
Comment (raman-m) [inline test/Ocelot.AcceptanceTests/Steps.cs:83]: Can we extract it to upper context, because it is initial config, right? And initial config can be read outside of waiting task, right?

File: test/Ocelot.AcceptanceTests/Steps.cs [hunk 6]
```diff
@@ -113,7 +106,7 @@ public async Task StartFakeOcelotWithWebSockets()
                     var env = hostingContext.HostingEnvironment;
                     config.AddJsonFile("appsettings.json", optional: true, reloadOnChange: false)
                         .AddJsonFile($"appsettings.{env.EnvironmentName}.json", optional: true, reloadOnChange: false);
-                    config.AddJsonFile("ocelot.json", false, false);
+                    config.AddJsonFile(_ocelotConfigFileName, false, false);
```
Comment (raman-m) [inline test/Ocelot.AcceptanceTests/Steps.cs:109]: Perfect! I love it! 😍 No hardcode anymore!

**Review by raman-m — CHANGES_REQUESTED** [review]
Minor issues, but it is always good to improve the code.

File: test/Ocelot.AcceptanceTests/ConfigurationReloadTests.cs (hunk 1 above)
Comment (ggnaegi) [reply test/Ocelot.AcceptanceTests/ConfigurationReloadTests.cs:91]: ok for sealed

File: test/Ocelot.AcceptanceTests/Steps.cs (hunk 2 above)
Comment (ggnaegi) [reply test/Ocelot.AcceptanceTests/Steps.cs:58]: well...

File: test/Ocelot.AcceptanceTests/Steps.cs (hunk 3 above)
Comment (ggnaegi) [reply test/Ocelot.AcceptanceTests/Steps.cs:70]: It was already in there.

File: test/Ocelot.AcceptanceTests/Steps.cs (hunk 4 above)
Comment (ggnaegi) [reply test/Ocelot.AcceptanceTests/Steps.cs:86]: It needs a refactoring of Until. We could do it later

File: test/Ocelot.AcceptanceTests/Steps.cs (hunk 5 above)
Comment (ggnaegi) [reply test/Ocelot.AcceptanceTests/Steps.cs:83]: Can we just keep it like that for the minute, We could create a new PR later, and implement a better design for Steps.

**Comment by ggnaegi** [comment]
@raman-m imho ok to merge

**Comment by raman-m** [comment]
> [Revert "commit #h5"](1703/commits/6e4b8a42c05207f73ed675db5b0c3468c20057cd) 
> [6e4b8a4](/1703/commits/6e4b8a42c05207f73ed675db5b0c3468c20057cd)

@ggnaegi #1706  FYI

File: test/Ocelot.AcceptanceTests/Steps.cs (hunk 5 above)
Comment (raman-m) [reply test/Ocelot.AcceptanceTests/Steps.cs:89]: Please include this changes while working on #1706 if you wish

**Review by raman-m — DISMISSED** [review]
```diff
+ Approved
```

**Review by raman-m — APPROVED** [review]

**Comment by raman-m** [comment]
@ggnaegi Congrats!
We did that!
Thank you very mush for your efforts during this Sunday's evening!
