### PR TITLE
#2064 2065 #2132 #2169 Ampersand vs Slash workaround in `UpstreamTemplatePatternCreator`

### LINKED ISSUE #2064: Incorrect routing when the query parameter is in the configuration
Hi guys.

I discovered strange and different routing behavior between versions `22.0.1` and `23.0.0`.

## Expected Behavior

In version `22.0.1` the routing works well as expected.
We have the following configuration:

```json
{
    "DownstreamPathTemplate": "/{tenantId}/products?{everything}",
    "UpstreamPathTemplate": "/{tenantId}/products?{everything}",
    "UpstreamHttpMethod": [ "Get" ]
},
{
    "DownstreamPathTemplate": "/{tenantId}/products/{everything}",
    "UpstreamPathTemplate": "/{tenantId}/products/{everything}",
    "UpstreamHttpMethod": [ "Get" ]
},
```

When I call a request
```http
GET localhost/1/products/1
```

then the correct route `"/{tenantId}/products/{everything}"` is selected.

## Actual Behavior

In version `23.0.0` the `"DownstreamPathTemplate":"/{tenantId}/products?{everything}"` path is chosen for some reason, which is not correct.

## Specifications

  - Version: >23.0.0

---

Maybe this PR? [#748](https://github.com/ThreeMammals/Ocelot/pull/1911)

Any idea for a quick fix on my part?
Thank you very much.

### LINKED ISSUE #2132: Incorrect Routing when a configuration exists with query param wildcard
Ocelot now matches routes incorrectly.
This started breaking between versions 22.0.1 and 23.0.0.

If I have two configurations - 

```json
{
  "Routes": [
    {
      "DownstreamHostAndPorts": [
        {
          "Host": "{Endpoint1}"
        }
      ],
      "DownstreamPathTemplate": "/api/v1/abc?{everything}",
      "DownstreamScheme": "https",
      "UpstreamPathTemplate": "/api/v1/abc?{everything}"
    },
    {
      "DownstreamHostAndPorts": [
        {
          "Host": "{Endpoint2}"
        }
      ],
      "DownstreamPathTemplate": "/api/v1/{everything}",
      "DownstreamScheme": "https",
      "UpstreamPathTemplate": "/api/v1/abc2/{everything}"
    }
  ]
}
```

Now if I initiate a call with `/api/v1/abc2/apple?isRequired=1` 

Expected Route: `{Endpoint2}/api/v1/apple?isRequired=1`

Actually Routes to: `{Endpoint1}/api/v1/abc?isRequired=1"`

Similar issue reported in: _Originally posted by @Burgyn in https://github.com/ThreeMammals/Ocelot/discussions/2065_

### PR DESCRIPTION
**Pull request by int0x81**
## Fixes #2132 #2169 
- #2132 
- #2169 

## Closes #2064 #2065 
- #2064 
- #2065

### CODE REVIEW

**Comment by raman-m** [comment]
Thanks for the PR creation!
Why don't you request code reviews?

File: src/Ocelot/Configuration/Creator/UpstreamTemplatePatternCreator.cs [hunk 1]
```diff
@@ -40,7 +40,15 @@ public UpstreamPathTemplate Create(IRoute route)
...
-            upstreamTemplate = upstreamTemplate.Replace("?", "(|\\?)");
+
+            if (upstreamTemplate.Contains("/?"))
+            {
+                upstreamTemplate = upstreamTemplate.Replace("/?", "(\\/|\\?|$)");
+            }
+            else if (upstreamTemplate.Contains('?'))
+            {
+                upstreamTemplate = upstreamTemplate.Replace("?", "(\\/|\\?|$)");
+            }
```
Comment (raman-m) [inline src/Ocelot/Configuration/Creator/UpstreamTemplatePatternCreator.cs:51]: The `else` branch is unnecessary as the condition is already evaluated on line 40.
Why not combine both branches of the `if` statement into a single coalescing operator?
```suggestion
            var ampersand = upstreamTemplate.Contains("/?")) ? "/?" : "?";
            upstreamTemplate = upstreamTemplate.Replace(ampersand, "(\\/|\\?|$)");
```

File: test/Ocelot.UnitTests/Configuration/UpstreamTemplatePatternCreatorTests.cs [hunk 2]
```diff
@@ -215,7 +216,7 @@ public void should_create_template_pattern_that_matches_query_string()
 
         this.Given(x => x.GivenTheFollowingFileRoute(fileRoute))
             .When(x => x.WhenICreateTheTemplatePattern())
-            .Then(x => x.ThenTheFollowingIsReturned($"^(?i)/api/subscriptions/[^/]+/updates(|\\?)unitId={MatchEverything}$"))
+            .Then(x => x.ThenTheFollowingIsReturned($"^(?i)/api/subscriptions/[^/]+/updates(\\/|\\?|$)unitId={MatchEverything}$"))
```
Comment (raman-m) [inline test/Ocelot.UnitTests/Configuration/UpstreamTemplatePatternCreatorTests.cs:219]: I apologize! Why was the unit test's expected value adjusted? It appears that the old template replaced is the same.

File: test/Ocelot.UnitTests/Configuration/UpstreamTemplatePatternCreatorTests.cs [hunk 3]
```diff
@@ -230,11 +231,31 @@ public void should_create_template_pattern_that_matches_query_string_with_multip
...
             .When(x => x.WhenICreateTheTemplatePattern())
-            .Then(x => x.ThenTheFollowingIsReturned($"^(?i)/api/subscriptions/[^/]+/updates(|\\?)unitId={MatchEverything}&productId={MatchEverything}$"))
+            .Then(x => x.ThenTheFollowingIsReturned($"^(?i)/api/subscriptions/[^/]+/updates(\\/|\\?|$)unitId={MatchEverything}&productId={MatchEverything}$"))
             .And(x => ThenThePriorityIs(1))
             .BDDfy();
     }
 
+    [Theory]
+    [InlineData(@"/api/v1/abc?{everything}", false)]
+    [InlineData(@"/api/v1/abc2/{everything}", true)]
```
Comment (raman-m) [inline test/Ocelot.UnitTests/Configuration/UpstreamTemplatePatternCreatorTests.cs:241]: 1. Please include traits with the IDs from the resolved issue.
2. I notice this is test data for #2132, but I recommend adding more unit tests for issues #2064 and #2065. This would enable us to close them with this PR as well.

**Review by raman-m — CHANGES_REQUESTED** [review]
Our [development process](https://ocelot.readthedocs.io/en/latest/building/devprocess.html) mandates the inclusion of acceptance tests for even the smallest fixes. Please refer to points 4 and 5.
- [Development Process](https://github.com/ThreeMammals/Ocelot/blob/develop/docs/building/devprocess.rst) | [RST docs](https://github.com/ThreeMammals/Ocelot/tree/develop/docs)

**So, please add acceptance tests!**

File: test/Ocelot.UnitTests/Configuration/UpstreamTemplatePatternCreatorTests.cs (hunk 2 above)
Comment (int0x81) [reply test/Ocelot.UnitTests/Configuration/UpstreamTemplatePatternCreatorTests.cs]: Since I changed the template pattern in `UpstreamTemplatePatternCreator.cs`  I also had to change these tests

**Review by raman-m — CHANGES_REQUESTED** [review]
## $\color{red}{No\ acceptance\ tests!}$
Please add tests!

File: src/Ocelot/Configuration/Creator/UpstreamTemplatePatternCreator.cs (hunk 1 above)
Comment (raman-m) [reply src/Ocelot/Configuration/Creator/UpstreamTemplatePatternCreator.cs]: Don't you like this suggestion?

**Comment by raman-m** [comment]
@ggnaegi Please join to review the Finn's coding art 😋

File: src/Ocelot/Configuration/Creator/UpstreamTemplatePatternCreator.cs (hunk 1 above)
Comment (int0x81) [reply src/Ocelot/Configuration/Creator/UpstreamTemplatePatternCreator.cs]: You are definitely right about the unnecessary `else if ` statement and I removed it. :D

**Comment by int0x81** [comment]
> ## N o   a c c e p t a n c e   t e s t s !
> 
> Please include tests. If you're uncertain about where to locate the appropriate testing class within the [Ocelot.AcceptanceTests](https://github.com/ThreeMammals/Ocelot/tree/develop/test/Ocelot.AcceptanceTests) project, please inform me.
> 
> Please add tests to [Routing](https://github.com/ThreeMammals/Ocelot/tree/develop/test/Ocelot.AcceptanceTests/Routing) → [RoutingTests](https://github.com/ThreeMammals/Ocelot/blob/develop/test/Ocelot.AcceptanceTests/Routing/RoutingTests.cs)

@raman-m 
I added an acceptance test based on the issue #2065

File: src/Ocelot/Configuration/Creator/UpstreamTemplatePatternCreator.cs [hunk 4]
```diff
@@ -40,7 +40,16 @@ public UpstreamPathTemplate Create(IRoute route)
...
+            const string QUERY_START_REGEX = "(\\/$|\\/\\?|\\?|$)";
+
+            if (upstreamTemplate.Contains("/?"))
+            {
+                upstreamTemplate = upstreamTemplate.Replace("/?", QUERY_START_REGEX);
+            }
+            else
+            {
+                upstreamTemplate = upstreamTemplate.Replace("?", QUERY_START_REGEX);
+            }
```
[the remark this answers is not in the document]
Comment (ggnaegi) [reply src/Ocelot/Configuration/Creator/UpstreamTemplatePatternCreator.cs:52]: Ternary conditional operator or with `Regex.Replace`
```c#
upstreamTemplate = Regex.Replace(
        upstreamTemplate,
        @"\?|/\?",
        queryStartRegex
    );
```

File: src/Ocelot/Configuration/Creator/UpstreamTemplatePatternCreator.cs [hunk 5]
```diff
@@ -40,7 +40,16 @@ public UpstreamPathTemplate Create(IRoute route)
         if (upstreamTemplate.Contains('?'))
         {
             containsQueryString = true;
-            upstreamTemplate = upstreamTemplate.Replace("?", "(|\\?)");
+            const string QUERY_START_REGEX = "(\\/$|\\/\\?|\\?|$)";
```
Comment (ggnaegi) [inline src/Ocelot/Configuration/Creator/UpstreamTemplatePatternCreator.cs:43]: please use `queryStartRegex`

**Review by ggnaegi — CHANGES_REQUESTED** [review]
Hello, thanks a lot, it would be imho, more elegant to use a ternary operator, or even `Regex.Replace`

File: src/Ocelot/Configuration/Creator/UpstreamTemplatePatternCreator.cs (hunk 4 above)
[the remark this answers is not in the document]
Comment (int0x81) [reply src/Ocelot/Configuration/Creator/UpstreamTemplatePatternCreator.cs]: Refactored the code so ternary operator is used

File: src/Ocelot/Configuration/Creator/UpstreamTemplatePatternCreator.cs (hunk 5 above)
Comment (int0x81) [reply src/Ocelot/Configuration/Creator/UpstreamTemplatePatternCreator.cs]: renamed const var to camleCase

File: src/Ocelot/Configuration/Creator/UpstreamTemplatePatternCreator.cs (hunk 1 above)
Comment (int0x81) [reply src/Ocelot/Configuration/Creator/UpstreamTemplatePatternCreator.cs]: Gui also requested ternary operator and I got overruled :D Changed it

**Review by ggnaegi — APPROVED** [review]

**Comment by raman-m** [comment]
Reviewing and checking tests...

**Review by raman-m — CHANGES_REQUESTED** [review]
A few issues should be resolved!

**Comment by raman-m** [comment]
@int0x81 Could you explain me this 👇 
image

Why did you forbid me to push to your forked repo?
Can't I help you in pair programming, really?

File: src/Ocelot/Configuration/Creator/UpstreamTemplatePatternCreator.cs [hunk 6]
```diff
@@ -40,7 +40,11 @@ public UpstreamPathTemplate Create(IRoute route)
         if (upstreamTemplate.Contains('?'))
         {
             containsQueryString = true;
-            upstreamTemplate = upstreamTemplate.Replace("?", "(|\\?)");
+            const string queryStartRegex = "(\\/$|\\/\\?|\\?|$)";
```
[the remark this answers is not in the document]
Comment (int0x81) [reply src/Ocelot/Configuration/Creator/UpstreamTemplatePatternCreator.cs]: I checked that and it seems you're right. I removed the redundant escape characters 👍

**Comment by raman-m** [comment]
Dear Finn,
Could you please respond to [my question](https://github.com/ThreeMammals/Ocelot/pull/2225#issuecomment-2527982165)? I would like to push a small code review commit.

As per GitHub's policy on forking repositories, maintainers or owners of the base repository have write permission to the feature branches of the pull requests, but not to other branches, including protected ones.
Could you clarify what actions were taken with your forked repository that resulted in me not having push access?

File: test/Ocelot.AcceptanceTests/Routing/RoutingTests.cs [hunk 7]
```diff
@@ -666,7 +666,36 @@ public void Should_change_downstream_path_by_upstream_path_when_path_contains_ma
...
+        // Arrange
+        var downstreamPath = "/products/1";
+        var port = PortFinder.GetRandomPort();
+
+        FileConfiguration configuration = new()
+        {
+            Routes = new List<FileRoute>
+            {
+                GivenRoute(port, "/products/{everything}", "/products/{everything}"), // This route should be matched
+                GivenRoute(port, "/products?{everything}", "/products?{everything}"), // This route should not be matched
```
[the remark this answers is not in the document]
Comment (raman-m) [reply test/Ocelot.AcceptanceTests/Routing/RoutingTests.cs:683]: Better to separate! FYI 2132 has URLs and paths with query string

**Comment by int0x81** [comment]
@raman-m I usually disable the option `Allow edit by maintainers`, because I like to have control over my changes and avoid confusion. Please don't take it personally :D. However, I just enabled it so you can push changes, but please keep your changes small so I can follow up on them.

File: test/Ocelot.AcceptanceTests/Routing/RoutingTests.cs (hunk 7 above)
[the remark this answers is not in the document]
Comment (int0x81) [reply test/Ocelot.AcceptanceTests/Routing/RoutingTests.cs:683]: I will add the test later the day 👍

**Review by raman-m — APPROVED** [review]
### Ready for Delivery ✅

File: test/Ocelot.AcceptanceTests/Routing/RoutingTests.cs (hunk 7 above)
[the remark this answers is not in the document]
Comment (raman-m) [reply test/Ocelot.AcceptanceTests/Routing/RoutingTests.cs]: Already fixed in commit https://github.com/ThreeMammals/Ocelot/pull/2225/commits/b7853e0ffd72bc61f4a538e09ffec5104966555d ✔️

**Comment by raman-m** [comment]
Hello Finn,
I've prioritized this PR for the upcoming **.NET 9** release, so it's now ready for merging.
If you're okay with the minor enhancements in https://github.com/ThreeMammals/Ocelot/pull/2225/commits/b7853e0ffd72bc61f4a538e09ffec5104966555d, feel free to use the `Squash and merge` button 😉
**Please avoid using the `Create a merge commit` option❗**

**Comment by int0x81** [comment]
> Hello Finn, I've prioritized this PR for the upcoming **.NET 9** release, so it's now ready for merging. If you're okay with the minor enhancements in [b7853e0](https://github.com/ThreeMammals/Ocelot/commit/b7853e0ffd72bc61f4a538e09ffec5104966555d), feel free to press the magic `Squash and merge` button 😉 **Please avoid using the `Create a merge commit` option❗**

@raman-m 

I don't think I am authorized to merge. The button is disabled for me. But I reviewed the changes and it looks good to me, so you can also perform the merge directly

**Comment by raman-m** [comment]
> I don't think I am authorized to merge. The button is disabled for me. 

Yes, right! Only team members can merge to protected branches. **Done! Merged!**
Thank you for your contribution!
