### PR TITLE
#2375 #2376 Map non-ASCII header `HttpRequestException` to 400 Bad Request according to RFC 7230

### LINKED ISSUE #2374: Matched requests that contain invalid header values (eg with emoji) return a `502` to the client
The expected behaviour of this should be to return a `4XX` error to the client.

## Reproducing

Reproduced against the `Basic` sample on tag `24.1.0` with:

```sh
curl -X GET -v 'http://localhost:5555/ocelot/posts/askdj' \
  --header 'Accept: */*' \
  --header 'skull: 💀'
```

Prints:

```
Note: Unnecessary use of -X or --request, GET is already inferred.
* Host localhost:5555 was resolved.
* IPv6: ::1
* IPv4: 127.0.0.1
*   Trying [::1]:5555...
* Established connection to localhost (::1 port 5555) from ::1 port 57284
* using HTTP/1.x
> GET /ocelot/posts/askdj HTTP/1.1
> Host: localhost:5555
> User-Agent: curl/8.19.0
> Accept: */*
> skull: 💀
>
* Request completely sent off
< HTTP/1.1 502 Bad Gateway
< Content-Length: 0
< Date: Mon, 30 Mar 2026 14:01:37 GMT
< Server: Kestrel
<
* Connection #0 to host localhost:5555 left intact
```

## Logs

The logs shed some light:

```
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET http://localhost:5555/ocelot/posts/askdj - - -
dbug: Ocelot.Errors.Middleware.ExceptionHandlerMiddleware[0]
      RequestId: 0HNKECIQOAUK4:00000001, PreviousRequestId: -
      Ocelot pipeline started
dbug: Ocelot.DownstreamRouteFinder.Middleware.DownstreamRouteFinderMiddleware[0]
      RequestId: 0HNKECIQOAUK4:00000001, PreviousRequestId: -
      Upstream URL path: /ocelot/posts/askdj
dbug: Ocelot.DownstreamRouteFinder.Middleware.DownstreamRouteFinderMiddleware[0]
      RequestId: 0HNKECIQOAUK4:00000001, PreviousRequestId: -
      Downstream templates: /todos/{id}
info: Ocelot.RateLimiting.RateLimitingMiddleware[0]
      RequestId: 0HNKECIQOAUK4:00000001, PreviousRequestId: -
      Rate limiting is disabled for route '/ocelot/posts/{id}' via the EnableRateLimiting option.
info: Ocelot.Authentication.AuthenticationMiddleware[0]
      RequestId: 0HNKECIQOAUK4:00000001, PreviousRequestId: -
      No authentication is required for the path '/ocelot/posts/askdj' in the route /ocelot/posts/{id}.
dbug: Ocelot.Authorization.AuthorizationMiddleware[0]
      RequestId: 0HNKECIQOAUK4:00000001, PreviousRequestId: -
      No authorization needed for the route: /ocelot/posts/{id}
dbug: Ocelot.DownstreamUrlCreator.DownstreamUrlCreatorMiddleware[0]
      RequestId: 0HNKECIQOAUK4:00000001, PreviousRequestId: -
      Downstream URL: https://jsonplaceholder.typicode.com/todos/askdj
info: Ocelot.Requester.Middleware.HttpRequesterMiddleware[0]
      RequestId: 0HNKECIQOAUK4:00000001, PreviousRequestId: -
      102 unknown status code of request URI: 
dbug: Ocelot.Requester.Middleware.HttpRequesterMiddleware[0]
      RequestId: 0HNKECIQOAUK4:00000001, PreviousRequestId: -
      IHttpRequester returned an error, setting pipeline error
warn: Ocelot.Responder.Middleware.ResponderMiddleware[0]
      RequestId: 0HNKECIQOAUK4:00000001, PreviousRequestId: -
      ResponderMiddleware found 1 error ->
      ConnectionToDownstreamServiceError: Error connecting to downstream service, exception: System.Net.Http.HttpRequestException: Request headers must contain only ASCII characters.
         at System.Net.Http.HttpConnection.<WriteString>g__ThrowForInvalidCharEncoding|55_0()
         at System.Net.Http.HttpConnection.WriteString(String s, Encoding encoding)
         at System.Net.Http.HttpConnection.WriteHeaderCollection(HttpHeaders headers, String cookiesFromContainer)
         at System.Net.Http.HttpConnection.WriteHeaders(HttpRequestMessage request)
         at System.Net.Http.HttpConnection.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnection.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
         at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at Ocelot.Requester.TimeoutDelegatingHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in /home/laura/scratch_pad/Ocelot/src/Ocelot/Requester/TimeoutDelegatingHandler.cs:line 30
         at Ocelot.Requester.MessageInvokerHttpRequester.GetResponse(HttpContext httpContext) in /home/laura/scratch_pad/Ocelot/src/Ocelot/Requester/MessageInvokerHttpRequester.cs:line 29
      Setting error response for request: GET /ocelot/posts/askdj
dbug: Ocelot.Errors.Middleware.ExceptionHandlerMiddleware[0]
      RequestId: 0HNKECIQOAUK4:00000001, PreviousRequestId: -
      Ocelot pipeline finished
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/1.1 GET http://localhost:5555/ocelot/posts/askdj - 502 0 - 58.9493ms
```

### LINKED ISSUE #2376: Matched requests that contain invalid header values (eg with emoji) return a `502` to the client
> ### Discussed in https://github.com/ThreeMammals/Ocelot/discussions/2375
> 
> <div type='discussions-op-text'>
> <sup>Originally posted by @Laura7089 March 30, 2026 in issue #2374</sup> 
> </div>

The expected behaviour of this should be to return a `4XX` error to the client.

## Reproducing

Reproduced against the `Basic` sample on tag [24.1.0](https://github.com/ThreeMammals/Ocelot/releases/tag/24.1.0) with:

```shell
curl -X GET -v 'http://localhost:5555/ocelot/posts/askdj' \
  --header 'Accept: */*' \
  --header 'skull: 💀'
```

Prints:

```
Note: Unnecessary use of -X or --request, GET is already inferred.
* Host localhost:5555 was resolved.
* IPv6: ::1
* IPv4: 127.0.0.1
*   Trying [::1]:5555...
* Established connection to localhost (::1 port 5555) from ::1 port 57284
* using HTTP/1.x
> GET /ocelot/posts/askdj HTTP/1.1
> Host: localhost:5555
> User-Agent: curl/8.19.0
> Accept: */*
> skull: 💀
>
* Request completely sent off
< HTTP/1.1 502 Bad Gateway
< Content-Length: 0
< Date: Mon, 30 Mar 2026 14:01:37 GMT
< Server: Kestrel
<
* Connection #0 to host localhost:5555 left intact
```

## Logs

The logs shed some light:

```
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET http://localhost:5555/ocelot/posts/askdj - - -
dbug: Ocelot.Errors.Middleware.ExceptionHandlerMiddleware[0]
      RequestId: 0HNKECIQOAUK4:00000001, PreviousRequestId: -
      Ocelot pipeline started
dbug: Ocelot.DownstreamRouteFinder.Middleware.DownstreamRouteFinderMiddleware[0]
      RequestId: 0HNKECIQOAUK4:00000001, PreviousRequestId: -
      Upstream URL path: /ocelot/posts/askdj
dbug: Ocelot.DownstreamRouteFinder.Middleware.DownstreamRouteFinderMiddleware[0]
      RequestId: 0HNKECIQOAUK4:00000001, PreviousRequestId: -
      Downstream templates: /todos/{id}
info: Ocelot.RateLimiting.RateLimitingMiddleware[0]
      RequestId: 0HNKECIQOAUK4:00000001, PreviousRequestId: -
      Rate limiting is disabled for route '/ocelot/posts/{id}' via the EnableRateLimiting option.
info: Ocelot.Authentication.AuthenticationMiddleware[0]
      RequestId: 0HNKECIQOAUK4:00000001, PreviousRequestId: -
      No authentication is required for the path '/ocelot/posts/askdj' in the route /ocelot/posts/{id}.
dbug: Ocelot.Authorization.AuthorizationMiddleware[0]
      RequestId: 0HNKECIQOAUK4:00000001, PreviousRequestId: -
      No authorization needed for the route: /ocelot/posts/{id}
dbug: Ocelot.DownstreamUrlCreator.DownstreamUrlCreatorMiddleware[0]
      RequestId: 0HNKECIQOAUK4:00000001, PreviousRequestId: -
      Downstream URL: https://jsonplaceholder.typicode.com/todos/askdj
info: Ocelot.Requester.Middleware.HttpRequesterMiddleware[0]
      RequestId: 0HNKECIQOAUK4:00000001, PreviousRequestId: -
      102 unknown status code of request URI: 
dbug: Ocelot.Requester.Middleware.HttpRequesterMiddleware[0]
      RequestId: 0HNKECIQOAUK4:00000001, PreviousRequestId: -
      IHttpRequester returned an error, setting pipeline error
warn: Ocelot.Responder.Middleware.ResponderMiddleware[0]
      RequestId: 0HNKECIQOAUK4:00000001, PreviousRequestId: -
      ResponderMiddleware found 1 error ->
      ConnectionToDownstreamServiceError: Error connecting to downstream service, exception: System.Net.Http.HttpRequestException: Request headers must contain only ASCII characters.
         at System.Net.Http.HttpConnection.<WriteString>g__ThrowForInvalidCharEncoding|55_0()
         at System.Net.Http.HttpConnection.WriteString(String s, Encoding encoding)
         at System.Net.Http.HttpConnection.WriteHeaderCollection(HttpHeaders headers, String cookiesFromContainer)
         at System.Net.Http.HttpConnection.WriteHeaders(HttpRequestMessage request)
         at System.Net.Http.HttpConnection.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnection.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
         at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at Ocelot.Requester.TimeoutDelegatingHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in /home/laura/scratch_pad/Ocelot/src/Ocelot/Requester/TimeoutDelegatingHandler.cs:line 30
         at Ocelot.Requester.MessageInvokerHttpRequester.GetResponse(HttpContext httpContext) in /home/laura/scratch_pad/Ocelot/src/Ocelot/Requester/MessageInvokerHttpRequester.cs:line 29
      Setting error response for request: GET /ocelot/posts/askdj
dbug: Ocelot.Errors.Middleware.ExceptionHandlerMiddleware[0]
      RequestId: 0HNKECIQOAUK4:00000001, PreviousRequestId: -
      Ocelot pipeline finished
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/1.1 GET http://localhost:5555/ocelot/posts/askdj - 502 0 - 58.9493ms
```

### PR DESCRIPTION
**Pull request by Majdi-Zlitni**
## Fixes #2376 
- #2376 

## Discussed in #2375 
- #2375 

### Changes

- Created a new `BadRequestError` mapped to **HTTP 400 (Bad Request)**.
- Updated `HttpExceptionToErrorMapper` to specifically catch `HttpRequestException` instances complaining about **"only ASCII characters"**.
- Mapped this specific exception to `BadRequestError` instead of falling back to the generic `ConnectionToDownstreamServiceError` (**HTTP 502**).

---

### Why it was done

When a client sends a request containing **invalid header characters** (for example an emoji 💀), Ocelot forwards the request as-is.  
While building the outbound request, the underlying .NET `HttpClient` throws the following exception:

Previously, Ocelot's error handler mapped this exception to **HTTP 502 Bad Gateway**, which incorrectly implies a failure in the downstream service.

By intercepting this specific exception (**Late Catch**), the gateway correctly identifies it as a **malformed client request** and returns the industry-standard **HTTP 400 Bad Request** instead.

---

### Architectural note

The solution uses a **Late Catch strategy** in the exception mapper rather than introducing early validation middleware.

This avoids the CPU overhead of iterating through and validating every incoming request header, preserving Ocelot’s philosophy of acting as a **transparent, high-performance proxy**.

### CODE REVIEW

File: src/Ocelot/Requester/HttpExceptionToErrorMapper.cs [hunk 1]
```diff
@@ -47,6 +47,14 @@ public Error Map(Exception exception)
                 return new PayloadTooLargeError(exception);
             }
 
+            // Late Catch: Map the HttpRequestException to a 400 Bad Request.
+            // If the header format is invalid, HttpClient throws this exception locally.
+            // By catching it here, we ensure Ocelot returns a clean 4xx client error instead of a generic 502 Bad Gateway.
+            if (exception is HttpRequestException && exception.Message.Contains("only ASCII characters"))
```
Comment (raman-m) [inline src/Ocelot/Requester/HttpExceptionToErrorMapper.cs]: # 😆 
Amazing lifehack!

File: src/Ocelot/Middleware/OcelotPipelineExtensions.cs
Comment (raman-m) [inline src/Ocelot/Middleware/OcelotPipelineExtensions.cs:1]: I don't understand, why did you change this file?
No actual changes, right?
Please revert style formatting changes, entirely!

File: src/Ocelot/Requester/BadRequestError.cs [hunk 2]
```diff
@@ -0,0 +1,12 @@
...
+
+namespace Ocelot.Requester;
+
+public class BadRequestError : Error
+{
+    public BadRequestError(string message) 
+        : base(message, OcelotErrorCode.BadRequestError, 400)
+    {
+    }
+}
```
Comment (raman-m) [inline src/Ocelot/Requester/BadRequestError.cs]: Last line must be empty! This red circle should be removed.

File: src/Ocelot/Requester/BadRequestError.cs [hunk 3]
```diff
@@ -0,0 +1,12 @@
+using System;
+using Ocelot.Errors;
+
+namespace Ocelot.Requester;
+
+public class BadRequestError : Error
+{
+    public BadRequestError(string message) 
+        : base(message, OcelotErrorCode.BadRequestError, 400)
```
Comment (raman-m) [inline src/Ocelot/Requester/BadRequestError.cs]:
```suggestion
        : base(message, OcelotErrorCode.BadRequestError, StatusCodes.Status400BadRequest)
```

File: src/Ocelot/Responder/ErrorsToHttpStatusCodeMapper.cs [hunk 4]
```diff
@@ -61,6 +61,11 @@ public int Map(List<Error> errors)
             return 413;
         }
 
+        if (errors.Any(e => e.Code == OcelotErrorCode.BadRequestError))
+        {
+            return 400;
```
Comment (raman-m) [inline src/Ocelot/Responder/ErrorsToHttpStatusCodeMapper.cs]:
```suggestion
            return StatusCodes.Status400BadRequest;
```

**Review by raman-m — CHANGES_REQUESTED** [review]
@Majdi-Zlitni, please work on the suggestions.
This is the first round of pair programming.

File: src/Ocelot/Requester/HttpExceptionToErrorMapper.cs (hunk 1 above)
Comment (raman-m) [reply src/Ocelot/Requester/HttpExceptionToErrorMapper.cs]: We will discuss this fix later...

**Comment by raman-m** [comment]
Unit tests have failed &rarr; [build 543](https://github.com/ThreeMammals/Ocelot/actions/runs/24130548195/job/70589658863?pr=2379#step:9:287)

Did you run the tests locally? Please pay attention to the tests, since submitting code with failed tests turns the pull request into draft status.

File: src/Ocelot/Responder/ErrorsToHttpStatusCodeMapper.cs (hunk 4 above)
Comment (Majdi-Zlitni) [reply src/Ocelot/Responder/ErrorsToHttpStatusCodeMapper.cs]: Resolved

File: src/Ocelot/Requester/HttpExceptionToErrorMapper.cs (hunk 1 above)
Comment (Majdi-Zlitni) [reply src/Ocelot/Requester/HttpExceptionToErrorMapper.cs]: Thanks for your feedback! happy to discuss and learn from you

File: src/Ocelot/Requester/BadRequestError.cs (hunk 2 above)
Comment (Majdi-Zlitni) [reply src/Ocelot/Requester/BadRequestError.cs]: Got it, done!

File: src/Ocelot/Requester/BadRequestError.cs (hunk 3 above)
Comment (Majdi-Zlitni) [reply src/Ocelot/Requester/BadRequestError.cs]: Resolved

File: src/Ocelot/Middleware/OcelotPipelineExtensions.cs
Comment (Majdi-Zlitni) [reply src/Ocelot/Middleware/OcelotPipelineExtensions.cs:1]: Resolved, yes there was no changed I was using Csharpier on save formatting, I disabled it.

**Comment by Majdi-Zlitni** [comment]
I will run the tests locally and check

**Comment by raman-m** [comment]
Majdi, thanks for being proactive. 💪 

The next step is writing an acceptance test for the linked bug #2376. We must add at least one test to be able to close the bug officially.
I will re-check [the previous code review](https://github.com/ThreeMammals/Ocelot/pull/2379#pullrequestreview-4081519966) and re-think the current bug fix, which looks simple, but the upcoming acceptance testing will uncover the next steps for this PR.

**Comment by Majdi-Zlitni** [comment]
Thank you @raman-m, I’ve added the acceptance test for #2376 to cover the bug end to end, so the fix is now backed by regression coverage.

File: src/Ocelot/Requester/HttpExceptionToErrorMapper.cs (hunk 1 above)
Comment (raman-m) [reply src/Ocelot/Requester/HttpExceptionToErrorMapper.cs]: We will discuss this solution later. With high probability this solution will finally be accepted.

**Comment by raman-m** [comment]
I've changed the priorities, and this PR has been included in the current release as a patch. Thus, the patch will be a part of [.NET 10](https://github.com/ThreeMammals/Ocelot/milestone/13) release. I'm going to perform a final code review...

File: test/Ocelot.AcceptanceTests/Requester/InvalidHeaderValueTests.cs [hunk 5]
```diff
@@ -0,0 +1,86 @@
...
+
+    [Theory]
+    [InlineData("💀")]
+    [InlineData("é")]
+    [InlineData("漢")]
+    public async Task Should_return_400_bad_request_when_request_contains_non_ascii_header_value(string headerValue)
+    {
+        var basePort = BasePortSeed + (Environment.ProcessId % 10000) * PortStride;
+        var downstreamPort = basePort;
+        var gatewayPort = basePort + 1;
```
Comment (raman-m) [inline test/Ocelot.AcceptanceTests/Requester/InvalidHeaderValueTests.cs]: What is that? Only one port is required. If you use the same port‑getting expression in another acceptance test, you will get the same port, since `Environment.ProcessId` remains unchanged for the current session process. But the `Thread` ID (aka `Thread.ManagedThreadId`) is unique for every `Task` and its allocated thread.

We have a special port‑getting class from `Ocelot.Testing` namespace:

```suggestion
        var downstreamPort = PortFinder.GetRandomPort();
        var gatewayPort = PortFinder.GetRandomPort();
```

File: test/Ocelot.AcceptanceTests/Requester/InvalidHeaderValueTests.cs [hunk 6]
```diff
@@ -0,0 +1,86 @@
...
+        var route = GivenRoute(downstreamPort, "/ocelot/posts/{id}", "/todos/{id}");
+        var configuration = GivenConfiguration(route);
+
+        GivenThereIsAConfiguration(configuration);
+        GivenThereIsAServiceRunningOn(downstreamPort, DownstreamRequestPath, context =>
+        {
+            context.Response.StatusCode = (int)HttpStatusCode.OK;
+            return context.Response.WriteAsync(DownstreamResponseBody);
+        });
```
Comment (raman-m) [inline test/Ocelot.AcceptanceTests/Requester/InvalidHeaderValueTests.cs]: Mapping OK/response is not required since it is encapsulated in lots of helpers from the `Ocelot.Testing` namespace.

```suggestion
        GivenThereIsAServiceRunningOnPath(downstreamPort, DownstreamRequestPath, DownstreamResponseBody);
```

File: test/Ocelot.AcceptanceTests/Requester/InvalidHeaderValueTests.cs [hunk 7]
```diff
@@ -0,0 +1,86 @@
...
+        await GivenOcelotHostIsRunning(null, null, null, builder => builder
+            .UseKestrel()
+            .ConfigureAppConfiguration(WithBasicConfiguration)
+            .ConfigureServices(WithAddOcelot)
+            .Configure(WithUseOcelot)
+            .UseUrls(DownstreamUrl(gatewayPort)), null, null, null);
```
Comment (raman-m) [inline test/Ocelot.AcceptanceTests/Requester/InvalidHeaderValueTests.cs]: Wow! AI is wrong! There is a helper:

```suggestion
        int gatewayPort = GivenOcelotIsRunning();
```
Finally, `gatewayPort` is not required because getting the port for the gateway is encapsulated inside the helper, which returns the port value from the method.

File: test/Ocelot.AcceptanceTests/Requester/InvalidHeaderValueTests.cs [hunk 8]
```diff
@@ -0,0 +1,86 @@
...
+
+        var response = await SendRawRequestAsync(gatewayPort, headerValue);
```
Comment (raman-m) [inline test/Ocelot.AcceptanceTests/Requester/InvalidHeaderValueTests.cs]: Something interesting and intriguing is inside. 😉

File: test/Ocelot.AcceptanceTests/Requester/InvalidHeaderValueTests.cs [hunk 9]
```diff
@@ -0,0 +1,86 @@
...
+        response.FirstLine().ShouldBe(ExpectedStatusLine);
+    }
+
+    private static async Task<string> SendRawRequestAsync(int port, string headerValue)
+    {
+        using var timeout = new CancellationTokenSource(TimeSpan.FromSeconds(RequestTimeoutSeconds));
+        using var client = new TcpClient();
+        await client.ConnectAsync(System.Net.IPAddress.Loopback, port).WaitAsync(timeout.Token);
+
+        using var stream = client.GetStream();
```
Comment (raman-m) [inline test/Ocelot.AcceptanceTests/Requester/InvalidHeaderValueTests.cs:55]: Oh my gosh! 🤯 
TCP, loopback interface, and plain streams... Why? 🤨 
You just need to attach a header with the desired header value to Ocelot client, and no extra streams are required.

File: test/Ocelot.AcceptanceTests/Requester/InvalidHeaderValueTests.cs [hunk 10]
```diff
@@ -0,0 +1,86 @@
...
+        var request = $"GET {GatewayRequestPath} HTTP/1.1\r\n{HostHeaderName}: localhost:{port}\r\n{AcceptHeaderName}: */*\r\n{TestHeaderName}: {headerValue}\r\n{ConnectionHeaderName}: close\r\n\r\n";
```
Comment (raman-m) [inline test/Ocelot.AcceptanceTests/Requester/InvalidHeaderValueTests.cs]: Is that another testing/sending request technique based on client streams? It's not something we use in acceptance testing, but, seems, it calls Ocelot's endpoint.

The code is very hard to read!
You just need to specify a header, attach it, and send the request.

File: test/Ocelot.AcceptanceTests/Requester/InvalidHeaderValueTests.cs [hunk 11]
```diff
@@ -0,0 +1,86 @@
...
+
+        return response.ToString();
+    }
+}
+
+internal static class InvalidHeaderValueTestsExtensions
+{
+    public static string FirstLine(this string response)
+    => response.Split(new[] { "\r\n", "\n" }, StringSplitOptions.RemoveEmptyEntries)[0];
+}
```
Comment (raman-m) [inline test/Ocelot.AcceptanceTests/Requester/InvalidHeaderValueTests.cs]: AI generated bull shit code

File: test/Ocelot.UnitTests/Responder/ErrorsToHttpStatusCodeMapperTests.cs [hunk 12]
```diff
@@ -73,15 +80,15 @@ public void Should_return_bad_gateway_error(OcelotErrorCode errorCode)
...
-    [Trait("PR", "1769")] // https://github.com/ThreeMammals/Ocelot/pull/1769
-    public void Should_return_request_entity_too_large()
-    {
-        ShouldMapErrorsToStatusCode(new() { OcelotErrorCode.PayloadTooLargeError }, HttpStatusCode.RequestEntityTooLarge);
-    }
+    [Trait("PR", "1769")] // https://github.com/ThreeMammals/Ocelot/pull/1769
+    public void Should_return_request_entity_too_large()
+    {
+        ShouldMapErrorsToStatusCode(new() { OcelotErrorCode.PayloadTooLargeError }, HttpStatusCode.RequestEntityTooLarge);
+    }
```
Comment (raman-m) [inline test/Ocelot.UnitTests/Responder/ErrorsToHttpStatusCodeMapperTests.cs]: Fictitious change! It must be reverted!

File: test/Ocelot.UnitTests/Kubernetes/PollKubeTests.cs
Comment (raman-m) [inline test/Ocelot.UnitTests/Kubernetes/PollKubeTests.cs:1]: Thanks for additional test coverage!

**Comment by Majdi-Zlitni** [comment]
Thanks @raman-m for the update and for including this in the release. I really appreciate the opportunity to contribute and learn. Looking forward to your final review.

File: src/Ocelot/Requester/HttpExceptionToErrorMapper.cs (hunk 1 above)
Comment (raman-m) [inline src/Ocelot/Requester/HttpExceptionToErrorMapper.cs]: It’s hard to judge this solution until a valid acceptance test has been written.

I believe we can improve this area, since the `Message.Contains` method handles a specific user scenario. But what about codes, internal exceptions, and so on? We should inspect the generated exception and reuse its state rather than relying only on messages.

We might also consider covering more scenarios that return a `BadRequestError` response.
Given the purpose of `BadRequestError`, it should cover all exceptions that result in a 400 Bad Request status. So, I'd expect more `if-else` block(s).
You (we) might be inspired by this https://github.com/ThreeMammals/Ocelot/discussions/2375#discussioncomment-16409071.

File: test/Ocelot.AcceptanceTests/Requester/InvalidHeaderValueTests.cs [hunk 13]
```diff
@@ -0,0 +1,86 @@
...
+    private const string AcceptHeaderName = "Accept";
+    private const string ConnectionHeaderName = "Connection";
+    private const string TestHeaderName = "skull";
+    private const string ExpectedStatusLine = "HTTP/1.1 400 Bad Request";
+
+    [Theory]
+    [InlineData("💀")]
+    [InlineData("é")]
+    [InlineData("漢")]
+    public async Task Should_return_400_bad_request_when_request_contains_non_ascii_header_value(string headerValue)
```
Comment (raman-m) [inline test/Ocelot.AcceptanceTests/Requester/InvalidHeaderValueTests.cs]: I suggest adding a second parameter to the theory—a parameter of type `HttpStatusCode`.

The 4th test case could verify the OK status if the header contains only ASCII characters. It’s a trivial test, but intentional. I expect that we haven’t written a separate `Fact`.

**Review by raman-m — CHANGES_REQUESTED** [review]
This is the second round, and my suggestions are below.
I will push a commit tomorrow with my review comments, if not fixed by you.

My current concern is that the acceptance test requires refactoring to use helpers from the `Ocelot.Testing` namespace. The test should be shorter and easier to read.
After that, we will be able to verify the bug fix, continue debugging, and find an optimal solution.

P.S. AI helps, but it sometimes produces redundant and unusual code that doesn’t match the current style and libraries.

File: test/Ocelot.AcceptanceTests/Requester/InvalidHeaderValueTests.cs (hunk 9 above)
Comment (raman-m) [reply test/Ocelot.AcceptanceTests/Requester/InvalidHeaderValueTests.cs:55]: Examples are inside the `HeaderTests`:
https://github.com/ThreeMammals/Ocelot/blob/5eeb9cccad4b45d8b409310c43582e827de97e06/test/Ocelot.AcceptanceTests/Transformations/HeaderTests.cs#L31

Comment (Majdi-Zlitni) [reply test/Ocelot.AcceptanceTests/Requester/InvalidHeaderValueTests.cs:55]: Resolved!

File: test/Ocelot.AcceptanceTests/Requester/InvalidHeaderValueTests.cs (hunk 13 above)
Comment (Majdi-Zlitni) [reply test/Ocelot.AcceptanceTests/Requester/InvalidHeaderValueTests.cs]: Done!

File: src/Ocelot/Requester/HttpExceptionToErrorMapper.cs (hunk 1 above)
Comment (Majdi-Zlitni) [reply src/Ocelot/Requester/HttpExceptionToErrorMapper.cs]: Appreciate the guidance

File: test/Ocelot.UnitTests/Responder/ErrorsToHttpStatusCodeMapperTests.cs (hunk 12 above)
Comment (Majdi-Zlitni) [reply test/Ocelot.UnitTests/Responder/ErrorsToHttpStatusCodeMapperTests.cs]: Reverted!

File: test/Ocelot.AcceptanceTests/Requester/InvalidHeaderValueTests.cs (hunk 11 above)
Comment (Majdi-Zlitni) [reply test/Ocelot.AcceptanceTests/Requester/InvalidHeaderValueTests.cs]: Yeah, it help but I need to improve my AI code review

File: test/Ocelot.AcceptanceTests/Requester/InvalidHeaderValueTests.cs (hunk 10 above)
Comment (Majdi-Zlitni) [reply test/Ocelot.AcceptanceTests/Requester/InvalidHeaderValueTests.cs]: Done!

**Comment by Majdi-Zlitni** [comment]
Ocelot is really cool 😎 but found it a little hard for me, I really enjoy learning from it and hope to keep on learning, also I need to improve my AI gen code review to contribute more effectively.
Thanks @raman-m for your patience🙏

File: test/Ocelot.UnitTests/Responder/ErrorsToHttpStatusCodeMapperTests.cs (hunk 12 above)
Comment (raman-m) [reply test/Ocelot.UnitTests/Responder/ErrorsToHttpStatusCodeMapperTests.cs]: Not reverted actually, you just [removed](https://github.com/ThreeMammals/Ocelot/pull/2379/changes/d1246cb4f01931458b9f1854629e449ea7889687#diff-d7747586dfe73d2c3b28db54f3c243d61fdb3a51c79c686fe83105fd2481f9ecL85-L91) the test entirely, but the test must be kept.
Seems you didn't understand me, sorry. Fake changes are those one which comes to GH diff in Files change tab but the change was just in replacing New Line chars, but GitHub highlights these changes.
In dev process doc we described this problem 👇 
- [EOL Gotchas | Ocelot Dev Process](https://ocelot.readthedocs.io/en/latest/building/devprocess.html#eol-gotchas)

Comment (Majdi-Zlitni) [reply test/Ocelot.UnitTests/Responder/ErrorsToHttpStatusCodeMapperTests.cs]: Gotcha i reverted it and re apply my changes

**Comment by raman-m** [comment]
@Majdi-Zlitni Please stop pushing commits! You've done a lot from your side. Thank you!
I will do the rest of the work.

File: test/Ocelot.AcceptanceTests/Requester/InvalidHeaderValueTests.cs [hunk 14]
```diff
@@ -0,0 +1,41 @@
...
+    private async Task WhenIGetUrlOnTheApiGatewaySafely(string url)
+    {
+        try
+        {
+            await WhenIGetUrlOnTheApiGateway(url);
+        }
+        catch (HttpRequestException)
+        {
+            response = new HttpResponseMessage(HttpStatusCode.BadRequest);
+        }
```
Comment (raman-m) [inline test/Ocelot.AcceptanceTests/Requester/InvalidHeaderValueTests.cs]: Yeah, that is funny.
This life hack — which catches the `HttpClient` exception early by adjusting the response to return a 400 status — actually triggers the exception too early. Here is the call stack it produces:
```
   at System.Net.Http.HttpConnection.<WriteString>g__ThrowForInvalidCharEncoding|55_0()
   at System.Net.Http.HttpConnection.WriteString(String s, Encoding encoding)
   at System.Net.Http.HttpConnection.WriteHeaderCollection(HttpHeaders headers, String cookiesFromContainer)
   at System.Net.Http.HttpConnection.WriteHeaders(HttpRequestMessage request)
   at System.Net.Http.HttpConnection.<SendAsync>d__56.MoveNext()
   at System.Net.Http.HttpConnection.<SendAsync>d__56.MoveNext()
   at System.Net.Http.HttpConnectionPool.<SendWithVersionDetectionAndRetryAsync>d__52.MoveNext()
   at System.Net.Http.DiagnosticsHandler.<SendAsyncCore>d__10.MoveNext()
   at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.GetResult()
   at System.Net.Http.RedirectHandler.<SendAsync>d__4.MoveNext()
   at System.Net.Http.SocketsHttpHandler.<<SendAsync>g__CreateHandlerAndSendAsync|115_0>d.MoveNext()
   at System.Net.Http.HttpClient.<<SendAsync>g__Core|83_0>d.MoveNext()
   at Ocelot.Testing.AcceptanceSteps.<WhenIGetUrlOnTheApiGateway>d__86.MoveNext() in D:\github\Ocelot\Majdi-Zlitni\Ocelot\testing\AcceptanceSteps.cs:line 368
   at Ocelot.AcceptanceTests.Requester.InvalidHeaderValueTests.<WhenIGetUrlOnTheApiGatewaySafely>d__1.MoveNext() in D:\github\Ocelot\Majdi-Zlitni\Ocelot\test\Ocelot.AcceptanceTests\Requester\InvalidHeaderValueTests.cs:line 34
```
However, the original bug #2374 has a different call stack:
```
         at System.Net.Http.HttpConnection.<WriteString>g__ThrowForInvalidCharEncoding|55_0()
         at System.Net.Http.HttpConnection.WriteString(String s, Encoding encoding)
         at System.Net.Http.HttpConnection.WriteHeaderCollection(HttpHeaders headers, String cookiesFromContainer)
         at System.Net.Http.HttpConnection.WriteHeaders(HttpRequestMessage request)
         at System.Net.Http.HttpConnection.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnection.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
         at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at Ocelot.Requester.TimeoutDelegatingHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in /home/laura/scratch_pad/Ocelot/src/Ocelot/Requester/TimeoutDelegatingHandler.cs:line 30
         at Ocelot.Requester.MessageInvokerHttpRequester.GetResponse(HttpContext httpContext) in /home/laura/scratch_pad/Ocelot/src/Ocelot/Requester/MessageInvokerHttpRequester.cs:line 29
```
As a result, we are reproducing the same bug on the `HttpClient` side, and the actual request never reaches the Ocelot side. This happened because the acceptance test was changed when I asked to use our testing helpers.

**I was wrong — the [original test version](https://github.com/ThreeMammals/Ocelot/pull/2379/changes/ee31a53f32e0ac53fc53e73c35cc5631b287eb7b) actually used the correct approach to emulate a `curl` request, based on `TcpClient` streams.**

Tomorrow I will rewrite the test based on the original version. The AI coding agent was right when it suggested how to properly emulate `curl` requests in .NET apps.
In the end, we must use plain `TcpClient` streams only if we want to reliably reproduce the bug.
This is my fault 🙃

Comment (raman-m) [reply test/Ocelot.AcceptanceTests/Requester/InvalidHeaderValueTests.cs]: Done &rarr; https://github.com/ThreeMammals/Ocelot/pull/2379/commits/730afbcde2e8e468f33c62c6c2e55420e733b8e0

File: src/Ocelot/Requester/HttpExceptionToErrorMapper.cs [hunk 15]
```diff
@@ -30,26 +30,36 @@ public Error Map(Exception exception)
...
         }
 
+        // Bug #2376 -> https://github.com/ThreeMammals/Ocelot/issues/2376
+        // Late Catch: Map the HttpRequestException to a 400 Bad Request.
+        // If the header format is invalid, HttpClient throws this exception locally.
+        // By catching it here, we ensure Ocelot returns a clean 4xx client error instead of a generic 502 Bad Gateway.
+        if (exception is HttpRequestException && exception.Message.Contains("Request headers must contain only ASCII characters."))
+        {
+            return new BadRequestError(exception); // -> 400 Bad Request
+        }
```
Comment (raman-m) [inline src/Ocelot/Requester/HttpExceptionToErrorMapper.cs:48]: It works!

Ideally, the conversion could test the current headers and find the bad header, but that would require significant refactoring after changing the `IExceptionToErrorMapper` interface so that the `Map` method could have a second parameter, for example:
```diff
- Error Map(Exception exception);
+ Error Map(Exception exception, HttpContext context);
```

**Review by raman-m — APPROVED** [review]
## Ready for delivery ✅ 
The solution is not ideal, but it works.

File: src/Ocelot/Requester/HttpExceptionToErrorMapper.cs (hunk 15 above)
Comment (raman-m) [reply src/Ocelot/Requester/HttpExceptionToErrorMapper.cs:48]: ### TODO
1. Extend both `IExceptionToErrorMapper` and `IErrorsToHttpStatusCodeMapper` by adding an `HttpContext` argument.
2. Detect the faulty header early inside `Ocelot.Requester` and attach the information to the exception data. This will allow smarter reporting in other middleware and services.
